//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandlerWalletItems
{
}

- (void)triggerImport;	// IMP=0x00400000000de689
- (void)updatePossibleActions;	// IMP=0x00100000000de3a5
- (id)suitableContentsDescription;	// IMP=0x00100000000de067
- (long long)transferTypes;	// IMP=0x00100000000de032
- (_Bool)canHandleTransfer;	// IMP=0x00100000000ddd6c
- (id)initWithTransfer:(id)arg1;	// IMP=0x00100000000ddd36

@end

