//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSMutableDictionary, NSString, NSUUID, NSXPCListener;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface IDSSimSupportLocalServer : NSObject
{
    _Bool _transportSuspended;	// 8 = 0x8
    NSUUID *_localDeviceUDID;	// 16 = 0x10
    NSMutableDictionary *_localConnections;	// 24 = 0x18
    NSMutableDictionary *_localConnectionsByServiceName;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_localConnectionsQueue;	// 40 = 0x28
    NSXPCListener *_localListener;	// 48 = 0x30
    NSMutableDictionary *_perClientServers;	// 56 = 0x38
    NSDate *_dateForNextDelayedData;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_sendQueue;	// 72 = 0x48
    NSObject<OS_dispatch_source> *_sendTimerSource;	// 80 = 0x50
    NSMutableDictionary *_outgoingMessages;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_receiveQueue;	// 96 = 0x60
    NSObject<OS_dispatch_source> *_receiveTimerSource;	// 104 = 0x68
    NSMutableDictionary *_receivedMessages;	// 112 = 0x70
    NSObject<OS_dispatch_queue> *_pairingStateQueue;	// 120 = 0x78
    NSUUID *_activeSimulatorID;	// 128 = 0x80
    NSObject<OS_dispatch_queue> *_remoteConnectionsQueue;	// 136 = 0x88
    NSMutableDictionary *_remoteConnections;	// 144 = 0x90
}

+ (id)sharedInstance;	// IMP=0x0020000000002fa2
- (void).cxx_destruct;	// IMP=0x0020000000009ad4
@property(retain, nonatomic) NSMutableDictionary *remoteConnections; // @synthesize remoteConnections=_remoteConnections;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *remoteConnectionsQueue; // @synthesize remoteConnectionsQueue=_remoteConnectionsQueue;
@property _Bool transportSuspended; // @synthesize transportSuspended=_transportSuspended;
@property(copy) NSUUID *activeSimulatorID; // @synthesize activeSimulatorID=_activeSimulatorID;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *pairingStateQueue; // @synthesize pairingStateQueue=_pairingStateQueue;
@property(retain, nonatomic) NSMutableDictionary *receivedMessages; // @synthesize receivedMessages=_receivedMessages;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *receiveTimerSource; // @synthesize receiveTimerSource=_receiveTimerSource;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *receiveQueue; // @synthesize receiveQueue=_receiveQueue;
@property(retain, nonatomic) NSMutableDictionary *outgoingMessages; // @synthesize outgoingMessages=_outgoingMessages;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *sendTimerSource; // @synthesize sendTimerSource=_sendTimerSource;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *sendQueue; // @synthesize sendQueue=_sendQueue;
@property(retain) NSDate *dateForNextDelayedData; // @synthesize dateForNextDelayedData=_dateForNextDelayedData;
@property(retain, nonatomic) NSMutableDictionary *perClientServers; // @synthesize perClientServers=_perClientServers;
@property(retain) NSXPCListener *localListener; // @synthesize localListener=_localListener;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *localConnectionsQueue; // @synthesize localConnectionsQueue=_localConnectionsQueue;
@property(retain) NSMutableDictionary *localConnectionsByServiceName; // @synthesize localConnectionsByServiceName=_localConnectionsByServiceName;
@property(retain) NSMutableDictionary *localConnections; // @synthesize localConnections=_localConnections;
@property(retain, nonatomic) NSUUID *localDeviceUDID; // @synthesize localDeviceUDID=_localDeviceUDID;
- (id)_resolveDestinationDeviceID:(id)arg1;	// IMP=0x001000000000981c
- (double)delayForDataOfLength:(unsigned long long)arg1;	// IMP=0x00100000000095b0
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0010000000009131
- (void)switchToActivePairedDeviceWithSimulatorID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000008ee4
- (void)deletePairedDeviceWithSimulatorID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000008c7e
- (void)addPairedDeviceWithSimulatorID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000008a31
- (void)transportResumeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000087ce
- (void)transportSuspendWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000008530
- (void)transportDisconnectWithSimulatorID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000008334
- (void)transportConnectWithSimulatorID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000007a7e
- (id)localConnectionsCopy;	// IMP=0x0010000000007960
- (id)localConnectionForService:(id)arg1;	// IMP=0x001000000000781f
- (void)unregisterPerClientServer:(id)arg1 forService:(id)arg2;	// IMP=0x0010000000007747
- (void)registerPerClientServer:(id)arg1 forService:(id)arg2;	// IMP=0x001000000000746a
- (void)getNetworkSimulationState:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000007386
- (void)setNetworkSimulation:(id)arg1 enabled:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000007025
- (void)_sendConnectionStateToClientsForSimulatorID:(id)arg1;	// IMP=0x0010000000006d29
- (void)getCurrentConnectedSimulatorUniqueID:(CDUnknownBlockType)arg1;	// IMP=0x0010000000006cbd
- (void)getConnectionState:(CDUnknownBlockType)arg1;	// IMP=0x0010000000006c3f
- (unsigned long long)connectionStateForSimulatorID:(id)arg1;	// IMP=0x0010000000006987
- (id)_attemptToSendDataDict:(id)arg1 toDestination:(id)arg2;	// IMP=0x0010000000006383
- (void)_processSendQueue;	// IMP=0x0010000000005602
- (void)sendData:(id)arg1 withServiceName:(id)arg2 messageID:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000005532
- (void)sendData:(id)arg1 toDevice:(id)arg2 withServiceName:(id)arg3 messageID:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000004ecb
- (void)handleControlTraffic:(id)arg1;	// IMP=0x0010000000004c49
- (void)_reEnqueueReceivedMessage:(id)arg1 withServiceName:(id)arg2;	// IMP=0x0010000000004ae5
- (void)_processReceivedDataQueueForService:(id)arg1;	// IMP=0x001000000000423e
- (void)_processReceiveQueue;	// IMP=0x0010000000004089
- (void)receiveData:(id)arg1 withServiceName:(id)arg2 messageID:(id)arg3 senderDeviceID:(id)arg4;	// IMP=0x00100000000039a9
- (void)suspend;	// IMP=0x001000000000396c
- (void)resume;	// IMP=0x001000000000392f
- (void)dealloc;	// IMP=0x00100000000038ec
- (id)init;	// IMP=0x0010000000002ff7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

