//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ClassKit/CLSFavorite.h>

@class NSObject, NSString;
@protocol PDDatabaseValue;

@interface CLSFavorite (PDDatabaseEntity)
+ (_Bool)migrateFromVersion:(unsigned long long)arg1 finalVersion:(out unsigned long long *)arg2 inDatabase:(id)arg3;	// IMP=0x002000000003d867
+ (id)entityName;	// IMP=0x001000000003d268
+ (id)recordType;	// IMP=0x001000000007077c
- (void)bindTo:(id)arg1;	// IMP=0x001000000003d557
- (id)initWithDatabaseRow:(id)arg1;	// IMP=0x001000000003d275
@property(readonly, nonatomic) NSString *parentReferenceName;
- (void)populate:(id)arg1;	// IMP=0x0010000000070a88
- (id)initWithCKRecord:(id)arg1;	// IMP=0x0010000000070791
@property(readonly, nonatomic) long long syncableItemType;

// Remaining properties
@property(readonly, nonatomic) unsigned long long changeHash;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic, getter=isDeleteTracked) _Bool deleteTracked;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<PDDatabaseValue> *identityValue;
@property(readonly) Class superclass;
@end

