//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PDBoolProperty
{
    _Bool _value;	// 16 = 0x10
}

+ (id)valueSQLType;	// IMP=0x0040000000191c06
+ (_Bool)migrateFromVersion:(unsigned long long)arg1 finalVersion:(out unsigned long long *)arg2 inDatabase:(id)arg3;	// IMP=0x0010000000191992
+ (id)entityName;	// IMP=0x0010000000191985
- (void)bindTo:(id)arg1;	// IMP=0x0020000000191b64
- (id)initWithDatabaseRow:(id)arg1;	// IMP=0x0010000000191acb

@end

