//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CKContainer, CKDatabase, CKRecordZone, NSMutableArray;

@interface PDCKOperation
{
    CKContainer *_container;	// 8 = 0x8
    CKRecordZone *_progressZone;	// 16 = 0x10
    CKRecordZone *_teacherZone;	// 24 = 0x18
    CKRecordZone *_assetZone;	// 32 = 0x20
    CKRecordZone *_surveyAnswerZone;	// 40 = 0x28
    NSMutableArray *_operations;	// 48 = 0x30
    _Bool _hasCachedTeacherZone;	// 56 = 0x38
    _Bool _hasCachedProgressZone;	// 57 = 0x39
}

+ (id)recordTypeToEntityMap;	// IMP=0x0020000000168b8d
+ (id)syncableEntities;	// IMP=0x00100000001688d4
- (void).cxx_destruct;	// IMP=0x0020000000169e39
@property(readonly, nonatomic) _Bool hasCachedProgressZone; // @synthesize hasCachedProgressZone=_hasCachedProgressZone;
@property(readonly, nonatomic) _Bool hasCachedTeacherZone; // @synthesize hasCachedTeacherZone=_hasCachedTeacherZone;
@property(readonly, nonatomic) CKContainer *container; // @synthesize container=_container;
- (void)deleteSyncMetadataAssociatedWithRecordID:(id)arg1;	// IMP=0x0010000000169cb5
- (_Bool)updateSyncMetadataForRecord:(id)arg1;	// IMP=0x0010000000169a28
- (id)syncMetadataForRecord:(id)arg1;	// IMP=0x00100000001698bc
- (id)syncMetadataForRecordID:(id)arg1;	// IMP=0x00100000001697c3
- (id)recordIDForSyncItem:(id)arg1;	// IMP=0x00100000001696fa
- (id)zoneIDForSyncItem:(id)arg1;	// IMP=0x001000000016967e
- (void)prepare;	// IMP=0x00100000001694e4
@property(readonly, nonatomic) CKRecordZone *surveyAnswerZone;
@property(readonly, nonatomic) CKRecordZone *assetZone;
@property(readonly, nonatomic) CKRecordZone *teacherZone;
@property(readonly, nonatomic) CKRecordZone *progressZone;
- (id)_zoneWithName:(id)arg1;	// IMP=0x00100000001692d5
- (double)retryDelayForServerBusyError:(id)arg1;	// IMP=0x0010000000169242
- (_Bool)isServerBusyError:(id)arg1;	// IMP=0x00100000001691d3
- (_Bool)isNetworkError:(id)arg1;	// IMP=0x0010000000169176
@property(readonly, nonatomic) CKDatabase *cloudDatabase;
@property(nonatomic, getter=isBootstrapped) _Bool bootstrapped;
- (void)abort;	// IMP=0x001000000016904a
- (void)performCKDatabaseOperation:(id)arg1;	// IMP=0x0010000000168e80
- (id)initWithDatabase:(id)arg1 container:(id)arg2;	// IMP=0x0010000000168e08

@end

