//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSString;

@interface PDDPPersonLinkId : PBCodable
{
    NSString *_context;	// 8 = 0x8
    NSString *_personLinkId;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000479a2
@property(retain, nonatomic) NSString *context; // @synthesize context=_context;
@property(retain, nonatomic) NSString *personLinkId; // @synthesize personLinkId=_personLinkId;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000478f5
- (unsigned long long)hash;	// IMP=0x00100000000478a8
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000477e0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000047742
- (void)copyTo:(id)arg1;	// IMP=0x00100000000476df
- (void)writeTo:(id)arg1;	// IMP=0x0010000000047682
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000047675
- (id)dictionaryRepresentation;	// IMP=0x001000000004745f
- (id)description;	// IMP=0x00100000000473b0
@property(readonly, nonatomic) _Bool hasContext;
@property(readonly, nonatomic) _Bool hasPersonLinkId;

@end

