//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray;

@interface PDDPPublishStateChangeResponse : PBCodable
{
    NSMutableArray *_payloads;	// 8 = 0x8
}

+ (Class)payloadType;	// IMP=0x0020000000173436
- (void).cxx_destruct;	// IMP=0x0020000000173eba
@property(retain, nonatomic) NSMutableArray *payloads; // @synthesize payloads=_payloads;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000173d60
- (unsigned long long)hash;	// IMP=0x0010000000173d43
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000173ca9
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000173ae6
- (void)copyTo:(id)arg1;	// IMP=0x0010000000173a27
- (void)writeTo:(id)arg1;	// IMP=0x00100000001738f7
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000173729
- (id)dictionaryRepresentation;	// IMP=0x00100000001734f6
- (id)description;	// IMP=0x0010000000173447
- (id)payloadAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000173419
- (unsigned long long)payloadsCount;	// IMP=0x00100000001733fc
- (void)addPayload:(id)arg1;	// IMP=0x0010000000173392
- (void)clearPayloads;	// IMP=0x0010000000173375

@end

