//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AVVoiceTriggerClient, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface CSAVVCRecordingClientMonitor
{
    unsigned long long _numOfAVVCRecordingClients;	// 8 = 0x8
    AVVoiceTriggerClient *_alwaysOnProcessorController;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x00200000000c3994
- (void).cxx_destruct;	// IMP=0x00200000000c4198
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) AVVoiceTriggerClient *alwaysOnProcessorController; // @synthesize alwaysOnProcessorController=_alwaysOnProcessorController;
@property(readonly, nonatomic) unsigned long long numOfAVVCRecordingClients; // @synthesize numOfAVVCRecordingClients=_numOfAVVCRecordingClients;
- (void)_didReceiveAVVCRecordingClientNumberChange:(unsigned long long)arg1;	// IMP=0x00100000000c409a
- (void)CSAudioServerCrashMonitorDidReceiveServerCrash:(id)arg1;	// IMP=0x00100000000c3fb5
- (void)_stopMonitoring;	// IMP=0x00100000000c3ed8
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x00100000000c3a8d
- (id)init;	// IMP=0x00100000000c39e9

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

