//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CSEndpointerSettings : NSObject
{
    _Bool _disableEndpointer;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00200000000e7292
@property(readonly, nonatomic) _Bool disableEndpointer; // @synthesize disableEndpointer=_disableEndpointer;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000000e72d8
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000000e729a
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000e7287
- (id)description;	// IMP=0x00100000000e7218
- (id)initWithDisableEndpointer:(_Bool)arg1;	// IMP=0x00100000000e71dd

@end

