//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol CSMyriadSelfTriggerCoordinatorDelegate;

@interface CSMyriadSelfTriggerCoordinator : NSObject
{
    id <CSMyriadSelfTriggerCoordinatorDelegate> _delegate;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000080f96
@property(nonatomic) __weak id <CSMyriadSelfTriggerCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)selfTriggerDetector:(id)arg1 didDetectSelfTrigger:(id)arg2;	// IMP=0x0010000000080cd9

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

