//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <FTServices/FTIDSMessage.h>

@class NSNumber, NSString;

@interface IDSKTOptInStatusMessage : FTIDSMessage
{
    NSString *_hardwareVersion;	// 232 = 0xe8
    NSString *_osVersion;	// 240 = 0xf0
    NSNumber *_isOptIn;	// 248 = 0xf8
    NSNumber *_responseStatus;	// 256 = 0x100
    NSString *_responseMessage;	// 264 = 0x108
}

- (void).cxx_destruct;	// IMP=0x00200000004d1480
@property(retain, nonatomic) NSString *responseMessage; // @synthesize responseMessage=_responseMessage;
@property(retain, nonatomic) NSNumber *responseStatus; // @synthesize responseStatus=_responseStatus;
@property(retain, nonatomic) NSNumber *isOptIn; // @synthesize isOptIn=_isOptIn;
@property(retain, nonatomic) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(retain, nonatomic) NSString *hardwareVersion; // @synthesize hardwareVersion=_hardwareVersion;
- (id)messageBody;	// IMP=0x00100000004d0dc0
- (id)requiredKeys;	// IMP=0x00100000004d0d10
- (id)bagKey;	// IMP=0x00100000004d0cf0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000004d0b50

@end

