//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData;

@interface IDSPeerAccessoryMessage
{
    NSData *_accessToken;	// 264 = 0x108
}

- (void).cxx_destruct;	// IMP=0x00200000004e5700
@property(copy) NSData *accessToken; // @synthesize accessToken=_accessToken;
- (id)messageBody;	// IMP=0x00100000004e5460
- (id)requiredKeys;	// IMP=0x00100000004e53c0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000004e5300

@end

