//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SMSScreenshotUIImages : NSObject
{
}

+ (void)saveImage:(id)arg1 filePath:(id)arg2 fileName:(id)arg3 withHeader:(id)arg4;	// IMP=0x004000000002055a
+ (id)imageFromView:(id)arg1;	// IMP=0x001000000002042c
+ (id)getKeyWindow;	// IMP=0x00100000000200f4
+ (id)captureScreenshot;	// IMP=0x0010000000020095

@end

