//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GeoServices/GEOServer.h>

@interface GEOResourceServer : GEOServer
{
}

+ (id)identifier;	// IMP=0x002000000001a263
- (void)fetchWithRequest:(id)arg1;	// IMP=0x001000000002f70d
- (_Bool)handleIncomingMessage:(id)arg1 withObject:(id)arg2 fromPeer:(id)arg3;	// IMP=0x001000000001a270

@end

