//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSSet, NSString;

@interface PDDiscoveryAnalytics : NSObject
{
}

- (void)clearVisitorIDAndRelatedData;	// IMP=0x00200000003628b0
- (id)_initalizeCountForDictionaryWithKey:(id)arg1 forItemIdentifier:(id)arg2;	// IMP=0x00100000003626f6
- (id)_countForDictionaryWithKey:(id)arg1 forItemIdentifier:(id)arg2;	// IMP=0x0010000000362608
- (void)_incrementCountForCountsDictionaryWithKey:(id)arg1 forItemIdentifier:(id)arg2;	// IMP=0x0010000000362495
- (id)_rotateVisitorIDIfNecessaryWithVisitorIDCreationInterval:(double)arg1;	// IMP=0x00100000003622f4
- (id)_createOrRotateVisitorIDIfNecessary;	// IMP=0x00100000003621d8
- (id)_createVisitorID;	// IMP=0x00100000003620f3
@property(readonly, nonatomic) NSSet *identifiersOfCompletedDiscoveryItems;
@property(readonly, nonatomic) NSSet *identifiersOfTappedDiscoveryItems;
@property(readonly, nonatomic) NSSet *identifiersOfDismissedDiscoveryItems;
@property(readonly, nonatomic) NSSet *identifiersOfExpandedDiscoveryItems;
@property(readonly, nonatomic) NSString *lastTappedCTAItemIdentifier;
- (void)endReporingDiscoveryAnalytics;	// IMP=0x0010000000361de2
- (void)beginReporingDiscoveryAnalytics;	// IMP=0x0010000000361dbf
- (void)discoveryItemWithIdentifier:(id)arg1 callToAction:(long long)arg2 wasScrolledToTheBottom:(_Bool)arg3;	// IMP=0x0010000000361c9d
- (void)discoveryItemWithIdentifier:(id)arg1 callToAction:(long long)arg2 isScrollable:(_Bool)arg3;	// IMP=0x0010000000361b7b
- (void)discoveryItemWithIdentifier:(id)arg1 launchedWithReferralSource:(unsigned long long)arg2 cardCount:(unsigned long long)arg3;	// IMP=0x0010000000361943
- (void)removedAllDiscoveryItems;	// IMP=0x0010000000361931
- (void)completedDiscoveryItemCTA;	// IMP=0x001000000036157c
- (void)tappedDiscoveryItemCTA:(long long)arg1 itemIdentifier:(id)arg2 cardSize:(long long)arg3;	// IMP=0x00100000003611f4
- (void)dismissedDiscoveryItemWithIdentifier:(id)arg1 callToAction:(long long)arg2 cardSize:(long long)arg3;	// IMP=0x0010000000360ed3
- (void)expandedDiscoveryItemWithIdentifier:(id)arg1 callToAction:(long long)arg2 afterSwipingToCard:(_Bool)arg3 multipleStoryCardsAvailable:(_Bool)arg4 cardSize:(long long)arg5;	// IMP=0x0010000000360b46
- (void)displayedDiscoveryItemWithIdentifier:(id)arg1 isWelcomeCard:(_Bool)arg2 afterSwipingToCard:(_Bool)arg3 multipleStoryCardsAvailable:(_Bool)arg4 callToAction:(long long)arg5 cardSize:(long long)arg6;	// IMP=0x0010000000360863
- (void)displayedEngagementMessage:(id)arg1;	// IMP=0x001000000036076c
- (void)performedAction:(long long)arg1 onDiscoveryItem:(id)arg2;	// IMP=0x0010000000360723
- (void)performedAction:(long long)arg1 onEngagementMessage:(id)arg2;	// IMP=0x00100000003605c3

@end

