//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CLGeocoder, CLLocationManager, NSHashTable, NSMutableArray, NSMutableSet, NSString, PDMapsBrandAndMerchantUpdater, PKMerchantCategoryCodeMap, PKUsageNotificationServer;
@protocol OS_dispatch_source, PDPaymentTransactionProcessorDataSource;

@interface PDPaymentTransactionProcessor : NSObject
{
    struct os_unfair_lock_s _itemsLock;	// 8 = 0x8
    NSMutableSet *_locationUpdateItems;	// 16 = 0x10
    NSMutableSet *_backgroundLocationUpdateItems;	// 24 = 0x18
    NSMutableArray *_reverseGeocodeItems;	// 32 = 0x20
    NSMutableSet *_stationsUpdateItems;	// 40 = 0x28
    NSMutableArray *_merchantCleanupItems;	// 48 = 0x30
    CLLocationManager *_locationManager;	// 56 = 0x38
    CLLocationManager *_backgroundMerchantLocationManager;	// 64 = 0x40
    CLGeocoder *_geocoder;	// 72 = 0x48
    NSObject<OS_dispatch_source> *_locationUpdateTimeoutTimer;	// 80 = 0x50
    NSObject<OS_dispatch_source> *_backgroundLocationUpdateTimer;	// 88 = 0x58
    _Bool _active;	// 96 = 0x60
    _Bool _processingMerchantCleanupItems;	// 97 = 0x61
    PKMerchantCategoryCodeMap *_categoryCodeMap;	// 104 = 0x68
    PDMapsBrandAndMerchantUpdater *_mapsBrandAndMerchantUpdater;	// 112 = 0x70
    struct os_unfair_lock_s _observersLock;	// 120 = 0x78
    NSHashTable *_observers;	// 128 = 0x80
    id <PDPaymentTransactionProcessorDataSource> _dataSource;	// 136 = 0x88
    PKUsageNotificationServer *_usageNotificationServer;	// 144 = 0x90
}

- (void).cxx_destruct;	// IMP=0x000000000048a213
@property(nonatomic) __weak PKUsageNotificationServer *usageNotificationServer; // @synthesize usageNotificationServer=_usageNotificationServer;
@property(nonatomic) __weak id <PDPaymentTransactionProcessorDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
- (id)_pendingMerchantCleanupItemForTransaction:(id)arg1;	// IMP=0x0010000000489f1c
- (id)_pendingStationsUpdateItemForTransaction:(id)arg1;	// IMP=0x0010000000489c88
- (id)_pendingLocationUpdateItemForTransaction:(id)arg1;	// IMP=0x00100000004897fb
- (void)_processForLocalMCCLookup:(id)arg1;	// IMP=0x0010000000489728
- (void)_beginMerchantCleanupIfPossible;	// IMP=0x0010000000488d19
- (_Bool)_canUpdateMapsDataForTransaction:(id)arg1;	// IMP=0x0010000000488c90
- (void)_processItemForMerchantCleanup:(id)arg1 clearingAttempt:(_Bool)arg2;	// IMP=0x0010000000488916
- (void)_processPaymentTransactionForMapsData:(id)arg1 forTransactionSourceIdentifier:(id)arg2;	// IMP=0x00100000004887f2
- (void)_processPaymentTransactionForMerchantCleanup:(id)arg1 forTransactionSourceIdentifier:(id)arg2 clearingAttempt:(_Bool)arg3;	// IMP=0x001000000048871b
- (void)_processItemForStationsCleanup:(id)arg1;	// IMP=0x001000000048758a
- (void)_processPaymentTransactionForStationsUpdate:(id)arg1 forTransactionSourceIdentifier:(id)arg2;	// IMP=0x00100000004874b3
- (id)_pendingReverseGeocodeUpdateItemForTransaction:(id)arg1;	// IMP=0x001000000048721f
- (void)_beginReverseGeocodingIfPossible;	// IMP=0x001000000048689e
- (void)_stopUpdatingLocationIfPossible;	// IMP=0x0010000000486719
- (void)_startUpdatingBackgroundLocationIfPossible;	// IMP=0x001000000048654a
- (void)_startUpdatingLocationIfPossible;	// IMP=0x001000000048637b
- (void)_abortUpdatingLocationForAllBackgroundLocationUpdateItems;	// IMP=0x00100000004862c4
- (void)_abortUpdatingLocationForAllLocationUpdateItems;	// IMP=0x001000000048620d
- (void)_abortUpdatingLocationForLocationUpdateItem:(id)arg1;	// IMP=0x001000000048610c
- (void)_reportTransactionWithFinalLocation:(id)arg1;	// IMP=0x0010000000485bef
- (void)_updateLocation:(id)arg1 forLocationUpdateItem:(id)arg2 andMarkAsProcessed:(_Bool)arg3;	// IMP=0x0010000000485637
- (void)_continueUpdatingLocationForTransactionUpdateItem:(id)arg1;	// IMP=0x001000000048559d
- (void)_processPaymentTransactionForLocationUpdate:(id)arg1 forTransactionSourceIdentifier:(id)arg2;	// IMP=0x00100000004850a0
- (void)_updateActiveState;	// IMP=0x0010000000484e24
- (void)_processPaymentTransaction:(id)arg1 forTransactionSourceIdentifier:(id)arg2;	// IMP=0x0010000000484702
- (void)_beginProcessingPaymentTransaction:(id)arg1 forTransactionSourceIdentifier:(id)arg2 skipLocation:(_Bool)arg3;	// IMP=0x001000000048419e
- (void)_markTransactionAsFullyProcessedAndNotifyDelegate:(id)arg1 forTransactionSourceIdentifier:(id)arg2;	// IMP=0x0010000000484019
- (void)_processPaymentTransactionForDemoMode:(id)arg1 forTransactionSourceIdentifier:(id)arg2;	// IMP=0x0010000000483bd4
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x0010000000483a3d
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;	// IMP=0x00100000004835fe
- (void)_accessObserversWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000483497
- (void)unregisterObserver:(id)arg1;	// IMP=0x001000000048343b
- (void)registerObserver:(id)arg1;	// IMP=0x00100000004833df
- (void)processPaymentTransactionConfigurations:(id)arg1;	// IMP=0x0010000000483064
- (void)processPaymentTransaction:(id)arg1 forTransactionSourceIdentifier:(id)arg2;	// IMP=0x0010000000482fd9
- (id)initWithQueue:(id)arg1 mapsBrandAndMerchantUpdater:(id)arg2;	// IMP=0x0010000000482d63
- (id)initWithMapsBrandAndMerchantUpdater:(id)arg1;	// IMP=0x0010000000482d01

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

