//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSURL, PDApplicationMessageManager, PDAssertionManager, PDDatabaseManager, PDUserNotificationCenter, PDUserNotificationIconStore, PKPaymentWebService;
@protocol OS_dispatch_queue, OS_dispatch_semaphore, PDUserNotificationManagerDelegate, PKApplicationMessageSink;

@interface PDUserNotificationManager : NSObject
{
    NSURL *_archiveFileURL;	// 8 = 0x8
    PDDatabaseManager *_databaseManager;	// 16 = 0x10
    PDAssertionManager *_assertionManager;	// 24 = 0x18
    PDUserNotificationCenter *_notificationCenter;	// 32 = 0x20
    PDUserNotificationIconStore *_iconStore;	// 40 = 0x28
    PKPaymentWebService *_paymentWebService;	// 48 = 0x30
    PDApplicationMessageManager *_applicationMessageManager;	// 56 = 0x38
    id <PKApplicationMessageSink> _applicationMessageSink;	// 64 = 0x40
    id <PDUserNotificationManagerDelegate> _delegate;	// 72 = 0x48
    NSObject<OS_dispatch_semaphore> *_archiveSemaphore;	// 80 = 0x50
    NSObject<OS_dispatch_queue> *_userNotificationManagerQueue;	// 88 = 0x58
    _Bool _isDeviceAssessmentEducationVisible;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x002000000029bf53
- (long long)_badgeCountForPayLaterWithAccount:(id)arg1;	// IMP=0x001000000029ba39
- (long long)_badgeCount;	// IMP=0x001000000029b148
- (_Bool)_notificationRequirementsAreSatisfied:(id)arg1;	// IMP=0x001000000029ae78
- (void)_archiveUserNotifications;	// IMP=0x001000000029ac40
- (void)_removeScheduledActivitiesForPassUniqueIdentifier:(id)arg1 ofType:(unsigned long long)arg2;	// IMP=0x001000000029aa19
- (void)_removeScheduledActivitiesOfType:(unsigned long long)arg1;	// IMP=0x001000000029a890
- (void)_removeScheduledActivitiesForPassUniqueIdentifier:(id)arg1;	// IMP=0x001000000029a69f
- (void)updateNotificationApplicationMessageWithNotification:(id)arg1;	// IMP=0x001000000029a5d3
- (_Bool)hasNotificationApplicationMessageWithIdentifier:(id)arg1;	// IMP=0x001000000029a5b4
- (void)removeNotificationApplicationMessageWithIdentifier:(id)arg1;	// IMP=0x001000000029a597
- (void)updateDeviceAssessmentEducationVisibility;	// IMP=0x001000000029a4d9
- (id)scheduledNotificationDescriptions;	// IMP=0x0010000000299eed
- (void)alertNotificationsEnabled:(CDUnknownBlockType)arg1;	// IMP=0x0010000000299ed4
- (void)updateWalletBadgeCount;	// IMP=0x0010000000299dc2
- (void)userNotificationWithIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000299bfb
- (void)userNotificationsForPassUniqueIdentifier:(id)arg1 ofType:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000299b03
- (void)userNotificationsOfType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000299a43
- (id)scheduledNotificationActivitiesForPassUniqueIdentifier:(id)arg1 ofType:(unsigned long long)arg2;	// IMP=0x00100000002997cc
- (void)removeNotificationAssetsForPassWithUniqueIdentifier:(id)arg1;	// IMP=0x00100000002997b6
- (void)removeAllUserNotifications;	// IMP=0x001000000029962b
- (void)removeUserNotificationsForPassUniqueIdentifier:(id)arg1;	// IMP=0x001000000029955c
- (void)removeUserNotificationsForPassUniqueIdentifier:(id)arg1 ofType:(unsigned long long)arg2;	// IMP=0x001000000029947a
- (void)removeUserNotificationsOfType:(unsigned long long)arg1;	// IMP=0x00100000002993ec
- (void)removeUserNotification:(id)arg1;	// IMP=0x00100000002992e7
- (void)removeUserNotificationWithIdentifier:(id)arg1;	// IMP=0x001000000029920c
- (void)updateUserNotificationsForUpdatedExpressPassesInformation:(id)arg1;	// IMP=0x00100000002991f6
- (void)insertUserNotification:(id)arg1;	// IMP=0x0010000000298f1a
- (void)userNotificationActionPerformed:(unsigned long long)arg1 applicationMessageContentIdentifier:(id)arg2;	// IMP=0x0010000000298e5e
- (void)requestNotificationAuthorizationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000298db5
- (void)requestNotificationAuthorizationIfNecessaryWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000298d0c
- (void)connect;	// IMP=0x0010000000298701
- (void)applicationMessageSink:(id)arg1 tappedMessageWithRegistration:(id)arg2;	// IMP=0x0010000000298685
- (void)applicationMessageSink:(id)arg1 removedMessageWithRegistration:(id)arg2;	// IMP=0x001000000029867f
- (id)applicationMessageSink:(id)arg1 createContentForMessageWithRegistration:(id)arg2;	// IMP=0x00100000002985f6
- (void)connectApplicationMessageSink:(id)arg1;	// IMP=0x00100000002985e5
- (void)assertionManager:(id)arg1 didInvalidateAssertion:(id)arg2;	// IMP=0x00100000002984e0
- (_Bool)allowAcquisitionOfAssertionOfType:(unsigned long long)arg1;	// IMP=0x00100000002984d8
- (_Bool)interestedInAssertionOfType:(unsigned long long)arg1;	// IMP=0x00100000002984cb
- (void)performScheduledActivityWithIdentifier:(id)arg1 activityCriteria:(id)arg2 activityContext:(id)arg3;	// IMP=0x00000000002983d5
- (void)performScheduledActivityWithIdentifier:(id)arg1 activityCriteria:(id)arg2;	// IMP=0x00100000002983c0
- (void)userNotificationCenter:(id)arg1 removedUserNotificationIdentifiers:(id)arg2;	// IMP=0x0010000000298267
- (void)userNotificationCenter:(id)arg1 insertedOrUpdatedUserNotification:(id)arg2;	// IMP=0x001000000029818b
- (_Bool)userNotificationCenterShouldSuppressUserNotifications:(id)arg1;	// IMP=0x001000000029813a
- (id)passWithUniqueIdentifier:(id)arg1;	// IMP=0x0010000000298124
- (void)dealloc;	// IMP=0x001000000029809f
- (id)initWithArchiveFileURL:(id)arg1 databaseManager:(id)arg2 assertionManager:(id)arg3 paymentWebService:(id)arg4 applicationMessageManager:(id)arg5 delegate:(id)arg6;	// IMP=0x0010000000297da1

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

