//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TapToRadarPrompt
{
}

+ (id)_propertySetters;	// IMP=0x00400000002c93d5
+ (id)_predicateForReason:(id)arg1;	// IMP=0x00100000002c93b2
+ (id)insertOrUpdateWithReason:(id)arg1 lastPromptDate:(id)arg2 inDatabase:(id)arg3;	// IMP=0x00100000002c8deb
+ (id)tapToRadarPromptWithReason:(id)arg1 inDatabase:(id)arg2;	// IMP=0x00100000002c8d5f
+ (id)databaseTable;	// IMP=0x00100000002c8d52
- (id)tapToRadarPrompt;	// IMP=0x00400000002c9245
- (void)updateWithLastPromptDate:(id)arg1;	// IMP=0x00100000002c90e4
- (id)initWithReason:(id)arg1 lastPromptDate:(id)arg2 inDatabase:(id)arg3;	// IMP=0x00100000002c8fd2

@end

