//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CloudBookmarkCKAssetValueTransformer
{
}

+ (_Bool)allowsReverseTransformation;	// IMP=0x0040000000074137
+ (Class)transformedValueClass;	// IMP=0x0010000000074126
- (id)reverseTransformedValue:(id)arg1;	// IMP=0x0040000000074206
- (id)transformedValue:(id)arg1;	// IMP=0x001000000007413f

@end

