//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class CalendarModel, EKCalendarDate, EKEvent, EKEventEditViewController, EKStructuredLocation, MISSING_TYPE, NSString, UINavigationController;
@protocol AddEventDelegate;

@interface AddEventViewController : UIViewController
{
    EKEventEditViewController *_eventEditViewController;	// 8 = 0x8
    _Bool _showEventWhenAdded;	// 16 = 0x10
    _Bool _allDay;	// 17 = 0x11
    CDUnknownBlockType _doneBlock;	// 24 = 0x18
    EKCalendarDate *_exactEventStartDate;	// 32 = 0x20
    NSString *_suggestionKey;	// 40 = 0x28
    MISSING_TYPE *_delegate;	// 48 = 0x30
    NSString *_eventCreationMethod;	// 56 = 0x38
    CalendarModel *_model;	// 64 = 0x40
    UINavigationController *_embeddedNavigationController;	// 72 = 0x48
    EKEvent *_event;	// 80 = 0x50
    EKCalendarDate *_eventStartDate;	// 88 = 0x58
    EKCalendarDate *_eventEndDate;	// 96 = 0x60
    NSString *_eventTitle;	// 104 = 0x68
    EKStructuredLocation *_eventLocation;	// 112 = 0x70
}

- (void).cxx_destruct;	// IMP=0x0020000000122c1f
@property(retain, nonatomic) EKStructuredLocation *eventLocation; // @synthesize eventLocation=_eventLocation;
@property(retain, nonatomic) NSString *eventTitle; // @synthesize eventTitle=_eventTitle;
@property(retain, nonatomic) EKCalendarDate *eventEndDate; // @synthesize eventEndDate=_eventEndDate;
@property(retain, nonatomic) EKCalendarDate *eventStartDate; // @synthesize eventStartDate=_eventStartDate;
@property(retain, nonatomic) EKEvent *event; // @synthesize event=_event;
@property(retain, nonatomic) UINavigationController *embeddedNavigationController; // @synthesize embeddedNavigationController=_embeddedNavigationController;
@property(retain, nonatomic) CalendarModel *model; // @synthesize model=_model;
@property(retain, nonatomic) NSString *eventCreationMethod; // @synthesize eventCreationMethod=_eventCreationMethod;
@property(nonatomic) __weak id <AddEventDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool allDay; // @synthesize allDay=_allDay;
@property(retain, nonatomic) NSString *suggestionKey; // @synthesize suggestionKey=_suggestionKey;
@property(retain, nonatomic) EKCalendarDate *exactEventStartDate; // @synthesize exactEventStartDate=_exactEventStartDate;
@property(copy, nonatomic) CDUnknownBlockType doneBlock; // @synthesize doneBlock=_doneBlock;
@property(nonatomic) _Bool showEventWhenAdded; // @synthesize showEventWhenAdded=_showEventWhenAdded;
- (void)cancelEditingWithDelegateNotification:(_Bool)arg1 forceCancel:(_Bool)arg2;	// IMP=0x0010000000122a01
- (void)didAttemptToDismiss;	// IMP=0x0010000000122982
- (_Bool)canDismiss;	// IMP=0x0010000000122962
- (void)attemptDisplayReviewPrompt;	// IMP=0x001000000012289a
- (id)pasteboardManagerForEventEditViewController:(id)arg1;	// IMP=0x001000000012287d
- (void)eventEditViewController:(id)arg1 didCompleteWithAction:(long long)arg2;	// IMP=0x0010000000122657
- (id)backgroundColor;	// IMP=0x001000000012260b
- (_Bool)prefersForcedModalShowViewController;	// IMP=0x0010000000122603
- (_Bool)isModalInPresentation;	// IMP=0x00100000001225ee
- (void)loadView;	// IMP=0x0010000000121f83
- (id)_eventEditViewControllerForTestingOnly;	// IMP=0x0010000000121f6e
- (void)viewWillLayoutSubviews;	// IMP=0x0010000000121ee8
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x0010000000121e16
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x0010000000121dd1
- (id)initWithModel:(id)arg1 eventTitle:(id)arg2 startDate:(id)arg3 endDate:(id)arg4 location:(id)arg5;	// IMP=0x0010000000121d03
- (id)initWithModel:(id)arg1 eventStartDate:(id)arg2;	// IMP=0x0010000000121c5d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

