//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UINavigationController.h>

@class MainViewController, NSOperationQueue, NSString;

@interface EnqueueableManagedNavigationController : UINavigationController
{
    _Bool _enqueuingDismissalsDisabled;	// 8 = 0x8
    MainViewController *_sourceViewController;	// 16 = 0x10
    NSOperationQueue *_showViewControllersWhenReadyQueue;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000a73d4
@property(retain, nonatomic) NSOperationQueue *showViewControllersWhenReadyQueue; // @synthesize showViewControllersWhenReadyQueue=_showViewControllersWhenReadyQueue;
@property(nonatomic) MainViewController *sourceViewController; // @synthesize sourceViewController=_sourceViewController;
- (id)EKUI_window;	// IMP=0x00100000000a72d7
- (void)setAllowsEnqueuedDismissal:(_Bool)arg1;	// IMP=0x00100000000a72c4
- (void)dismissViewControllerWithoutEnqueuingWithTransition:(int)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a7295
- (void)dismissViewControllerWithTransition:(int)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a7030
- (_Bool)_shouldEnqueueDismissals;	// IMP=0x00100000000a6f73
- (void)enqueueBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000a6c39
- (void)enqueueStackResetOperationDismissingPresentations:(_Bool)arg1 cancelOperations:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00100000000a6132
- (void)enqueueStackResetOperation;	// IMP=0x00100000000a6113
- (void)_doneButtonTapped;	// IMP=0x00100000000a6073
- (void)_addDoneButtonIfNeededToViewController:(id)arg1;	// IMP=0x00100000000a5f23
- (_Bool)_shouldDoExternalPresentationOfManagedNavigationController;	// IMP=0x00100000000a5e27
- (void)showViewController:(id)arg1 sender:(id)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000000a5490
- (Class)showViewControllerOperationClass;	// IMP=0x00100000000a547f
- (id)_popoverPresentationOperationInQueue;	// IMP=0x00100000000a52d4
- (void)sourceViewController:(id)arg1 notifiesReadinessForPresentation:(_Bool)arg2;	// IMP=0x00100000000a5297
- (void)cancelOutstandingOperations;	// IMP=0x00100000000a525a
- (_Bool)canBeDirectlyManaged;	// IMP=0x00100000000a5252
- (_Bool)canManagePresentationStyle;	// IMP=0x00100000000a524a
- (_Bool)wantsManagement;	// IMP=0x00100000000a5242
- (void)dealloc;	// IMP=0x00100000000a514a
- (id)init;	// IMP=0x00100000000a4f87

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

