//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class WeekViewController;

@interface PadWeekViewScrollTest
{
    WeekViewController *_controller;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000131d9d
@property(readonly, nonatomic) WeekViewController *controller; // @synthesize controller=_controller;
- (id)scrollView;	// IMP=0x0010000000131d6f
- (void)navigateToScrollView;	// IMP=0x0010000000131c75

@end

