//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC14amsengagementd10JSLocation : NSObject
{
}

- (id)init;	// IMP=0x00400000000b5b10
- (id)getAuthorizationStatus:(id)arg1;	// IMP=0x00100000000b5a70

@end

