//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface AppDefaultsManager : NSObject
{
}

+ (_Bool)_boolForKey:(struct __CFString *)arg1 applicationId:(struct __CFString *)arg2 ifMissing:(_Bool)arg3;	// IMP=0x00200000000536e1
+ (id)transporterConfiguration;	// IMP=0x00100000000536c1
+ (void)setTransporterConfiguration:(id)arg1;	// IMP=0x0010000000053694
+ (void)setExternalPurchaseSpringBoardAppDeleteAlertEnabled:(_Bool)arg1;	// IMP=0x0010000000053653
+ (_Bool)externalPurchaseSpringBoardAppDeleteAlertEnabled;	// IMP=0x001000000005362d
+ (_Bool)alwaysUseLegacyAPIForStoreKitProductsRequest;	// IMP=0x001000000005360d
+ (_Bool)allowPurchaseRequestData;	// IMP=0x00100000000535cc
+ (void)setOcelotApps:(id)arg1;	// IMP=0x001000000005359f
+ (id)ocelotApps;	// IMP=0x001000000005357f
+ (_Bool)marketingDemoModeEnabled;	// IMP=0x001000000005355f
+ (_Bool)keepTemporaryFiles;	// IMP=0x001000000005353f

@end

