//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;

@interface SQLiteMemoryEntity : NSObject
{
    long long _databaseID;	// 8 = 0x8
    NSMutableDictionary *_propertyValues;	// 16 = 0x10
    NSMutableDictionary *_externalPropertyValues;	// 24 = 0x18
}

+ (id)defaultProperties;	// IMP=0x002000000009ce79
+ (Class)databaseEntityClass;	// IMP=0x001000000009ce68
+ (id)queryOnConnection:(id)arg1 predicate:(id)arg2 orderingProperties:(id)arg3;	// IMP=0x001000000007b9e3
+ (id)queryOnConnection:(id)arg1 predicate:(id)arg2;	// IMP=0x001000000007b9ce
+ (id)anyOnConnection:(id)arg1 predicate:(id)arg2;	// IMP=0x001000000007b86c
- (void).cxx_destruct;	// IMP=0x001000000009d3f9
@property(readonly, copy, nonatomic) NSDictionary *externalPropertyValues; // @synthesize externalPropertyValues=_externalPropertyValues;
@property(readonly, copy, nonatomic) NSDictionary *propertyValues; // @synthesize propertyValues=_propertyValues;
@property(nonatomic) long long databaseID; // @synthesize databaseID=_databaseID;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000009d380
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000009d243
- (unsigned long long)hash;	// IMP=0x001000000009d22d
- (id)description;	// IMP=0x001000000009d1a7
- (id)valueForExternalProperty:(id)arg1;	// IMP=0x001000000009d191
- (id)valueForProperty:(id)arg1;	// IMP=0x001000000009d17b
- (void)setValues:(id *)arg1 forExternalProperties:(const id *)arg2 count:(long long)arg3;	// IMP=0x001000000009d0fe
- (void)setValue:(id)arg1 forExternalProperty:(id)arg2;	// IMP=0x001000000009d072
- (void)setValuesWithDictionary:(id)arg1;	// IMP=0x001000000009d05c
- (void)setValues:(id *)arg1 forProperties:(const id *)arg2 count:(long long)arg3;	// IMP=0x001000000009cfdf
- (void)setValue:(id)arg1 forProperty:(id)arg2;	// IMP=0x001000000009cf53
- (void)setExternalValuesWithDictionary:(id)arg1;	// IMP=0x001000000009cf3d
- (void)reloadFromDatabaseEntity:(id)arg1 properties:(id)arg2;	// IMP=0x001000000009ce86
- (id)initWithPropertyValues:(id)arg1;	// IMP=0x001000000009ce4a
- (id)initWithDatabaseEntity:(id)arg1 properties:(id)arg2;	// IMP=0x001000000009cda2
- (id)initWithDatabaseID:(long long)arg1 propertyValues:(id)arg2 externalPropertyValues:(id)arg3;	// IMP=0x001000000009cccc
- (id)init;	// IMP=0x001000000009ccae
- (id)dictValueForProperty:(id)arg1;	// IMP=0x001000000009d6b3
- (id)arrayValueForProperty:(id)arg1;	// IMP=0x001000000009d65c
- (id)urlValueForProperty:(id)arg1;	// IMP=0x001000000009d605
- (id)uuidValueForProperty:(id)arg1;	// IMP=0x001000000009d5ae
- (id)stringValueForProperty:(id)arg1;	// IMP=0x001000000009d557
- (id)numberValueForProperty:(id)arg1;	// IMP=0x001000000009d500
- (long long)integerValueForProperty:(id)arg1;	// IMP=0x001000000009d4bc
- (id)dateValueForProperty:(id)arg1;	// IMP=0x001000000009d465
- (_Bool)boolValueForProperty:(id)arg1;	// IMP=0x001000000009d421

@end

