//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface AKTTRController : NSObject
{
}

+ (id)generateRadarRequestFor:(unsigned long long)arg1;	// IMP=0x00200000000ae455
+ (id)sharedController;	// IMP=0x00100000000ada40
- (void)performSilentTTRFor:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00200000000ae4ec
- (void)requestTapToRadarWithTitle:(id)arg1 message:(id)arg2 componentName:(id)arg3 componentVersion:(id)arg4 componentID:(id)arg5 keywords:(id)arg6;	// IMP=0x00100000000adf34
- (void)requestTapToRadarWithTitle:(id)arg1 message:(id)arg2 keywords:(id)arg3;	// IMP=0x00100000000adf02
- (void)processPushMessage:(id)arg1;	// IMP=0x00100000000adb63
- (_Bool)shouldSuppressPushMessage:(id)arg1;	// IMP=0x00100000000adac4
- (id)init;	// IMP=0x00100000000ada95

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

