//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface _TtC9Reminders28TTRIAddShareesViewController
{
}

+ (id)composeLabel;	// IMP=0x0020000000035b40
+ (id)titleString;	// IMP=0x0010000000035b00
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000000035ff0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000035f40
- (id)initWithAllowsPhoneNumbers:(_Bool)arg1;	// IMP=0x0010000000035f00
- (void)viewDidLoad;	// IMP=0x0010000000035ed0

@end

