//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PPTNavigation_SmartList_Flagged
{
}

- (void).cxx_destruct;	// IMP=0x00400000001fc930
- (id)init;	// IMP=0x00100000001fcbb0

@end

