//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APXPCConnection, NSString, Protocol;

@interface PCSupportReceiver : NSObject
{
    APXPCConnection *_connection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000001060dd
@property(retain, nonatomic) APXPCConnection *connection; // @synthesize connection=_connection;
- (void)finishedWithRequests;	// IMP=0x00100000001060ae
- (void)extendCollectionClassesForExportedInterface:(id)arg1;	// IMP=0x0010000000105ff3
- (id)requiredEntitlements;	// IMP=0x0010000000105fd3
- (void)connectionInvalidated;	// IMP=0x0010000000105f52
- (void)connectionInterrupted;	// IMP=0x0010000000105ed1
@property(readonly) Protocol *exportedInterface;
@property(readonly) id exportedObject;
- (void)fetchConfigurationForClass:(Class)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000105e24
- (void)fetchGenderAndAgeGroupData:(CDUnknownBlockType)arg1;	// IMP=0x0010000000105dea
- (void)policiesToEnforce:(CDUnknownBlockType)arg1;	// IMP=0x0010000000105d87
- (void)policiesForContainerType:(id)arg1 adType:(id)arg2 adFormatType:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000105d0c
- (void)addClientToSegments:(id)arg1 replaceExisting:(_Bool)arg2 privateSegment:(_Bool)arg3;	// IMP=0x0010000000105a9b
- (id)initWithConnection:(id)arg1;	// IMP=0x0010000000105a30

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

