//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol Transmitter;

@interface APDUMapping : NSObject
{
    NSObject<Transmitter> *_transmitter;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000003046
- (id)transmit:(id)arg1;	// IMP=0x0010000000002cf3
- (id)initWithTransmitter:(id)arg1;	// IMP=0x0010000000002c8f

@end

