//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NEKCalendarID, NSData, NSDictionary, NSMutableDictionary, NSString;

@interface NEKICSWrapper : NSObject
{
    NSData *_zICSData;	// 8 = 0x8
    NSData *_rICSData;	// 16 = 0x10
    NSString *_title;	// 24 = 0x18
    _Bool _taskCompleted;	// 32 = 0x20
    _Bool _isReminderWithLocation;	// 33 = 0x21
    NSData *_lzfseICSData;	// 40 = 0x28
    NEKCalendarID *_calendarIdentifier;	// 48 = 0x30
    NSString *_oldCalendarIdentifier;	// 56 = 0x38
    NSString *_oldIdentifier;	// 64 = 0x40
    NSString *_nuevoIdentifier;	// 72 = 0x48
    long long _calendarItemCount;	// 80 = 0x50
    double _taskCompletionDate;	// 88 = 0x58
    long long _displayOrder;	// 96 = 0x60
    NSDictionary *_startDateMap;	// 104 = 0x68
    NSMutableDictionary *_properties;	// 112 = 0x70
    NSString *_syncId;	// 120 = 0x78
}

+ (void)setPropertiesForWrapper:(id)arg1 withReminders:(id)arg2 oldListIdentifier:(id)arg3 sendAllProperties:(_Bool)arg4 store:(id)arg5 list:(id)arg6;	// IMP=0x00100000000063a2
+ (void)setMinimalPropertiesForReminder:(id)arg1 identifier:(id)arg2 wrapper:(id)arg3;	// IMP=0x0010000000006254
+ (void)setAllPropertiesForReminder:(id)arg1 identifier:(id)arg2 wrapper:(id)arg3 store:(id)arg4 list:(id)arg5 oldListIdentifier:(id)arg6;	// IMP=0x00100000000060f6
+ (id)wrapperForReminder:(id)arg1 oldListIdentifier:(id)arg2 store:(id)arg3;	// IMP=0x0010000000005a69
+ (void)setPropertiesForWrapper:(id)arg1 withCalendarItems:(id)arg2 needsInvite:(id)arg3 sendAllProperties:(_Bool)arg4 eventStore:(id)arg5 calendar:(id)arg6 originalEvent:(id)arg7;	// IMP=0x0010000000025ce6
+ (void)setMinimalPropertiesForItem:(id)arg1 identifier:(id)arg2 wrapper:(id)arg3;	// IMP=0x0010000000025a68
+ (void)setAllPropertiesForItem:(id)arg1 identifier:(id)arg2 wrapper:(id)arg3 needsInvite:(id)arg4 eventStore:(id)arg5 calendar:(id)arg6;	// IMP=0x0010000000025536
+ (id)wrapperForCalendarItem:(id)arg1 needsInvite:(id)arg2 eventStore:(id)arg3;	// IMP=0x00100000000248d1
- (void).cxx_destruct;	// IMP=0x0020000000004318
@property(copy, nonatomic) NSString *syncId; // @synthesize syncId=_syncId;
@property(retain, nonatomic) NSMutableDictionary *properties; // @synthesize properties=_properties;
@property(retain, nonatomic) NSDictionary *startDateMap; // @synthesize startDateMap=_startDateMap;
@property(nonatomic) _Bool isReminderWithLocation; // @synthesize isReminderWithLocation=_isReminderWithLocation;
@property(nonatomic) long long displayOrder; // @synthesize displayOrder=_displayOrder;
@property(nonatomic) double taskCompletionDate; // @synthesize taskCompletionDate=_taskCompletionDate;
@property(nonatomic, getter=isTaskCompleted) _Bool taskCompleted; // @synthesize taskCompleted=_taskCompleted;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long calendarItemCount; // @synthesize calendarItemCount=_calendarItemCount;
@property(retain, nonatomic) NSString *nuevoIdentifier; // @synthesize nuevoIdentifier=_nuevoIdentifier;
@property(retain, nonatomic) NSString *oldIdentifier; // @synthesize oldIdentifier=_oldIdentifier;
@property(retain, nonatomic) NSString *oldCalendarIdentifier; // @synthesize oldCalendarIdentifier=_oldCalendarIdentifier;
@property(retain, nonatomic) NEKCalendarID *calendarIdentifier; // @synthesize calendarIdentifier=_calendarIdentifier;
@property(retain, nonatomic) NSData *lzfseICSData; // @synthesize lzfseICSData=_lzfseICSData;
@property(readonly, copy) NSString *description;
- (long long)objectTypeForCalendarItemWithIdentifier:(id)arg1;	// IMP=0x0010000000003f49
- (unsigned long long)entityTypeForCalendarItemWithIdentifier:(id)arg1;	// IMP=0x0010000000003eee
- (void)enumerateCalendarItemIdentifiersUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000003db7
- (id)startDateForIdentifier:(id)arg1;	// IMP=0x0010000000003d67
- (void)setStartDate:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003cef
- (id)externalIDForIdentifier:(id)arg1;	// IMP=0x0010000000003c9f
- (void)setExternalID:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003c27
- (_Bool)attendeeStatusFlagForIdentifier:(id)arg1;	// IMP=0x0010000000003be3
- (void)setAttendeeStatusFlag:(_Bool)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003b94
- (long long)attendeeStatusForIdentifier:(id)arg1;	// IMP=0x0010000000003b50
- (void)setAttendeeStatus:(long long)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003b01
- (id)locationPredictionStateForIdentifier:(id)arg1;	// IMP=0x0010000000003a91
- (void)setLocationPredictionState:(long long)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003a42
- (id)properInvitationStatusForIdentifier:(id)arg1;	// IMP=0x00100000000039bc
- (void)setProperInvitationStatus:(unsigned long long)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003911
- (id)invitationStatusForIdentifier:(id)arg1;	// IMP=0x00100000000038a1
- (void)setInvitationStatus:(unsigned long long)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003852
- (id)selfOrganizerUUIDForIdentifier:(id)arg1;	// IMP=0x0010000000003802
- (void)setSelfOrganizerUUID:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003771
- (id)selfOrganizerEmailForIdentifier:(id)arg1;	// IMP=0x0010000000003721
- (void)setSelfOrganizerEmail:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003690
- (id)selfAttendeeUUIDForIdentifier:(id)arg1;	// IMP=0x0010000000003640
- (void)setSelfAttendeeUUID:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x00100000000035af
- (id)selfAttendeeEmailForIdentifier:(id)arg1;	// IMP=0x001000000000355f
- (void)setSelfAttendeeEmail:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x001000000000345e
- (_Bool)attendeeCommentForIdentifier:(id)arg1;	// IMP=0x001000000000341a
- (void)setAttendeeComment:(_Bool)arg1 forIdentifier:(id)arg2;	// IMP=0x00100000000033cb
- (_Bool)locationChangedForIdentifier:(id)arg1;	// IMP=0x0010000000003387
- (void)setLocationChanged:(_Bool)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003338
- (_Bool)titleChangedForIdentifier:(id)arg1;	// IMP=0x00100000000032f4
- (void)setTitleChanged:(_Bool)arg1 forIdentifier:(id)arg2;	// IMP=0x00100000000032a5
- (_Bool)timeChangedForIdentifier:(id)arg1;	// IMP=0x0010000000003261
- (void)setTimeChanged:(_Bool)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000003212
- (_Bool)dateChangedForIdentifier:(id)arg1;	// IMP=0x00100000000031ce
- (void)setDateChanged:(_Bool)arg1 forIdentifier:(id)arg2;	// IMP=0x001000000000317f
- (void)setMetadata:(id)arg1 forCalendarItemIdentifier:(id)arg2;	// IMP=0x0010000000002f02
- (_Bool)hasPropertiesForIdentifier:(id)arg1;	// IMP=0x0010000000002ecb
- (id)settablePropertiesForCalendarItemIdentifier:(id)arg1;	// IMP=0x0010000000002e4d
- (id)propertiesForCalendarItemIdentifier:(id)arg1;	// IMP=0x0010000000002e37
@property(readonly, nonatomic) long long changeType;
@property(readonly, nonatomic) NSString *sequencer;
@property(readonly, nonatomic) NSString *objectIdentifier;
@property(retain, nonatomic) NSData *ICSData;
- (id)init;	// IMP=0x0010000000002b7d
- (id)ICSWrapperMetadata;	// IMP=0x0010000000002b2d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

