//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface TIKeyboardInputManagerServer : NSObject
{
    MISSING_TYPE *_listener;	// 8 = 0x8
}

+ (id)sharedKeyboardInputManagerServer;	// IMP=0x0020000000007b05
- (void).cxx_destruct;	// IMP=0x002000000000868b
- (void)prepareForActivity;	// IMP=0x00100000000085c0
- (void)prepareForInactivity;	// IMP=0x00100000000084b8
- (void)handleMemoryPressureLevel:(unsigned long long)arg1 excessMemoryInBytes:(unsigned long long)arg2;	// IMP=0x0010000000008400
- (void)keyboardActivityDidTransition:(id)arg1;	// IMP=0x0010000000008395
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x001000000000800a
- (void)reduceCacheToSize:(unsigned long long)arg1;	// IMP=0x0010000000007f1c
- (void)releaseAllInputManagers:(_Bool)arg1;	// IMP=0x0010000000007ec9
- (void)appleKeyboardsSettingsChanged:(id)arg1;	// IMP=0x0010000000007e24
- (id)init;	// IMP=0x0010000000007c57
- (void)dealloc;	// IMP=0x0010000000007b8a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

