//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class TRIClient;

@interface SRAssetsUtilities : NSObject
{
    TRIClient *_client;	// 8 = 0x8
}

+ (void)_runAssetCheckWithTask:(id)arg1;	// IMP=0x0040000000008deb
+ (void)_scheduleAssetCheckWithEarliestBeginDate:(id)arg1;	// IMP=0x0010000000008c5a
+ (void)setupBackgroundAssetCheck;	// IMP=0x0010000000008b6b
- (void).cxx_destruct;	// IMP=0x002000000000913f
- (unsigned long long)_mockSiriAssetState;	// IMP=0x0010000000008ad6
- (id)_beginDownloadNamespaces:(id)arg1;	// IMP=0x0010000000008a47
- (_Bool)_deviceSupportsUOD;	// IMP=0x0010000000008a07
- (id)_requiredNamespaces;	// IMP=0x0010000000008813
- (_Bool)_supportsCurrentLocale;	// IMP=0x00100000000084c0
- (void)checkAssetsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000008249
- (void)dealloc;	// IMP=0x0010000000008207
- (id)init;	// IMP=0x001000000000819c

@end

