//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class AFAnalyticsTurnBasedInstrumentationContext, NSString, SRCarPlayHeaderButton, SRStarkCancelButton, SRUIFCachedPreferences, SiriUICachedUserNotificationsSettings, UIFocusContainerGuide;
@protocol SRStarkGatekeeperHeaderViewDelegate, UIFocusItem;

@interface SRStarkGatekeeperHeaderView : UIView
{
    id <UIFocusItem> userFocusedItem;	// 8 = 0x8
    AFAnalyticsTurnBasedInstrumentationContext *_currentTurnContext;	// 16 = 0x10
    id <SRStarkGatekeeperHeaderViewDelegate> _delegate;	// 24 = 0x18
    UIFocusContainerGuide *_gatekeeperHeaderViewFocusContainerGuide;	// 32 = 0x20
    NSString *_appBundleIdentifier;	// 40 = 0x28
    SRStarkCancelButton *_cancelButton;	// 48 = 0x30
    SRCarPlayHeaderButton *_trailingButton;	// 56 = 0x38
    SiriUICachedUserNotificationsSettings *_cachedUserNotificationsSettings;	// 64 = 0x40
}

+ (Class)_carPlayHeaderButtonClassForHeaderButtonType:(unsigned long long)arg1;	// IMP=0x0020000000020c2a
+ (unsigned long long)_carPlayHeaderButtonTypeForDirectActionEvent:(long long)arg1;	// IMP=0x0010000000020c0e
+ (unsigned long long)_carPlayHeaderButtonTypeForAceObject:(id)arg1;	// IMP=0x0010000000020a27
+ (unsigned long long)_gatekeeperTypeForBundleIdentifier:(id)arg1;	// IMP=0x001000000001f73f
+ (id)gatekeeperForAceObject:(id)arg1 currentTurnContext:(id)arg2;	// IMP=0x001000000001eaa4
+ (id)gatekeeperForRequestOptions:(id)arg1 currentTurnContext:(id)arg2;	// IMP=0x001000000001e960
- (void).cxx_destruct;	// IMP=0x00200000000211e0
@property(readonly, nonatomic) SiriUICachedUserNotificationsSettings *cachedUserNotificationsSettings; // @synthesize cachedUserNotificationsSettings=_cachedUserNotificationsSettings;
@property(readonly, nonatomic) SRCarPlayHeaderButton *trailingButton; // @synthesize trailingButton=_trailingButton;
@property(readonly, nonatomic) SRStarkCancelButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(readonly, copy, nonatomic) NSString *appBundleIdentifier; // @synthesize appBundleIdentifier=_appBundleIdentifier;
@property(retain, nonatomic) UIFocusContainerGuide *gatekeeperHeaderViewFocusContainerGuide; // @synthesize gatekeeperHeaderViewFocusContainerGuide=_gatekeeperHeaderViewFocusContainerGuide;
@property(nonatomic) __weak id <SRStarkGatekeeperHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic, getter=_currentTurnContext, setter=_setCurrentTurnContext:) AFAnalyticsTurnBasedInstrumentationContext *currentTurnContext; // @synthesize currentTurnContext=_currentTurnContext;
@property(retain, nonatomic) id <UIFocusItem> userFocusedItem; // @synthesize userFocusedItem;
- (id)accessibilityIdentifier;	// IMP=0x00100000000210ec
- (void)_updateStateAndVisibilityForAnnounceHeaderButton:(id)arg1 announceEnabled:(_Bool)arg2 bannersVisibleInCarPlay:(_Bool)arg3 announceCarPlaySetting:(long long)arg4 temporarilyDisabled:(_Bool)arg5;	// IMP=0x0010000000020e7b
- (void)_updateStateAndVisibilityForAnnounceHeaderButton:(id)arg1 forAppBundleId:(id)arg2 fromCachedPreferences:(id)arg3 cachedUserNotificationsSettings:(id)arg4;	// IMP=0x0010000000020d37
- (void)_announceButtonTapped:(id)arg1;	// IMP=0x0010000000020c58
- (id)_trailingButtonForCarPlayHeaderButtonType:(unsigned long long)arg1;	// IMP=0x00100000000207b2
- (void)_updateTrailingButton:(id)arg1;	// IMP=0x001000000002071e
- (void)_updateTrailingButtonForCarPlayHeaderButtonType:(unsigned long long)arg1;	// IMP=0x00100000000206d2
- (void)_updateTrailingButtonForDirectActionEvent:(long long)arg1;	// IMP=0x001000000002061b
- (void)_updateTrailingButtonForAceObject:(id)arg1;	// IMP=0x001000000002054f
- (void)_updateAppBundleIdentifier:(id)arg1;	// IMP=0x001000000002036d
- (void)cachedSettings:(id)arg1 didChangeForAppBundleId:(id)arg2;	// IMP=0x001000000002011a
- (void)cachedPreferences:(id)arg1 announceNotificationsInCarPlayTemporarilyDisabledChanged:(_Bool)arg2;	// IMP=0x001000000001febc
- (_Bool)viewContainsFocusItem:(id)arg1;	// IMP=0x001000000001fdf0
- (id)updatedFocusItemForCurrentFocusItem:(id)arg1;	// IMP=0x001000000001fcc5
- (id)preferredFocusEnvironments;	// IMP=0x001000000001fbf0
- (void)layoutSubviews;	// IMP=0x001000000001f7e9
- (void)_logGatekeeperDismissedManually;	// IMP=0x001000000001f609
- (void)logGatekeeperAppeared;	// IMP=0x001000000001f4d3
- (void)_dismissalButtonTapped:(id)arg1;	// IMP=0x001000000001f21b
@property(readonly, nonatomic) SRUIFCachedPreferences *cachedPreferences;
- (id)initWithAceObject:(id)arg1 currentTurnContext:(id)arg2;	// IMP=0x001000000001f165
- (id)initWithRequestOptions:(id)arg1 currentTurnContext:(id)arg2;	// IMP=0x001000000001f0ba
- (id)_initWithAppBundleIdentifier:(id)arg1 directActionEvent:(long long)arg2 aceObject:(id)arg3 currentTurnContext:(id)arg4;	// IMP=0x001000000001ee43
- (void)updateForRequestOptions:(id)arg1 currentTurnContext:(id)arg2;	// IMP=0x001000000001ed9e
- (void)updateForAceObject:(id)arg1 currentTurnContext:(id)arg2;	// IMP=0x001000000001ed02

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

