//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ICQRemotePresentationManager, INAccountEventPushHandler, INDelayedOfferFailsafeActivity, NSDictionary;

@interface INDaemon_iOS
{
    NSDictionary *_accountPushNotificationHandlersByEventType;	// 8 = 0x8
    INAccountEventPushHandler *_accountDefaultEventPushNotificationHandler;	// 16 = 0x10
    CDUnknownBlockType _freshmintCompletion;	// 24 = 0x18
    ICQRemotePresentationManager *_presentationManager;	// 32 = 0x20
    INDelayedOfferFailsafeActivity *_delayedOfferFailsafeActivity;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000000183f0
@property(retain, nonatomic) INDelayedOfferFailsafeActivity *delayedOfferFailsafeActivity; // @synthesize delayedOfferFailsafeActivity=_delayedOfferFailsafeActivity;
- (id);	// IMP=0x00100000000183cb
- (void)calculateExtraQuotaNeededToSyncForAccountWithID:(id)arg1 isAccountFull:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000182de
- (void)stopDelayedOfferFailsafeActivityWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000018265
- (void)startDelayedOfferFailsafeActivityWithDelaySecs:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000181e7
- (_Bool)_unsafe_isLegacyDeviceStorageLevelNotificationEnabled;	// IMP=0x001000000001819c
- (void)_unsafe_handleSimulateVFSNotFullEvent;	// IMP=0x00100000000180e3
- (void)_unsafe_handleSimulateVFSAlmostFullEvent;	// IMP=0x0010000000018027
- (void)_unsafe_handleVFSRiseAboveDesiredDisk;	// IMP=0x0010000000017f4d
- (void)_unsafe_handleVFSRiseAboveLowDisk;	// IMP=0x0010000000017e87
- (void)_unsafe_handleVFSFallBelowNearLowDisk;	// IMP=0x0010000000017dea
- (void)_unsafe_handleVFSFallBelowLowDisk;	// IMP=0x0010000000017d63
- (void)_unsafe_handleVFSFallBelowVeryLowDisk;	// IMP=0x0010000000017c9d
- (void)_unsafe_handlePhotosOptimizeStateChangedEvent;	// IMP=0x0010000000017c19
- (void)_unsafe_handlePhotosiCPLStateChangedEvent;	// IMP=0x0010000000017b95
- (void)renewCredentialsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000017ab3
- (void)commonHeadersForRequest:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001793a
- (void)remoteFreshmintFlowCompletedWithSuccess:(_Bool)arg1 error:(id)arg2;	// IMP=0x001000000001782a
- (void)presentHiddenFreshmintWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000174bc
- (void)notifyDeviceStorageLevel:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000017376
- (void)iCloudServerOfferForAccountWithID:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000017101
- (void)handleICloudQuotaPush:(id)arg1;	// IMP=0x001000000001700e
- (id)pushTopics;	// IMP=0x0010000000016f3b
- (id)accountPushNotificationHandlerForEventType:(id)arg1;	// IMP=0x0010000000016e9d
- (void)_loadPushNotificationHandlers;	// IMP=0x0010000000016d61
- (void)_handleDeviceDidPairEvent;	// IMP=0x0010000000016981
- (void)_handleDeviceNameChangeEvent;	// IMP=0x00100000000165a1
- (void)_configureXPCEventStreamHandler;	// IMP=0x0010000000015eb0
- (void)start;	// IMP=0x0010000000015e24
- (id)init;	// IMP=0x0010000000015da4

@end

