//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppleAccount/AARequest.h>

@class ACAccount;

@interface INStorageAppsRequest : AARequest
{
    ACAccount *_account;	// 8 = 0x8
}

+ (Class)responseClass;	// IMP=0x0040000000008d84
- (void).cxx_destruct;	// IMP=0x002000000000901a
- (id)urlRequest;	// IMP=0x0010000000008f93
- (id)init;	// IMP=0x0010000000008f68
- (id)urlString;	// IMP=0x0010000000008e03
- (id)initWithAccount:(id)arg1;	// IMP=0x0010000000008d95

@end

