//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSIndexPath, TransitDirectionsStepView;

@interface _TransitDirectionsListViewInfo : NSObject
{
    TransitDirectionsStepView *_stepView;	// 8 = 0x8
    NSIndexPath *_indexPath;	// 16 = 0x10
}

+ (id)infoWithStepView:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0040000000423284
- (void).cxx_destruct;	// IMP=0x0020000000423569
@property(readonly, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(readonly, nonatomic) TransitDirectionsStepView *stepView; // @synthesize stepView=_stepView;
- (id)description;	// IMP=0x0010000000423417
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000423345
- (unsigned long long)hash;	// IMP=0x0010000000423301

@end

