//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, NSAttributedString, NSString;

@interface _TtC4Maps14EmptyStateView : UIView
{
    MISSING_TYPE *titleLabel;	// 8 = 0x8
    MISSING_TYPE *subtitleLabel;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00400000000dab20
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000000daa20
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000000da930
@property(nonatomic, retain) NSAttributedString *attributedSubtitle;
@property(nonatomic, copy) NSString *subtitle;
@property(nonatomic, copy) NSString *title;

@end

