//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UILabel;

@interface CarDoneButton
{
    UILabel *_titleLabel;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000005a0ab0
- (_Bool)needsContinuousRoundedCorners;	// IMP=0x00100000005a0aa8
- (void)setTintColor:(id)arg1;	// IMP=0x00100000005a0a32
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000005a051f

@end

