//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CarPlayUIServices/CRSUIWindow.h>

@class NSHashTable, NSString;

@interface CarDisplayWindow : CRSUIWindow
{
    NSHashTable *_eventTaps;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000b66a26
- (void)notificationLayoutGuideDidChange;	// IMP=0x0010000000b6695c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0010000000b667de
- (void)registerEventTap:(id)arg1;	// IMP=0x0010000000b66764
- (void)sendEvent:(id)arg1;	// IMP=0x0010000000b66598
- (void)setRootViewController:(id)arg1;	// IMP=0x0010000000b664aa
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000b663d9

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

