//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CarInstrumentClusterChromeConfiguration, NSString, UITapGestureRecognizer;

@interface CarMapWidgetChromeViewController
{
    UITapGestureRecognizer *_tapGesture;	// 48 = 0x30
    CarInstrumentClusterChromeConfiguration *_chromeConfiguration;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000a87a8d
@property(retain, nonatomic) CarInstrumentClusterChromeConfiguration *chromeConfiguration; // @synthesize chromeConfiguration=_chromeConfiguration;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;	// IMP=0x0010000000a87a54
- (void)_tappedMapWidget:(id)arg1;	// IMP=0x0010000000a87999
- (void)windowWantsToZoomInDirection:(long long)arg1;	// IMP=0x0010000000a87887
- (void)sceneConfigurationDidChange:(id)arg1;	// IMP=0x0010000000a87538
- (void)configureAccessoriesOverlay:(id)arg1 forContext:(id)arg2;	// IMP=0x0010000000a8733d
- (_Bool)canShowCards;	// IMP=0x0010000000a872d7
- (void)prepareMapViewForFirstUse;	// IMP=0x0010000000a871e9
- (void)didUnsuppress;	// IMP=0x0010000000a8700a
- (void)didSuppress;	// IMP=0x0010000000a86ef1
- (void)viewDidLoad;	// IMP=0x0010000000a86e03
- (id)initWithSceneType:(long long)arg1;	// IMP=0x0010000000a86dd4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

