//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MapKit/MKTableViewCell.h>

@class CollectionView;
@protocol CollectionHandlerInfo;

@interface CollectionTableViewCell : MKTableViewCell
{
    CollectionView *_collectionView;	// 8 = 0x8
    _Bool _disabled;	// 16 = 0x10
    _Bool _showCheckmark;	// 17 = 0x11
    id <CollectionHandlerInfo> _collectionInfo;	// 24 = 0x18
    unsigned long long _collectionViewSize;	// 32 = 0x20
}

+ (double)estimatedCellHeight;	// IMP=0x00200000006a286e
+ (double)cellHeight;	// IMP=0x00100000006a285d
+ (id)identifier;	// IMP=0x00100000006a2850
- (void).cxx_destruct;	// IMP=0x00200000006a2fa7
@property(nonatomic, getter=showsCheckmark) _Bool showCheckmark; // @synthesize showCheckmark=_showCheckmark;
@property(nonatomic) unsigned long long collectionViewSize; // @synthesize collectionViewSize=_collectionViewSize;
@property(nonatomic) _Bool disabled; // @synthesize disabled=_disabled;
@property(retain, nonatomic) id <CollectionHandlerInfo> collectionInfo; // @synthesize collectionInfo=_collectionInfo;
- (void)createContent;	// IMP=0x00100000006a2a30
- (id)_cellBackgroundColor;	// IMP=0x00100000006a28d9
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00100000006a287c

@end

