//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSMapTable, NSMutableArray;

@interface ContainerStack : NSObject
{
    NSMutableArray *_array;	// 8 = 0x8
    NSMapTable *_content;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000155196
- (id)description;	// IMP=0x0010000000155180
- (id)lastState;	// IMP=0x0010000000155119
- (unsigned long long)count;	// IMP=0x0010000000155103
- (id)allObjects;	// IMP=0x00100000001550e5
- (id)popFromIndex:(unsigned long long)arg1;	// IMP=0x0010000000154f22
- (MISSING_TYPE *)popAll;	// IMP=0x0010000000154dbc
- (void)replaceLastOne:(id)arg1;	// IMP=0x0010000000154cdc
- (void)removeContaineeState:(id)arg1;	// IMP=0x0010000000154bdd
- (void)pushContaineeState:(id)arg1;	// IMP=0x0010000000154b2c
- (id)containeeStateForContainee:(id)arg1;	// IMP=0x0010000000154b16
- (id)containeeStateAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000154a77
- (unsigned long long)indexOfContainee:(id)arg1;	// IMP=0x0010000000154a61
- (id)init;	// IMP=0x00100000001549c7

@end

