//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface DirectionsHistoryRecordingHelper : NSObject
{
}

+ (id)destinationGEOMapItemToRecordWithDirectionItem:(id)arg1;	// IMP=0x0040000000a56fe2
+ (id)destinationGEOMapItemToRecordWithDirectionIntent:(id)arg1 searchResults:(id)arg2;	// IMP=0x0010000000a56de8

@end

