//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIToolbar, UIVisualEffectView;

@interface FooterToolBarView
{
    UIVisualEffectView *_blurView;	// 8 = 0x8
    _Bool _canDeleteOnly;	// 16 = 0x10
    _Bool _canBeSaved;	// 17 = 0x11
    _Bool _canMove;	// 18 = 0x12
    _Bool _canAdaptToWidth;	// 19 = 0x13
    unsigned long long _state;	// 24 = 0x18
    id _delegate;	// 32 = 0x20
    UIToolbar *_toolBar;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000000ec2d2
@property(retain, nonatomic) UIToolbar *toolBar; // @synthesize toolBar=_toolBar;
@property(nonatomic) _Bool canAdaptToWidth; // @synthesize canAdaptToWidth=_canAdaptToWidth;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool canMove; // @synthesize canMove=_canMove;
@property(nonatomic) _Bool canBeSaved; // @synthesize canBeSaved=_canBeSaved;
@property(nonatomic) _Bool canDeleteOnly; // @synthesize canDeleteOnly=_canDeleteOnly;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void)_udpateContent;	// IMP=0x00100000000ec1e9
- (void)updateTheme;	// IMP=0x00100000000ec116
- (void)layoutSubviews;	// IMP=0x00100000000ec0c1
- (id)contentView;	// IMP=0x00100000000ec0a4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000000eba04

@end

