//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MeCardDataProvider, NSArray, NSMutableArray, NSString, ShortcutEditSession, ShortcutManager, SuggestionsDataProvider;
@protocol MapsUIDiffableDataSourceViewModel;

@interface HomeOutlineFavoritesSectionController
{
    SuggestionsDataProvider *_suggestionsDataProvider;	// 8 = 0x8
    MeCardDataProvider *_meCardDataProvider;	// 16 = 0x10
    ShortcutEditSession *_shortcutEditSession;	// 24 = 0x18
    NSMutableArray *_dropShortcutEditSessions;	// 32 = 0x20
    NSMutableArray *_deleteShortcutEditSessions;	// 40 = 0x28
    ShortcutManager *_shortcutManager;	// 48 = 0x30
    NSArray *_entriesForMoveAnimation;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000008554c3
@property(readonly, nonatomic) SuggestionsDataProvider *suggestionsDataProvider; // @synthesize suggestionsDataProvider=_suggestionsDataProvider;
- (void)collectionView:(id)arg1 performDropWithCoordinator:(id)arg2;	// IMP=0x00100000008553e6
- (id)collectionView:(id)arg1 dropSessionDidUpdate:(id)arg2 withDestinationIndexPath:(id)arg3;	// IMP=0x0010000000855277
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0010000000854fff
- (void)_deleteSnapshot:(id)arg1;	// IMP=0x0010000000854cb1
- (id)_shortcutForNodeSnapshot:(id)arg1;	// IMP=0x0010000000854bbd
- (long long)_headerNodeCount;	// IMP=0x0010000000854bb2
- (id)_entries;	// IMP=0x0010000000854b04
- (void)_performCopyWithDropCoordinator:(id)arg1;	// IMP=0x0010000000854847
- (_Bool)_isCopyOperationWithDropSession:(id)arg1;	// IMP=0x00100000008547be
- (void)_animateMoveOfShortcut:(id)arg1 toIndex:(unsigned long long)arg2 dropCoordinator:(id)arg3;	// IMP=0x001000000085444f
- (void)_performMoveWithDropCoordinator:(id)arg1;	// IMP=0x00100000008540ea
- (_Bool)_isMoveOperationWithDropSession:(id)arg1;	// IMP=0x0010000000853d46
- (_Bool)_shouldShowAccessoryForEntry:(id)arg1;	// IMP=0x0010000000853d36
- (_Bool)_accessoryVisiblityForEntry:(id)arg1;	// IMP=0x0010000000853ba9
- (void)_endEditSession;	// IMP=0x0010000000853b2c
- (void)_startEditSessionForShortcut:(id)arg1 sourceView:(id)arg2 sourceRect:(struct CGRect)arg3;	// IMP=0x00100000008538b7
- (void)smallButtonOutlineCellTapped:(id)arg1;	// IMP=0x00100000008538a5
- (void)sectionHeaderOutlineCell:(id)arg1 accessoryTypeTapped:(long long)arg2;	// IMP=0x001000000085388b
- (void)twoLinesOutlineCell:(id)arg1 accessoryViewTapped:(id)arg2 accessoryModel:(id)arg3;	// IMP=0x00100000008536d8
- (void)_addFavorite;	// IMP=0x0010000000853596
- (_Bool)_shouldShowAddButtonForItemSnapshots:(id)arg1;	// IMP=0x0010000000853391
- (id)shareItemSourceForSnapshot:(id)arg1;	// IMP=0x00100000008531a0
- (void)_openSnapshot:(id)arg1 inNewTab:(_Bool)arg2;	// IMP=0x0010000000852e6b
- (void)_copyEntrySnapshot:(id)arg1;	// IMP=0x0010000000852e65
- (void)_editEntrySnapshot:(id)arg1;	// IMP=0x0010000000852b04
- (id)contextMenuForSnapshot:(id)arg1;	// IMP=0x0010000000852137
@property(readonly, nonatomic) _Bool persistsExpansions;
- (id)sourceViewForProfileTipPopover;	// IMP=0x0010000000851fdc
- (_Bool)shouldClearSelectionWithReason:(id)arg1;	// IMP=0x0010000000851fc4
@property(readonly, nonatomic) NSArray *itemSnapshots;
@property(readonly, nonatomic) id <MapsUIDiffableDataSourceViewModel> sectionHeaderViewModel;
@property(readonly, nonatomic) NSArray *dataProviders;
- (id)initWithConfiguration:(id)arg1 suggestionsDataProvider:(id)arg2;	// IMP=0x00100000008517c6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

