//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, UICollectionViewCellRegistration;
@protocol HomeSearchStatusOutlineCellModelDelegate;

@interface HomeSearchStatusOutlineCellModel : NSObject
{
    _Bool;	// 8 = 0x8
    NSString *_errorString;	// 16 = 0x10
    id <HomeSearchStatusOutlineCellModelDelegate> _delegate;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000011aff2
@property(readonly, copy, nonatomic) id <HomeSearchStatusOutlineCellModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) _Bool enableStructuredRAPAffordance; // @synthesize enableStructuredRAPAffordance=_enableStructuredRAPAffordance;
@property(readonly, copy, nonatomic) NSString *errorString; // @synthesize errorString=_errorString;
- (_Bool)needsReloadFromPreviousViewModel:(id)arg1;	// IMP=0x001000000011afc0
@property(readonly, nonatomic) UICollectionViewCellRegistration *cellRegistration;
- (id)_maps_diffableDataSourceIdentifier;	// IMP=0x001000000011af9a
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000011af0c
@property(readonly) unsigned long long hash;
- (id)initWithErrorString:(id)arg1 enableStructuredRAPAffordance:(_Bool)arg2 delegate:(id)arg3;	// IMP=0x001000000011ae53

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

