//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable;

@interface LoadingIndicatorController : NSObject
{
    NSHashTable *_loadingTokens;	// 8 = 0x8
    _Bool _updateScheduled;	// 16 = 0x10
    _Bool _showing;	// 17 = 0x11
    _Bool _suppressed;	// 18 = 0x12
}

+ (void)setAsSharedInstanceClass;	// IMP=0x00400000008de14d
+ (id)sharedController;	// IMP=0x00100000008de111
- (void).cxx_destruct;	// IMP=0x00200000008de51f
@property(nonatomic, getter=isSuppressed) _Bool suppressed; // @synthesize suppressed=_suppressed;
@property(readonly, nonatomic, getter=isShowing) _Bool showing; // @synthesize showing=_showing;
- (void)_didInvalidateLoadingToken;	// IMP=0x00100000008de470
- (id)beginShowingLoadingIndicator;	// IMP=0x00100000008de25c
- (_Bool)_isLoading;	// IMP=0x00100000008de210
- (void)showingDidChange;	// IMP=0x00100000008de20a
- (void)_updateLoadingIndicator;	// IMP=0x00100000008de1c2
- (id)_allLoadingTokens;	// IMP=0x00100000008de190

@end

