//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class UIButton, UIVisualEffectView;
@protocol LookAroundTTRButtonViewDelegate;

@interface LookAroundTTRButtonView : UIView
{
    id <LookAroundTTRButtonViewDelegate> _delegate;	// 8 = 0x8
    UIVisualEffectView *_blurView;	// 16 = 0x10
    UIButton *_button;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000302fff
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UIVisualEffectView *blurView; // @synthesize blurView=_blurView;
@property(nonatomic) __weak id <LookAroundTTRButtonViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)buttonTapped:(id)arg1;	// IMP=0x0010000000302f13
- (void)_setupConstraints;	// IMP=0x00100000003029c6
- (void);	// IMP=0x001000000030278a
- (id)init;	// IMP=0x0010000000302715
- (id)contentView;	// IMP=0x00100000003026c5

@end

