//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface LPROnboardingPageViewController
{
    long long _scenario;	// 8 = 0x8
}

- (void)continuePressed;	// IMP=0x0020000000a50eb2
- (void)cancel;	// IMP=0x0010000000a50e99
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0010000000a50def
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000a50cff
- (void)viewDidLoad;	// IMP=0x0010000000a50667
- (id)initWithScenario:(long long)arg1;	// IMP=0x0010000000a50623

@end

