//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class MKMapItem, NSString, UIButton, UILabel, UITextField;

@interface MacCollectionRenameViewController : UIViewController
{
    UILabel *_label;	// 8 = 0x8
    UITextField *_textField;	// 16 = 0x10
    UIButton *_cancelButton;	// 24 = 0x18
    UIButton *_saveButton;	// 32 = 0x20
    MKMapItem *_mapItem;	// 40 = 0x28
    CDUnknownBlockType _saveHandler;	// 48 = 0x30
    CDUnknownBlockType _cancelHandler;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000716366
@property(readonly, nonatomic) CDUnknownBlockType cancelHandler; // @synthesize cancelHandler=_cancelHandler;
@property(readonly, nonatomic) CDUnknownBlockType saveHandler; // @synthesize saveHandler=_saveHandler;
@property(readonly, nonatomic) MKMapItem *mapItem; // @synthesize mapItem=_mapItem;
- (_Bool)textFieldShouldReturn:(id)arg1;	// IMP=0x001000000071631e
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;	// IMP=0x0010000000716201
- (id)keyCommands;	// IMP=0x001000000071615c
- (void)_cancel;	// IMP=0x0010000000716123
- (void)_save;	// IMP=0x00100000007160ab
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0010000000716062
- (void)viewDidLoad;	// IMP=0x0010000000715001
- (void)loadView;	// IMP=0x0010000000714f94
- (id)initWithMapItem:(id)arg1 saveHandler:(CDUnknownBlockType)arg2 cancelHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000714eae

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

