//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewController.h>

@class MISSING_TYPE, NSArray, UITableViewDiffableDataSource, _MapDataSubscriptionStateObserverRegistry;

@interface MapDataSubscriptionsDebugViewController : UITableViewController
{
    MISSING_TYPE *_subscriptionManager;	// 8 = 0x8
    NSArray *_subscriptions;	// 16 = 0x10
    _MapDataSubscriptionStateObserverRegistry *_observerRegistry;	// 24 = 0x18
    UITableViewDiffableDataSource *_dataSource;	// 32 = 0x20
    int _subscriptionsChangedNotifyToken;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000004e65da
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00100000004e6434
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00100000004e6423
- (void)_reloadSubscriptions;	// IMP=0x00100000004e5614
- (id)_configuredCellForSubscriptionIdentifier:(id)arg1;	// IMP=0x00100000004e4daa
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00100000004e4d5d
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00100000004e4beb
- (void)viewDidLoad;	// IMP=0x00100000004e4944

@end

