//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIResponder.h>

@class AppCoordinator, ApplicationSessionController, BKSProcessAssertion, CarDisplayController, DataActivationPopupAssertion, FavoritesSpotlightIndexingClient, FeedbackSubmissionManager, ForegroundOnlyDataActivationPopupAssertion, IOSChromeViewController, IPCLoadDirectionsMessage, IdleTimerController, MSPCloudSynchronizer, MUPlaceholderGridCache, MapsDistanceUnitUpdater, MapsSyncDataMigrator, NSArray, NSString, NavigationIdleTimerProvider, NavigationThermalWarningController, POISearchManager, PlatformController, SBSSecureAppAssertion, SBSStatusBarStyleOverridesAssertion, SiriNavStatusUpdater, UGCAppKitPreferencesPrivacyController, UIWindow;

@interface MapsAppDelegate : UIResponder
{
    int _navNotifyToken;	// 8 = 0x8
    _Bool _hasNavNotifyToken;	// 12 = 0xc
    _Bool _isNavigatingTurnByTurn;	// 13 = 0xd
    _Bool _isTrackingLocation;	// 14 = 0xe
    _Bool _isShowingTour;	// 15 = 0xf
    _Bool _carNavigationWasVisible;	// 16 = 0x10
    _Bool _canShowInLockscreen;	// 17 = 0x11
    _Bool _didSkipInitialUIKitBuildMenuCall;	// 18 = 0x12
    DataActivationPopupAssertion *_navigatorDataActivationPopupAssertion;	// 24 = 0x18
    ForegroundOnlyDataActivationPopupAssertion *_foregroundDataActivationPopupAssertion;	// 32 = 0x20
    POISearchManager *_poiSearchManager;	// 40 = 0x28
    FavoritesSpotlightIndexingClient *_favoritesSpotlightIndexingClient;	// 48 = 0x30
    MSPCloudSynchronizer *_cloudSynchronizer;	// 56 = 0x38
    MapsSyncDataMigrator *_syncMigrator;	// 64 = 0x40
    CarDisplayController *_carDisplayController;	// 72 = 0x48
    MUPlaceholderGridCache *_placeholderGridCache;	// 80 = 0x50
    UGCAppKitPreferencesPrivacyController *_ugcPrivacyController;	// 88 = 0x58
    IPCLoadDirectionsMessage *_lastPrepareNavigationMessage;	// 96 = 0x60
    NavigationIdleTimerProvider *_navigationIdleTimerProvider;	// 104 = 0x68
    NavigationIdleTimerProvider *_transitIdleTimerProvider;	// 112 = 0x70
    NavigationThermalWarningController *_thermalWarningController;	// 120 = 0x78
    SBSStatusBarStyleOverridesAssertion *_doubleHeightStatusBarAssertion;	// 128 = 0x80
    SBSSecureAppAssertion *_secureAppAssertion;	// 136 = 0x88
    FeedbackSubmissionManager *_submissionManager;	// 144 = 0x90
    _Bool _coreRoutineEnabled;	// 152 = 0x98
    ApplicationSessionController *_appSessionController;	// 160 = 0xa0
    IdleTimerController *_idleTimerController;	// 168 = 0xa8
    unsigned long long _lockedOrientations;	// 176 = 0xb0
    BKSProcessAssertion *_priorityAssertion;	// 184 = 0xb8
    SiriNavStatusUpdater *_siriNavStatusUpdater;	// 192 = 0xc0
    MapsDistanceUnitUpdater *_distanceUnitUpdater;	// 200 = 0xc8
}

+ (_Bool)mapsIsLaunchedForTesting;	// IMP=0x002000000046266c
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;	// IMP=0x0010000000889d2b
- (void).cxx_destruct;	// IMP=0x001000000046a168
@property(retain, nonatomic) MapsDistanceUnitUpdater *distanceUnitUpdater; // @synthesize distanceUnitUpdater=_distanceUnitUpdater;
@property(retain, nonatomic) SiriNavStatusUpdater *siriNavStatusUpdater; // @synthesize siriNavStatusUpdater=_siriNavStatusUpdater;
@property(retain, nonatomic) BKSProcessAssertion *priorityAssertion; // @synthesize priorityAssertion=_priorityAssertion;
@property(readonly, nonatomic) MSPCloudSynchronizer *cloudSynchronizer; // @synthesize cloudSynchronizer=_cloudSynchronizer;
@property(readonly, nonatomic) FavoritesSpotlightIndexingClient *favoritesSpotlightIndexingClient; // @synthesize favoritesSpotlightIndexingClient=_favoritesSpotlightIndexingClient;
@property(readonly, nonatomic, getter=isCoreRoutineEnabled) _Bool coreRoutineEnabled; // @synthesize coreRoutineEnabled=_coreRoutineEnabled;
@property(nonatomic) unsigned long long lockedOrientations; // @synthesize lockedOrientations=_lockedOrientations;
@property(retain, nonatomic) IdleTimerController *idleTimerController; // @synthesize idleTimerController=_idleTimerController;
@property(retain, nonatomic) ApplicationSessionController *appSessionController; // @synthesize appSessionController=_appSessionController;
- (id)photoAttributionPreferencesManager;	// IMP=0x001000000046a064
- (_Bool)useLargeLabelsPreferenceForAppkitBundle;	// IMP=0x001000000046a045
- (void)appkitBundleSetUseLargeLabels:(_Bool)arg1;	// IMP=0x001000000046a02c
- (void)presentRatingsAndPhotosPrivacyScreen;	// IMP=0x0010000000469f74
- (void)notificationButtonPressedWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000469bd1
- (void)fetchNotificationAuthUndetermined:(CDUnknownBlockType)arg1;	// IMP=0x0010000000469a35
- (void)preferencesPrivacyControllerDidDismiss:(id)arg1;	// IMP=0x0010000000469a14
- (void)presentMacARPPreferences;	// IMP=0x0010000000469a02
- (void)presentMacRoutePlannerPreferences;	// IMP=0x00100000004699f0
- (void)presentMacGeneralPreferences;	// IMP=0x00100000004699de
- (void)presentPreferences;	// IMP=0x00100000004699d8
- (void)presentMacPreferencesTabWithType:(long long)arg1;	// IMP=0x00100000004699b7
- (id)loadAppKitBundle;	// IMP=0x00100000004699af
- (Class)appKitBundleClass;	// IMP=0x00100000004699a7
- (void)buildMenuWithBuilder:(id)arg1;	// IMP=0x001000000046985a
- (id)testCoordinator;	// IMP=0x001000000046980a
- (id)mainVKMapView;	// IMP=0x0010000000469769
- (id)sceneDelegateForTesting;	// IMP=0x0010000000469697
- (id)visibleMapViewFromCarPlay;	// IMP=0x0010000000469616
@property(readonly, nonatomic) NSArray *allVisibleMapViewsButNotCarPlay;
@property(readonly, nonatomic) NSArray *allVisibleMapViews;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0010000000469088
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000468f39
- (void)endBackgroundNavigation;	// IMP=0x0010000000468e3e
- (void)updateWithGuidance:(id)arg1;	// IMP=0x0010000000468dd1
- (void)startPreparedBackgroundNavigationWithMessage:(id)arg1;	// IMP=0x0010000000468695
- (void)prepareBackgroundNavigationWithMessage:(id)arg1;	// IMP=0x0010000000468196
- (void)navigationService:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x0010000000467b60
- (void)navigationServiceWillResumeFromPause:(id)arg1;	// IMP=0x0010000000467b4e
- (void)navigationServiceWillPause:(id)arg1;	// IMP=0x0010000000467b3c
- (void)navigationService:(id)arg1 didEnableGuidancePrompts:(_Bool)arg2;	// IMP=0x0010000000467abb
- (void)navigationService:(id)arg1 didResumeNavigatingFromWaypoint:(id)arg2 endOfLegIndex:(unsigned long long)arg3 reason:(unsigned long long)arg4;	// IMP=0x00100000004679f1
- (void)navigationService:(id)arg1 didArriveAtWaypoint:(id)arg2 endOfLegIndex:(unsigned long long)arg3;	// IMP=0x001000000046797f
- (void)navigationService:(id)arg1 didChangeFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;	// IMP=0x0010000000467761
- (void)navigationService:(id)arg1 willChangeFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;	// IMP=0x00100000004675d7
- (_Bool)_supportsModernTransitNavigation:(id)arg1;	// IMP=0x00100000004675aa
- (void)_releaseProcessAssertion;	// IMP=0x001000000046730d
- (void)_acquireProcessAssertionForTurnByTurn:(_Bool)arg1;	// IMP=0x00100000004670e6
- (void)chromeViewController:(id)arg1 didMoveFromContextStack:(id)arg2 toContextStack:(id)arg3;	// IMP=0x001000000046703d
- (void)chromeViewController:(id)arg1 willMoveFromContextStack:(id)arg2 toContextStack:(id)arg3;	// IMP=0x0010000000466f94
- (void)endTurnByTurn:(id)arg1;	// IMP=0x0010000000466d9a
- (void)endTransitTurnByTurn;	// IMP=0x0010000000466d79
- (void)startTurnByTurn:(id)arg1;	// IMP=0x001000000046688e
- (void)startTransitTurnByTurn;	// IMP=0x00100000004667bc
@property(readonly, nonatomic) _Bool canPlayTrace;
- (void)_releaseSecureAppAssertion;	// IMP=0x00100000004666f9
- (void)_acquireSecureAppAssertion;	// IMP=0x00100000004664d2
- (void)_updateSecureAppAssertion;	// IMP=0x0010000000465d8b
- (void)_setCanShowInLockscreen:(_Bool)arg1;	// IMP=0x0010000000465ab4
- (void)acquireSecureAppAssertionIfNeeded;	// IMP=0x0010000000465aa2
- (void)updateNavigationIdleTimerConfiguration;	// IMP=0x0010000000465a85
- (void)setMapsIsShowingTour:(_Bool)arg1;	// IMP=0x001000000046595d
- (void)setTrackingMode:(long long)arg1 monitorBatteryState:(_Bool)arg2;	// IMP=0x00100000004658e2
- (void)_clearDoubleHeightStatusBar;	// IMP=0x0010000000465827
- (void)_acquireDoubleHeightStatusBarAssertionIfNeeded;	// IMP=0x00100000004655a7
- (void)_unsuppressNetworkFlagsIfNecessary;	// IMP=0x0010000000465595
- (void)_unsuppressNetworkFlags;	// IMP=0x001000000046557a
- (void)_suppressNetworkFlags;	// IMP=0x0010000000465565
- (void)carDisplayControllerDidUpdateNavigationVisibility:(id)arg1;	// IMP=0x00100000004652bd
- (void)prepareForCarPlayLaunch;	// IMP=0x0010000000465245
- (void)_localeDidChange:(id)arg1;	// IMP=0x001000000046522c
- (void);	// IMP=0x00100000004651a1
- (void)migrateNavigoDefaults:(id)arg1;	// IMP=0x00100000004650b9
- (void)_userDefaultsDidChange:(id)arg1;	// IMP=0x001000000046509c
- (void)_registerDefaults;	// IMP=0x0010000000464dc3
- (_Bool)applicationCanPromptToCalibrateHeading:(id)arg1;	// IMP=0x0010000000464dbb
- (void)applicationDidRemoveDeactivationReason:(id)arg1;	// IMP=0x0010000000464caf
- (void)applicationWillAddDeactivationReason:(id)arg1;	// IMP=0x0010000000464ba3
- (void)_maps_applicationDidEnterBackground:(id)arg1;	// IMP=0x0010000000464ae2
- (void)_maps_applicationWillEnterForeground:(id)arg1;	// IMP=0x0010000000464a5b
- (void)_maps_applicationWillResignActive:(id)arg1;	// IMP=0x00100000004649a6
- (void)_maps_applicationDidBecomeActive:(id)arg1;	// IMP=0x00100000004646e9
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000464658
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;	// IMP=0x001000000046459c
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;	// IMP=0x00100000004644e0
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;	// IMP=0x00100000004644a7
- (id)application:(id)arg1 configurationForConnectingSceneSession:(id)arg2 options:(id)arg3;	// IMP=0x001000000046413e
- (void)applicationDidReceiveMemoryWarning:(id)arg1;	// IMP=0x00100000004640cb
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x0010000000463ed5
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0010000000463cdc
- (_Bool)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;	// IMP=0x00100000004635d0
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000046349f
- (void)_performPostExtendedLaunchInitialization;	// IMP=0x0010000000463247
- (void)receivedFullyDrawnNotification;	// IMP=0x0010000000463136
- (void)sendDidEnterBackgroundNotification;	// IMP=0x00100000004630e1
@property(readonly, nonatomic) double timeIntervalSinceLastBackgrounded;
- (void)checkCoreRoutineEnabledState;	// IMP=0x0010000000462ee0
- (void)_setupSharedLocationManager;	// IMP=0x0010000000462ba6
- (void)_startSyncIfNeededAllowingHistorySyncStartDuringTesting:(_Bool)arg1;	// IMP=0x0010000000462a24
@property(readonly, nonatomic) POISearchManager *poiSearchManager;
- (id)entryPointsCoordinator;	// IMP=0x001000000046294b
@property(readonly, nonatomic) IOSChromeViewController *chromeViewController;
@property(readonly, nonatomic) AppCoordinator *appCoordinator;
@property(readonly, nonatomic) PlatformController *platformController;
- (void)dealloc;	// IMP=0x00100000004626a4
@property(readonly, nonatomic) FeedbackSubmissionManager *submissionManager;
- (void)createSubmissionManagerIfNeeded;	// IMP=0x0010000000338f59
- (void)showNavigationAdvisoryIfNeeded;	// IMP=0x0010000000889ad1
- (void)promptPreciseLocationOff;	// IMP=0x0010000000889434
- (void)promptLocationServicesOff;	// IMP=0x0010000000888e17
- (void)_presentLocationServicesAlertController:(id)arg1;	// IMP=0x0010000000888c40
- (void)_cleanupAfterLocationServicesAlertController;	// IMP=0x0010000000888ba1
- (void)_locationManagerApprovalDidChange:(id)arg1;	// IMP=0x0010000000888a44
- (void)promptLocationServicesAuthorizationWithHandler:(CDUnknownBlockType)arg1 forceAlways:(_Bool)arg2;	// IMP=0x0010000000888824
- (void)promptLocationServicesAuthorizationWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000888810
- (void)showLocationServicesAlertWithError:(id)arg1;	// IMP=0x0010000000888603
- (void)interruptApplicationWithKind:(long long)arg1 userInfo:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000887a41
- (_Bool)dismissCurrentInterruptionOfKind:(long long)arg1;	// IMP=0x00100000008879fb
- (void)dismissCurrentInterruption;	// IMP=0x0010000000887831
@property(readonly, nonatomic) long long currentInterruptionKind;
- (void)_locationAuthorizationDismissed:(id)arg1;	// IMP=0x00100000008877d0
- (void)_setShowingLocationServicesAuthorizationPrompt:(_Bool)arg1;	// IMP=0x00100000008875c9
- (_Bool)_isShowingLocationServicesAuthorizationPrompt;	// IMP=0x001000000088748c
- (void)_setCurrentInterruptionHandle:(id)arg1;	// IMP=0x00100000008873d7
- (id)_currentInterruptionHandle;	// IMP=0x00100000008873c6
- (void)addAttachmentsPathToComposer:(id)arg1;	// IMP=0x0010000000a246ff
- (void)presentRadarComposerIfPossibleInViewController:(id)arg1 showingTracePicker:(_Bool)arg2 traceFilePath:(id)arg3 radarTitle:(id)arg4 radarDescription:(id)arg5 classification:(unsigned long long)arg6 component:(unsigned long long)arg7;	// IMP=0x0010000000a243b6
- (void)presentRadarComposerIfPossibleInViewController:(id)arg1 showingTracePicker:(_Bool)arg2 traceFilePath:(id)arg3;	// IMP=0x0010000000a24388
- (void)presentRadarComposerIfPossibleInViewController:(id)arg1 reason:(id)arg2 radarTitle:(id)arg3 radarDescription:(id)arg4 shouldPrompt:(_Bool)arg5 classification:(unsigned long long)arg6 component:(unsigned long long)arg7;	// IMP=0x0010000000a240e6
- (void)presentRadarComposerIfPossibleInViewController:(id)arg1 reason:(id)arg2 radarTitle:(id)arg3 classification:(unsigned long long)arg4 component:(unsigned long long)arg5;	// IMP=0x0010000000a240bf
- (void)presentRadarComposerIfPossibleInViewController:(id)arg1;	// IMP=0x0010000000a240a5
- (_Bool)createCurrentStateSnapshotAndReturnSnapshotDirectoryURL:(out id *)arg1 tileStateReportURLs:(out id *)arg2 screenshotImageURLs:(out id *)arg3 debugTreeURLs:(out id *)arg4 mapsActivityDataPath:(out id *)arg5 error:(out id *)arg6;	// IMP=0x0010000000a22a97
- (_Bool)_isMainScreenMapView:(id)arg1;	// IMP=0x0010000000a22a10
- (_Bool)_isCarPlayMapView:(id)arg1;	// IMP=0x0010000000a22965
- (void)presentAddAMissingPlaceWith:(id)arg1;	// IMP=0x0010000000a4745d
- (void)newScene;	// IMP=0x0010000000a473b3
- (void)requestNewWindow:(id)arg1;	// IMP=0x0010000000a473a1
- (void)requestNewTab:(id)arg1;	// IMP=0x0010000000a4738f
- (void)presentRadar;	// IMP=0x0010000000a47357
- (void)sendToDeviceWithID:(id)arg1;	// IMP=0x0010000000a47351
- (void)toggleDisableMenuSharing;	// IMP=0x0010000000a472c2
- (void)toggleScrollingOpensPlacecard;	// IMP=0x0010000000a47230
- (void)toggleSidebarSelection;	// IMP=0x0010000000a47157
- (void)presentAddAMissingPlace;	// IMP=0x0010000000a470e4
- (void)presentRAP;	// IMP=0x0010000000a47071
- (_Bool)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;	// IMP=0x0010000000afb2a4
- (id)currentTest;	// IMP=0x0010000000afb28b
- (void)setCurrentTest:(id)arg1;	// IMP=0x0010000000afb272
- (void)doPostLaunchTestSetup;	// IMP=0x0010000000afb17c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

