//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;

@interface MapsSearchPrintingInfo
{
    NSArray *_searchResultCells;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000053748c
@property(readonly, nonatomic) NSArray *searchResultCells; // @synthesize searchResultCells=_searchResultCells;
- (id)initWithNumberOfPages:(long long)arg1 searchResultCells:(id)arg2;	// IMP=0x00100000005373e4

@end

