//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableArray, NSString;

@interface MapsAppTestSearch
{
    NSString *_query;	// 8 = 0x8
    unsigned int _searchTestACMode;	// 16 = 0x10
    unsigned long long _maxACSearchQueryLength;	// 24 = 0x18
    NSMutableArray *_autoCompleteQueries;	// 32 = 0x20
    _Bool _isNearbyTest;	// 40 = 0x28
    unsigned long long _nearbyCategoryIndex;	// 48 = 0x30
    long long _directionIntentTestType;	// 56 = 0x38
    _Bool _isPrewarmingKeyboard;	// 64 = 0x40
    NSString *_selectACSuggestionMatchingAddress;	// 72 = 0x48
    _Bool _isShowcaseTest;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x00200000003609ea
- (void)continueDirectionIntentTest;	// IMP=0x00100000003608ce
- (void)refreshSearchAnnotationPinDroppedForResults:(id)arg1;	// IMP=0x0010000000360730
- (void)refreshSearchSessionDidChangeSearchResults:(id)arg1;	// IMP=0x0010000000360597
- (void)refreshSearchRequestSent:(id)arg1;	// IMP=0x0010000000360480
- (void)startRefreshSearchTestIfNeeded;	// IMP=0x00100000003600c4
- (void)finishSearchTest:(id)arg1;	// IMP=0x001000000035fffe
- (void)continueToNearbyScrollTests;	// IMP=0x001000000035feb8
- (void)annotationPinDroppedForResults:(id)arg1;	// IMP=0x001000000035fd1e
- (void)annotationPinDroppedForAResult:(id)arg1;	// IMP=0x001000000035fbba
- (void)searchSessionDidFail:(id)arg1;	// IMP=0x001000000035fbb4
- (void)searchSessionDidInvalidate:(id)arg1 reason:(unsigned long long)arg2;	// IMP=0x001000000035fbae
- (void)searchSessionWillPerformSearch:(id)arg1;	// IMP=0x001000000035fba8
- (void)searchSessionDidChangeSearchFieldItem:(id)arg1;	// IMP=0x001000000035fba2
- (void)continueToAnnotationsTestsWithSearchSession:(id)arg1;	// IMP=0x001000000035f9b0
- (void)searchSessionDidChangeSearchResults:(id)arg1;	// IMP=0x001000000035f7f6
- (void)searchRequestSent:(id)arg1;	// IMP=0x001000000035f721
- (void)sendSearchRequest;	// IMP=0x001000000035f60d
- (void)didEndGEOPPTTest_PlaceRequestTicket_PlaceDataRequest:(id)arg1;	// IMP=0x001000000035f3f6
- (void)willBeginGEOPPTTest_PlaceRequestTicket_PlaceDataRequest:(id)arg1;	// IMP=0x001000000035f2a4
- (void)searchAutoCompleteTestDidFinish;	// IMP=0x001000000035ee5e
- (void)searchAutoCompleteTestReceiveResponse:(id)arg1;	// IMP=0x001000000035ea6d
- (void)searchAutoCompleteTestSendQuery;	// IMP=0x001000000035e808
- (void)startSearchAutoCompleteTest;	// IMP=0x001000000035e55b
- (void)startScrollNearbyTestCategory;	// IMP=0x001000000035e41c
- (void)endNearbyTestCategory:(id)arg1;	// IMP=0x001000000035e33f
- (void)startNearbyTestCategory;	// IMP=0x001000000035e283
- (void)startNearbyTest;	// IMP=0x001000000035e24e
- (void)startAutocompleteOrNearbySearchTest;	// IMP=0x001000000035e223
- (void)searchKeyboardDidHide;	// IMP=0x001000000035e202
- (void)searchKeyboardDidShow;	// IMP=0x001000000035e162
- (void)searchKeyboardWillShow;	// IMP=0x001000000035e13a
- (void)searchUILayoutDone;	// IMP=0x001000000035e0c7
- (void)didDisplayCarplayBrowseCategories;	// IMP=0x001000000035da84
- (void)_prewarmingKeyboardCompleted;	// IMP=0x001000000035da67
- (void)_startPrewarmingKeyboard;	// IMP=0x001000000035da1f
- (void)_runTestNow;	// IMP=0x001000000035d0c4
- (void)runScrollBrowseCategoriesInCarPlay;	// IMP=0x001000000035ceaf
- (_Bool)runTest;	// IMP=0x001000000035ccdf
- (void)performOnMainQueue:(CDUnknownBlockType)arg1;	// IMP=0x001000000035cc29
- (void)startedSubTest:(id)arg1 withMetrics:(id)arg2;	// IMP=0x001000000035cb36
- (void)finishedSubTest:(id)arg1;	// IMP=0x001000000035ca70
- (void)startedSubTest:(id)arg1;	// IMP=0x001000000035c9aa
- (void)didEndMSGPPTTest_Insights_ACRanking_PreLoad:(id)arg1;	// IMP=0x001000000035c991
- (void)willBeginMSGPPTTest_Insights_ACRanking_PreLoad:(id)arg1;	// IMP=0x001000000035c971
- (void)didEndMSGPPTTest_Insights_ACRanking_RoutineCall:(id)arg1;	// IMP=0x001000000035c958
- (void)willBeginMSGPPTTest_Insights_ACRanking_RoutineCall:(id)arg1;	// IMP=0x001000000035c938
- (void)didEndMSGPPTTest_Insights_ACRanking_PortraitCall:(id)arg1;	// IMP=0x001000000035c91f
- (void)willBeginMSGPPTTest_Insights_ACRanking_PortraitCall:(id)arg1;	// IMP=0x001000000035c8ff
- (void)didEndMSGPPTTest_Insights_ACRanking_Tourist:(id)arg1;	// IMP=0x001000000035c8e6
- (void)willBeginMSGPPTTest_Insights_ACRanking_Tourist:(id)arg1;	// IMP=0x001000000035c8c6
- (void)didEndMSGPPTTest_Insights_ACRanking_Contacts:(id)arg1;	// IMP=0x001000000035c8ad
- (void)willBeginMSGPPTTest_Insights_ACRanking_Contacts:(id)arg1;	// IMP=0x001000000035c88d
- (void)didEndMSGPPTTest_Insights_ACRanking_MapItems:(id)arg1;	// IMP=0x001000000035c874
- (void)willBeginMSGPPTTest_Insights_ACRanking_MapItems:(id)arg1;	// IMP=0x001000000035c854

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

