//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MapsAppTestTransitRoute
{
}

- (void)_performRouteUpdateWithDetails;	// IMP=0x00400000001000b5
- (void)_performRouteUpdateWithList;	// IMP=0x00100000000ffe22
- (void)doAfterSubTestForDisplayingRoutes;	// IMP=0x00100000000ffd79

@end

