//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MapsBannerContent, UIStackView;

@interface MapsBannerContentView : UIView
{
    UIStackView *_vStack;	// 8 = 0x8
    MapsBannerContent *_content;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000079c3cf
@property(retain, nonatomic) MapsBannerContent *content; // @synthesize content=_content;
- (id)accessibilityIdentifier;	// IMP=0x001000000079c3ac
- (id)_topView:(id)arg1;	// IMP=0x001000000079c25d
- (id)_bodyContentView:(id)arg1;	// IMP=0x001000000079c06f
- (id)_bodyView:(id)arg1;	// IMP=0x001000000079b77a

@end

