//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSPointerArray.h>

@interface NSPointerArray (MapsExtras)
- (void)_maps_compact;	// IMP=0x00200000008e5cd4
- (void)_maps_removeAllObjects;	// IMP=0x00100000008e5cc0
- (void)_maps_removeObject:(id)arg1;	// IMP=0x00100000008e5c27
- (void)_maps_moveOrAddObjectToTop:(id)arg1;	// IMP=0x00100000008e5b7b
- (_Bool)_maps_containsObject:(id)arg1;	// IMP=0x00100000008e5aef
@property(readonly) id _maps_lastObject;
@end

