//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSSet.h>

@interface NSSet (SearchResultAdditions)
- (id)_maps_searchResultMemberEqualToResult:(id)arg1 forPurpose:(long long)arg2;	// IMP=0x00100000008ac569
- (_Bool)_maps_containsSearchResultEqualToResult:(id)arg1 forPurpose:(long long)arg2;	// IMP=0x00100000008ac3a4
@end

