//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol RAPDirectionsStepsListDelegate;

@interface RAPDirectionsStepsListDataSource
{
    double _dummyTrailingViewWidth;	// 8 = 0x8
    id <RAPDirectionsStepsListDelegate> _rapDelegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000003359b1
@property(nonatomic) __weak id <RAPDirectionsStepsListDelegate> rapDelegate; // @synthesize rapDelegate=_rapDelegate;
- (double)_trailingViewWidth;	// IMP=0x00100000003358e4
- (id)_rapDisclosureViewForCell:(id)arg1 routeStep:(id)arg2;	// IMP=0x00100000003357b8
- (id)trailingViewForInstructionIncorrectView:(id)arg1;	// IMP=0x00100000003355ca
- (void)_attachDisclosureViewToCell:(id)arg1 routeStep:(id)arg2;	// IMP=0x0010000000335463
- (unsigned long long)routeStepIndexForRowIndex:(unsigned long long)arg1;	// IMP=0x0010000000335415
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000335293
- (void)setOptions:(unsigned long long)arg1;	// IMP=0x0010000000335261
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x00100000003351f9
- (id)init;	// IMP=0x00100000003351b0

@end

