//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOPDHours, GEORPFeedbackBusinessHours, NSArray, NSDate, NSMutableArray;

@interface RAPStoreHour : NSObject
{
    NSMutableArray *_mutableDaysOpen;	// 8 = 0x8
    id _observer;	// 16 = 0x10
    CDUnknownBlockType _changeHandler;	// 24 = 0x18
    GEOPDHours *_shadowHours;	// 32 = 0x20
    _Bool _open24Hours;	// 40 = 0x28
    NSDate *_startDate;	// 48 = 0x30
    NSDate *_endDate;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x002000000041381e
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(nonatomic) _Bool open24Hours; // @synthesize open24Hours=_open24Hours;
- (void)notifyObserver;	// IMP=0x0010000000413797
- (void)clearObserver;	// IMP=0x001000000041376b
- (void)setObserver:(id)arg1 changeHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000041370a
@property(readonly, nonatomic) GEORPFeedbackBusinessHours *businessHours;
- (_Bool)isSubmittable;	// IMP=0x0010000000413495
- (_Bool)containsDay:(int)arg1;	// IMP=0x001000000041343a
- (void)toggleDay:(int)arg1;	// IMP=0x00100000004133b8
@property(readonly, nonatomic) NSArray *daysOpen;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000041322a
- (unsigned long long)hash;	// IMP=0x0010000000413152
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000412e7c
- (id)initWithPlaceDailyHours:(id)arg1;	// IMP=0x0010000000412e1f
- (id)init;	// IMP=0x0010000000412d83

@end

