//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface RAPSearchAutocompleteBlockFilter : NSObject
{
    CDUnknownBlockType _block;	// 8 = 0x8
}

+ (id)poiAutocompleteFilterWithExcludedMUIDs:(id)arg1;	// IMP=0x00400000001bc258
+ (id)addressAutocompleteFilter;	// IMP=0x00100000001bc1cb
- (void).cxx_destruct;	// IMP=0x00200000001bc456
- (id)initWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001bc0e7
- (_Bool)shouldFilterItem:(id)arg1;	// IMP=0x00100000001bc0d5

@end

