//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface RoutePlanningTransportTypeRefinementModel
{
}

- (void)_assertValidValue;	// IMP=0x0040000000825947
- (int)menuPressUsageAction;	// IMP=0x001000000082593c
- (id)menu;	// IMP=0x0010000000825414
- (long long)_resolvedTransportType;	// IMP=0x00100000008253b4
- (_Bool)shouldShowChevron;	// IMP=0x00100000008253ac
- (_Bool)shouldShowHighlighted;	// IMP=0x0010000000825364
- (id)titleText;	// IMP=0x00100000008251ac
- (id)iconImage;	// IMP=0x0010000000824fb8

@end

