//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOMapsSearchHomeResult, SearchHomeDataDownloaderCacheKey;

@interface SearchHomeDataDownloaderCache : NSObject
{
    SearchHomeDataDownloaderCacheKey *_cachedKey;	// 8 = 0x8
    GEOMapsSearchHomeResult *_cachedResults;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000012f1a4
@property(retain, nonatomic) GEOMapsSearchHomeResult *cachedResults; // @synthesize cachedResults=_cachedResults;
@property(retain, nonatomic) SearchHomeDataDownloaderCacheKey *cachedKey; // @synthesize cachedKey=_cachedKey;
- (_Bool)keyIsValid:(id)arg1;	// IMP=0x001000000012efa2
- (void)replaceCachedObject:(id)arg1 withKey:(id)arg2;	// IMP=0x001000000012ef4b
- (id)objectForKey:(id)arg1;	// IMP=0x001000000012eeba

@end

