//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol UITraitEnvironment;

@interface SearchHomeCuratedCollectionsLayoutProvider : NSObject
{
    id <UITraitEnvironment> _traitEnvironment;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000759712
@property(retain, nonatomic) id <UITraitEnvironment> traitEnvironment; // @synthesize traitEnvironment=_traitEnvironment;
- (id)layoutSectionWithLayoutEnvironment:(id)arg1 estimatedHeaderHeight:(double)arg2 estimatedFooterHeight:(double)arg3 deletionBlock:(CDUnknownBlockType)arg4 objectsCount:(unsigned long long)arg5 mapsTheme:(id)arg6;	// IMP=0x0010000000758de4
- (id)cellForRowAtIndexPath:(id)arg1 collectionView:(id)arg2 item:(id)arg3;	// IMP=0x0010000000758ce5
- (long long)type;	// IMP=0x0010000000758cda
- (id)cellReuseIdentifier;	// IMP=0x0010000000758cc1
- (id)cellClasses;	// IMP=0x0010000000758c55
- (id)initWithTraitEnvironment:(id)arg1;	// IMP=0x0010000000758bed

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

