//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MapsThemeButton, SmallButtonOutlineCellModel;

@interface SmallButtonOutlineCell
{
    MapsThemeButton *_button;	// 8 = 0x8
    SmallButtonOutlineCellModel *_cellModel;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000009209ad
// Error: Property attributes should begin with the type ('T') attribute, property name: cellModel
// Property attributes: (null)

- (void)hoverSourceStateDidChange:(id)arg1;	// IMP=0x001000000092095b
- (void)_buttonTapped:(id)arg1;	// IMP=0x0010000000920904
- (void)_updateImage;	// IMP=0x001000000092076a
- (void)_updateTitleColor;	// IMP=0x0010000000920649
- (void)_updateFromModel;	// IMP=0x00100000009205ac
- (void)tintColorDidChange;	// IMP=0x0010000000920508
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000092003a

@end

