//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GEOComposedTransitTripRouteSegment;

@interface TransitDirectionsListClusteredVehicleItem
{
    GEOComposedTransitTripRouteSegment *_clusteredSegment;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000032fcab
@property(readonly, nonatomic) GEOComposedTransitTripRouteSegment *clusteredSegment; // @synthesize clusteredSegment=_clusteredSegment;
- (id)initWithClusteredRouteSegment:(id)arg1;	// IMP=0x001000000032fc02

@end

