//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/_UINavigationBarTitleView.h>

@class NSString, UIImageView, UILabel;

@interface TransitPayEducationScreenTitleView : _UINavigationBarTitleView
{
    UILabel *_titleLabel;	// 8 = 0x8
    UIImageView *_iconImageView;	// 16 = 0x10
    NSString *_title;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000004fb051
- (id)_createIconImageView;	// IMP=0x00100000004faf7f
- (id)_createTitleLabel;	// IMP=0x00100000004faecb
- (void)_setUpConstraints;	// IMP=0x00100000004fa9dc
- (void)_setupViews;	// IMP=0x00100000004fa941
- (id)initWithTitle:(id)arg1;	// IMP=0x00100000004fa8a5

@end

