//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, UILabel;

@interface UGCPOIEnrichmentHeaderCell
{
    UILabel *_headerLabel;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000001ecb2f
@property(copy, nonatomic) NSString *headerText;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00100000001ec9d3
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000001ec828

@end

