//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIStackView.h>

@interface UIStackView (UIKitExtras)
+ (id)_maps_Spacer:(double)arg1;	// IMP=0x001000000052aba0
+ (id)_maps_Spacer:(double)arg1 visibilityModel:(id)arg2;	// IMP=0x001000000052aaf9
+ (id)_maps_HStack;	// IMP=0x001000000052aade
+ (id)_maps_VStack;	// IMP=0x001000000052aac0
+ (id)_maps_StackWithAxis:(long long)arg1;	// IMP=0x001000000052aa27
- (void)_maps_removeArrangedSubview:(id)arg1;	// IMP=0x0020000000179baa
- (void)_maps_setArrangedSubviews:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000017912d
- (void)_maps_setArrangedSubviews:(id)arg1;	// IMP=0x0010000000178e44
- (id)_maps_deepArrangedSubviews;	// IMP=0x001000000052af50
- (void)_maps_addArrangedExpandingSubview:(id)arg1 padding:(struct BannerContentPadding)arg2;	// IMP=0x001000000052af39
- (void)_maps_addArrangedContentHuggingSubview:(id)arg1 padding:(struct BannerContentPadding)arg2;	// IMP=0x001000000052af25
- (void)_addArrangedSubview:(id)arg1 layoutPriority:(unsigned long long)arg2 padding:(struct BannerContentPadding)arg3;	// IMP=0x001000000052ae27
- (void)_maps_addArrangedExpandingSubview:(id)arg1;	// IMP=0x001000000052ae10
- (void)_maps_addArrangedContentHuggingSubview:(id)arg1;	// IMP=0x001000000052adfc
- (void)_addArrangedSubview:(id)arg1 layoutPriority:(unsigned long long)arg2;	// IMP=0x001000000052acbb
- (void)_configureSpacerIfNeeded:(id)arg1 layoutPriority:(unsigned long long)arg2;	// IMP=0x001000000052abb4
@end

