//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface UserProfileAnalyticsManager : NSObject
{
}

+ (void)captureSettingsAppTapAction;	// IMP=0x00400000008b3666
+ (void)captureEnableTransitPreferenceForMode:(long long)arg1;	// IMP=0x00100000008b3633
+ (void)captureDisableTransitPreferenceForMode:(long long)arg1;	// IMP=0x00100000008b3600
+ (void)captureTravelPreferencesUserAction:(int)arg1;	// IMP=0x00100000008b35df
+ (void)captureTravelPreferencesUserAction:(int)arg1 value:(id)arg2;	// IMP=0x00100000008b35be
+ (void)capturePreferredDirectionsForTransportType:(long long)arg1;	// IMP=0x00100000008b3581
+ (void)captureRatingHistoryItemTapAction;	// IMP=0x00100000008b355b
+ (void)captureExitRatingsHistoryTapAction;	// IMP=0x00100000008b3535
+ (void)captureExitAccountTapAction;	// IMP=0x00100000008b350f
+ (void)captureICloudSignInTapAction;	// IMP=0x00100000008b34e9
+ (void)captureTapActionWithUserProfileLinkType:(long long)arg1 availableActions:(id)arg2 signedIntoICloud:(_Bool)arg3;	// IMP=0x00100000008b3284
+ (void)captureAccountDidAppearWithAvailableActions:(id)arg1 signedIntoICloud:(_Bool)arg2;	// IMP=0x00100000008b30a3
+ (void)captureEnterAccountTapAction;	// IMP=0x00100000008b3048

@end

