//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface UserCollectionHandler
{
    NSString *_stagedTitle;	// 8 = 0x8
    struct os_unfair_lock_s _modficationLock;	// 16 = 0x10
    long long _modificationCount;	// 24 = 0x18
    _Bool _needsToBePersisted;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000041cce2
@property(nonatomic) _Bool needsToBePersisted; // @synthesize needsToBePersisted=_needsToBePersisted;
- (int)showAction;	// IMP=0x001000000041cc71
- (void)updateCollection:(CDUnknownBlockType)arg1;	// IMP=0x001000000041caef
- (_Bool)containsItem:(id)arg1;	// IMP=0x001000000041c91b
- (void)updateTitle:(id)arg1 forMapItem:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000041c6f0
- (void)updateWithMapsSyncCollection:(id)arg1;	// IMP=0x001000000041c646
- (void)rebuildContent;	// IMP=0x001000000041c5b0
- (void)removeObjects:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000041bc0e
- (void)addObjects:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000041b298
- (void)existingCollectionItemForMapItem:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000041ae9e
- (_Bool)updateImage:(id)arg1;	// IMP=0x001000000041ac8e
- (_Bool)updateTitle:(id)arg1;	// IMP=0x001000000041abec
- (long long)contentType;	// IMP=0x001000000041abe1
- (_Bool)canDeleteContent;	// IMP=0x001000000041abd9
- (_Bool)canAddContent;	// IMP=0x001000000041abd1
- (_Bool)canEditTitle;	// IMP=0x001000000041ab8e
- (_Bool)canEditImage;	// IMP=0x001000000041ab86
- (_Bool)canDelete;	// IMP=0x001000000041ab43
- (void)setStagedTitle:(id)arg1;	// IMP=0x001000000041ab2f
- (id)stagedTitle;	// IMP=0x001000000041ab1a
- (id)title;	// IMP=0x001000000041aaa9
- (id)identifier;	// IMP=0x001000000041aa2f
- (id)sharingURL;	// IMP=0x001000000041a601
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000041a554
- (long long)handlerType;	// IMP=0x001000000041a54c
- (_Bool)beingModified;	// IMP=0x001000000041a510
- (void)endModification;	// IMP=0x001000000041a4dd
- (void)startModification;	// IMP=0x001000000041a4aa
- (id)initWithCollection:(id)arg1;	// IMP=0x001000000041a450

@end

