//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewCell.h>

@class MISSING_TYPE, UILabel;

@interface VehicleLabelCell : UITableViewCell
{
    UILabel *_label;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000675ed1
@property(readonly, nonatomic) UILabel *label; // @synthesize label=_label;
- (double)cellHeight;	// IMP=0x0010000000675e44
- (void)_commonInit;	// IMP=0x0010000000675afa
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0010000000675a90
- (MISSING_TYPE *)init;	// IMP=0x0010000000675a7a

@end

