//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSNumber, NSString, UIImageView, UILabel, UIView, VGVehicle, VehicleColorPicker, VehicleTextFieldCell;
@protocol VehicleAppearanceViewControllerDelegate;

@interface VehicleAppearanceViewController : UIViewController
{
    NSArray *_colors;	// 8 = 0x8
    VGVehicle *_vehicle;	// 16 = 0x10
    NSNumber *_selectedIndexBacking;	// 24 = 0x18
    _Bool _allowsEditingNickname;	// 32 = 0x20
    NSString *_currentNickname;	// 40 = 0x28
    id <VehicleAppearanceViewControllerDelegate> _delegate;	// 48 = 0x30
    UIView *_vehicleColorView;	// 56 = 0x38
    UIImageView *_vehicleIconView;	// 64 = 0x40
    VehicleTextFieldCell *_nicknameCell;	// 72 = 0x48
    UILabel *_colorTitleLabel;	// 80 = 0x50
    VehicleColorPicker *_colorPicker;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x002000000037b291
@property(retain, nonatomic) VehicleColorPicker *colorPicker; // @synthesize colorPicker=_colorPicker;
@property(retain, nonatomic) UILabel *colorTitleLabel; // @synthesize colorTitleLabel=_colorTitleLabel;
@property(retain, nonatomic) VehicleTextFieldCell *nicknameCell; // @synthesize nicknameCell=_nicknameCell;
@property(retain, nonatomic) UIImageView *vehicleIconView; // @synthesize vehicleIconView=_vehicleIconView;
@property(retain, nonatomic) UIView *vehicleColorView; // @synthesize vehicleColorView=_vehicleColorView;
@property(nonatomic) __weak id <VehicleAppearanceViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)pressedDone;	// IMP=0x001000000037b089
- (void)pressedCancel;	// IMP=0x001000000037afef
- (void)_updateContent;	// IMP=0x001000000037ac5f
- (void)textFieldDidEndEditing:(id)arg1;	// IMP=0x001000000037ac11
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;	// IMP=0x001000000037ab73
- (_Bool)textFieldShouldReturn:(id)arg1;	// IMP=0x001000000037ab5b
- (void)textFieldDidBeginEditing:(id)arg1;	// IMP=0x001000000037ab0a
- (id)_selectedColor;	// IMP=0x001000000037aa7c
- (void)colorPicker:(id)arg1 didSelectIndex:(unsigned long long)arg2;	// IMP=0x001000000037aa4b
- (void)viewDidLayoutSubviews;	// IMP=0x001000000037a843
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x001000000037a799
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x001000000037a6a9
- (void)viewDidLoad;	// IMP=0x001000000037944b
@property(nonatomic) unsigned long long selectedIndex;
- (id)initWithColors:(id)arg1 vehicle:(id)arg2 delegate:(id)arg3 allowsEditingNickname:(_Bool)arg4;	// IMP=0x00100000003789d5

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

