//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewCell.h>

@class LSApplicationRecord, UIButton, UIImageView, UILabel;

@interface VehicleAppCell : UITableViewCell
{
    LSApplicationRecord *_applicationRecord;	// 8 = 0x8
    UIButton *_openButton;	// 16 = 0x10
    UIImageView *_appIconView;	// 24 = 0x18
    UILabel *_appNameLabel;	// 32 = 0x20
    UILabel *_appDescriptionLabel;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000005e6df5
@property(retain, nonatomic) UILabel *appDescriptionLabel; // @synthesize appDescriptionLabel=_appDescriptionLabel;
@property(retain, nonatomic) UILabel *appNameLabel; // @synthesize appNameLabel=_appNameLabel;
@property(retain, nonatomic) UIImageView *appIconView; // @synthesize appIconView=_appIconView;
@property(readonly, nonatomic) UIButton *openButton; // @synthesize openButton=_openButton;
@property(retain, nonatomic) LSApplicationRecord *applicationRecord; // @synthesize applicationRecord=_applicationRecord;
- (double)cellHeight;	// IMP=0x00100000005e6d56
- (void)layoutSubviews;	// IMP=0x00100000005e6a98
- (void)_commonInit;	// IMP=0x00100000005e5e7e
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00100000005e5e14
- (id)init;	// IMP=0x00100000005e5dfe

@end

