//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC18SharingViewService21B389MapViewController : UIViewController
{
    MISSING_TYPE *mapAnnotation;	// 8 = 0x8
    MISSING_TYPE *tapHandler;	// 16 = 0x10
    MISSING_TYPE *mapView;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00400000000fc9b0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00100000000fc930
- (void)viewTapped:(id)arg1;	// IMP=0x00100000000fc890
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00100000000fc7f0
- (void)loadView;	// IMP=0x00100000000fc7c0
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000000fc550

@end

