//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, PUConnection, _HKWheelchairUseCharacteristicCache;

@interface COSGeneralSettingsController
{
    PUConnection *_unlockConnection;	// 192 = 0xc0
    _Bool _logsAreDumping;	// 200 = 0xc8
    _HKWheelchairUseCharacteristicCache *_wheelchairUseCharacteristicCache;	// 208 = 0xd0
    _Bool _alwaysInstall;	// 216 = 0xd8
}

+ (id)_displayNamesForLanguageIDs:(id)arg1;	// IMP=0x002000000012f946
+ (id)_localizedListForLanguageCodes:(id)arg1 andLanguageMapping:(id)arg2;	// IMP=0x001000000012f704
+ (id)_footerTextForAutoPunctuationLanguages:(id)arg1 withLanguageMapping:(id)arg2;	// IMP=0x001000000012f5aa
+ (id)_pendingLanguagesFooterTextForWaitingLanguages:(id)arg1 installingLanguages:(id)arg2 andLanguageMapping:(id)arg3;	// IMP=0x001000000012f347
+ (id)_dictationPrivacyTextWithUnsupportedLanguages:(id)arg1 supportedInstalledLanguages:(id)arg2 supportedWaitingLanguages:(id)arg3 supportedInstallingLanguages:(id)arg4 andLanguageMapping:(id)arg5;	// IMP=0x001000000012ed78
+ (id)_dictationAutoPunctuationSupportedLanguages;	// IMP=0x001000000012e95d
+ (id)_enabledDictationLanguageCodes;	// IMP=0x001000000012e88f
- (void).cxx_destruct;	// IMP=0x002000000012fe3f
@property(nonatomic) _Bool alwaysInstall; // @synthesize alwaysInstall=_alwaysInstall;
- (void)wheelchairUseCharacteristicCache:(id)arg1 wheelchairUsageDidChange:(_Bool)arg2;	// IMP=0x001000000012fe0d
- (void)presentPrivacySheet:(id)arg1;	// IMP=0x001000000012e828
- (void)_prepareDictationFooterForSpecifier:(id)arg1;	// IMP=0x001000000012de5e
- (void)assistantPreferencesDidChange:(id)arg1;	// IMP=0x001000000012de4c
- (void)setDictationAutoPunctuationEnabled:(id)arg1;	// IMP=0x001000000012ddea
- (id)dictationAutoPunctuationEnabled;	// IMP=0x001000000012dd82
- (void)setDictationEnabled:(id)arg1;	// IMP=0x001000000012d8f0
- (id)dictationEnabled;	// IMP=0x001000000012d7d4
- (_Bool)reloadingSpecifiersUpdatesSearchModel;	// IMP=0x001000000012d7cc
- (void)versionOrCapabilitiesChanged:(id)arg1;	// IMP=0x001000000012d7ba
- (void)setAutomaticDownloadsEnabled:(id)arg1 specifier:(id)arg2;	// IMP=0x001000000012d6fd
- (id)automaticDownloadsEnabled:(id)arg1;	// IMP=0x001000000012d6d6
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;	// IMP=0x001000000012d6c4
- (void)_gotAutomaticAppInstallState:(_Bool)arg1;	// IMP=0x001000000012d6a1
- (void)handleURL:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000012d63b
- (id)getGizmoWristChoice:(id)arg1;	// IMP=0x001000000012d622
- (void)refreshSoftwareUpdateBadge:(id)arg1;	// IMP=0x001000000012d610
- (void)dumpLogs:(id)arg1;	// IMP=0x001000000012d465
- (_Bool)allowLogCollection;	// IMP=0x001000000012d3fd
- (id)specifiers;	// IMP=0x001000000012cd00
- (void)dealloc;	// IMP=0x001000000012cc3e
- (id)init;	// IMP=0x001000000012c6f1

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

