//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSString, UILabel, UIScrollView, UIView;

@interface COSHeadphoneNotificationsController : UIViewController
{
    UIScrollView *_scrollView;	// 8 = 0x8
    UILabel *_titleLabel;	// 16 = 0x10
    UIView *_descriptionView;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000004c9c1
@property(retain, nonatomic) UIView *descriptionView; // @synthesize descriptionView=_descriptionView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3 interaction:(long long)arg4;	// IMP=0x001000000004c860
- (id)createDescriptionTextView;	// IMP=0x001000000004c73a
- (id)createTitleLabel;	// IMP=0x001000000004c651
- (id)createScrollView;	// IMP=0x001000000004c512
- (id)descriptionText;	// IMP=0x001000000004c1bc
- (void)removeUnderlineStyle:(id)arg1 toRange:(struct _NSRange)arg2;	// IMP=0x001000000004c190
- (void)applyBoldStyle:(id)arg1 toTextMatching:(id)arg2;	// IMP=0x001000000004c038
- (void)applyBodyStyle:(id)arg1 toRange:(struct _NSRange)arg2;	// IMP=0x001000000004bf26
- (id)healthLinkText;	// IMP=0x001000000004be7a
- (id)bluetoothSettingsLinkText;	// IMP=0x001000000004bdce
- (id)linkText:(id)arg1 withLink:(id)arg2;	// IMP=0x001000000004bc1b
- (id)titleText;	// IMP=0x001000000004bbaf
- (void)viewDidLoad;	// IMP=0x001000000004b39e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

