//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class COSBuddyWatchDiscoveryMonitor, COSSatellitePairingHelper, NSString, UIActivityIndicatorView;

@interface COSPairingTypeSelectionViewController
{
    COSSatellitePairingHelper *_satellitePairingHelper;	// 8 = 0x8
    UIActivityIndicatorView *_spinner;	// 16 = 0x10
    COSBuddyWatchDiscoveryMonitor *_buddyWatchDiscoveryMonitor;	// 24 = 0x18
}

+ (_Bool)controllerNeedsToRun;	// IMP=0x00200000000cb7f4
- (void).cxx_destruct;	// IMP=0x00200000000ccfaf
@property(retain, nonatomic) COSBuddyWatchDiscoveryMonitor *buddyWatchDiscoveryMonitor; // @synthesize buddyWatchDiscoveryMonitor=_buddyWatchDiscoveryMonitor;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) COSSatellitePairingHelper *satellitePairingHelper; // @synthesize satellitePairingHelper=_satellitePairingHelper;
- (void)discoveryOperationComplete;	// IMP=0x00100000000ccef4
- (void)applyConfirmedOptinAndCheckMaxDeviceCount:(_Bool)arg1;	// IMP=0x00100000000cc85d
- (id)alternateButtonTitle;	// IMP=0x00100000000cc7f1
- (id)suggestedButtonTitle;	// IMP=0x00100000000cc785
- (void)applyConfirmedOptin:(_Bool)arg1;	// IMP=0x00100000000cc330
- (void)alternateButtonPressed:(id)arg1;	// IMP=0x00100000000cc31c
- (void)suggestedButtonPressed:(id)arg1;	// IMP=0x00100000000cc305
- (id)learnMoreButtonTitle;	// IMP=0x00100000000cc2fd
- (id)captionText;	// IMP=0x00100000000cc272
- (id)detailString;	// IMP=0x00100000000cc1d0
- (id)titleString;	// IMP=0x00100000000cc12e
- (void)dismissSetupFlow:(id)arg1;	// IMP=0x00100000000cc0e9
- (void)viewDidLoad;	// IMP=0x00100000000cbaf3
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00100000000cb9d0
- (void)didEstablishHold;	// IMP=0x00100000000cb984
- (_Bool)holdWithWaitScreen;	// IMP=0x00100000000cb97c
- (_Bool)holdBeforeDisplaying;	// IMP=0x00100000000cb974
- (id)init;	// IMP=0x00100000000cb86a
- (_Bool)requiresActivationCheck;	// IMP=0x00100000000cb7ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

