//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface COSPasscodeInputViewController
{
}

- (_Bool)isComplex;	// IMP=0x00200000000c7b9e
- (id)detailText;	// IMP=0x00100000000c7b0e
- (id)titleText;	// IMP=0x00100000000c7a7e
- (void)back:(id)arg1;	// IMP=0x00100000000c7a78
- (_Bool)controllerAllowsNavigatingBackTo;	// IMP=0x00100000000c79e8
- (void)viewDidLoad;	// IMP=0x00100000000c782c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

