//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface COSSettingsContactTransparencyViewController
{
}

+ (void)recordUserTransparencyPresentation;	// IMP=0x004000000001c22f
+ (_Bool)controllerNeedsToRun;	// IMP=0x001000000001bc81
- (id)suggestedButtonTitle;	// IMP=0x004000000001c33d
- (void)alternateButtonPressed:(id)arg1;	// IMP=0x001000000001c229
- (id)alternateButtonTitle;	// IMP=0x001000000001c1bd
- (void)suggestedButtonPressed:(id)arg1;	// IMP=0x001000000001c11a
- (id)imageResource;	// IMP=0x001000000001c10d
- (id)detailString;	// IMP=0x001000000001c0a1
- (id)titleString;	// IMP=0x001000000001c035
- (id)init;	// IMP=0x001000000001bfe4

@end

