//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FBSDisplayIdentity, FBSDisplayLayoutMonitor, NSSet;

@interface DRLayoutMonitor : NSObject
{
    FBSDisplayIdentity *_displayIdentity;	// 8 = 0x8
    NSSet *_sceneIdentifiers;	// 16 = 0x10
    FBSDisplayLayoutMonitor *_displayLayoutMonitor;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000000c1e2
@property(retain, nonatomic) FBSDisplayLayoutMonitor *displayLayoutMonitor; // @synthesize displayLayoutMonitor=_displayLayoutMonitor;
@property(retain, nonatomic) NSSet *sceneIdentifiers; // @synthesize sceneIdentifiers=_sceneIdentifiers;
@property(readonly, nonatomic) FBSDisplayIdentity *displayIdentity; // @synthesize displayIdentity=_displayIdentity;
- (void)dealloc;	// IMP=0x001000000000c160
- (void)updateSceneIdentifiersWithLayout:(id)arg1;	// IMP=0x001000000000bf3a
- (_Bool)containsSceneIdentifier:(id)arg1;	// IMP=0x001000000000bec3
- (id)initWithDisplayIdentity:(id)arg1;	// IMP=0x001000000000bc7e

@end

