//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSDictionary;

@interface VCPLibraryProcessingTask : NSObject
{
    struct atomic<bool> _cancel;	// 8 = 0x8
    struct atomic<bool> _started;	// 9 = 0x9
    NSArray *_photoLibraries;	// 16 = 0x10
    NSDictionary *_options;	// 24 = 0x18
    CDUnknownBlockType _progressHandler;	// 32 = 0x20
    CDUnknownBlockType _completionHandler;	// 40 = 0x28
    CDUnknownBlockType _cancelBlock;	// 48 = 0x30
}

+ (id)taskWithPhotoLibraries:(id)arg1 andOptions:(id)arg2 andProgressHandler:(CDUnknownBlockType)arg3 andCompletionHandler:(CDUnknownBlockType)arg4 andCancelBlock:(CDUnknownBlockType)arg5;	// IMP=0x0020000000090f2d
- (void).cxx_destruct;	// IMP=0x0020000000092461
- (_Bool)autoCancellable;	// IMP=0x0010000000092459
- (int)run;	// IMP=0x0010000000091516
- (id)createTaskBacklogForPhotoLibrary:(id)arg1 withDatabase:(id)arg2;	// IMP=0x00100000000910e8
- (_Bool)isCancelled;	// IMP=0x00100000000910c4
- (void)cancel;	// IMP=0x00100000000910b9
- (MISSING_TYPE *)resourceRequirement;	// IMP=0x00100000000910ab
- (void)dealloc;	// IMP=0x0010000000091020
- (id)initWithPhotoLibraries:(id)arg1 andOptions:(id)arg2 andProgressHandler:(CDUnknownBlockType)arg3 andCompletionHandler:(CDUnknownBlockType)arg4 andCancelBlock:(CDUnknownBlockType)arg5;	// IMP=0x0010000000090dbe
- (id)init;	// IMP=0x0010000000090db0

@end

