//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC8Freeform23CRLAnalyticsFeatureUsed : NSObject
{
}

+ (void)logFeatureUsedWithName:(long long)arg1;	// IMP=0x0020000000a52ce0
+ (id)featurePayloadFor:(long long)arg1;	// IMP=0x0010000000a52c90
- (void).cxx_destruct;	// IMP=0x0040000000a52e40
- (id)init;	// IMP=0x0010000000a52de0

@end

