//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC8Freeform17CRLBoardChangeSet : _TtCs12_SwiftObject
{
    MISSING_TYPE *boardIdentifier;	// 544 = 0x220
    MISSING_TYPE *rootContainerUUID;	// 17122152 = 0x1054368
    MISSING_TYPE *accessQueue;	// 0 = 0x0
    MISSING_TYPE *lockCounter;	// 0 = 0x0
    MISSING_TYPE *processingQueue;	// 0 = 0x0
    MISSING_TYPE *boardAuxiliaryChanges;	// 0 = 0x0
    MISSING_TYPE *addedItemDatas;	// 0 = 0x0
    MISSING_TYPE *modifiedItemDatas;	// 0 = 0x0
    MISSING_TYPE *snapshots;	// 2004049759 = 0x77735f5f
    MISSING_TYPE *removedItemDatas;	// 1701866847 = 0x65706d5f
    MISSING_TYPE *removedNewlyCreatedItemIds;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *removedFreehandItemIDsSubset;	// 0 = 0x0
    MISSING_TYPE *removedAsOrphanItemIDs;	// 17122696 = 0x1054588
    MISSING_TYPE *uncommittedChangeAvailablePublisher;	// 284 = 0x11c
    MISSING_TYPE *realTimePeerCreatedItemIds;	// 17122696 = 0x1054588
    MISSING_TYPE *realTimePeerDeletedItemIds;	// 0 = 0x0
}

@end

