//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CRLAssertionHandler : NSObject
{
}

+ (int)_atomicIncrementAssertCount;	// IMP=0x002000000021550b
+ (void)handleFailureInFunction:(id)arg1 file:(id)arg2 lineNumber:(long long)arg3 isFatal:(_Bool)arg4 description:(const char *)arg5;	// IMP=0x00100000002153ce
+ (void)handleFailureInFunction:(id)arg1 file:(id)arg2 lineNumber:(long long)arg3 isFatal:(_Bool)arg4 format:(id)arg5 args:(struct __va_list_tag [1])arg6;	// IMP=0x0010000000215150
+ (void)simulateCrashWithMessage:(id)arg1;	// IMP=0x001000000021514a
+ (id)packedBacktraceStringWithReturnAddresses:(id)arg1;	// IMP=0x001000000021464b
+ (id)packedBacktraceString;	// IMP=0x00100000002145e5
+ (void)_logBacktraceWithCallStackSymbols:(id)arg1;	// IMP=0x001000000021452b
+ (void)logFullBacktrace;	// IMP=0x0010000000214492
+ (id)p_performBlockIgnoringAssertions:(CDUnknownBlockType)arg1 onlyFatal:(_Bool)arg2;	// IMP=0x001000000021416c
+ (_Bool)isQAFatalAssertionsEnabled;	// IMP=0x0010000000214164
+ (id)performBlockIgnoringQAFatalAssertions:(CDUnknownBlockType)arg1;	// IMP=0x00100000002140d1
+ (id)performBlockIgnoringFatalAssertions:(CDUnknownBlockType)arg1;	// IMP=0x001000000021407c
+ (id)performBlockIgnoringAssertionsAndReturnList:(CDUnknownBlockType)arg1;	// IMP=0x0010000000214068
+ (id)performBlockIgnoringAssertions:(CDUnknownBlockType)arg1;	// IMP=0x0010000000214016
+ (void)initialize;	// IMP=0x0010000000214010

@end

