//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CRLCanvasAutoscroll, CRLCanvasHUDController, CRLCanvasRep, CRLCanvasShapeRenderable, NSArray, NSMapTable, NSMutableSet, NSString, UIImpactFeedbackGenerator;

@interface CRLCanvasRepDragTracker : NSObject
{
    CRLCanvasRep *mRep;	// 8 = 0x8
    _Bool mDidBeginDrag;	// 16 = 0x10
    _Bool mHaveShownHUD;	// 17 = 0x11
    _Bool mHaveShownSecondHUD;	// 18 = 0x12
    _Bool mDidDuplicateWhenDragBegan;	// 19 = 0x13
    _Bool mIsInspectorDrivenTracking;	// 20 = 0x14
    _Bool mIsDragInsertDrivenTracking;	// 21 = 0x15
    _Bool mIsArrowkeyDrivenTracking;	// 22 = 0x16
    struct CGPoint mInitialDragPoint;	// 24 = 0x18
    struct CGPoint mActualDragPoint;	// 40 = 0x28
    _Bool mHaveSetPreviousActualDragPoint;	// 56 = 0x38
    struct CGPoint mPreviousActualDragPoint;	// 64 = 0x40
    struct CGPoint mLogicalDragPoint;	// 80 = 0x50
    CRLCanvasHUDController *mSecondHUDController;	// 96 = 0x60
    struct CGPoint mUnscaledDragDelta;	// 104 = 0x68
    _Bool mRoundDragDelta;	// 120 = 0x78
    CRLCanvasAutoscroll *mAutoscroll;	// 128 = 0x80
    struct CGPoint mAutoscrollPoint;	// 136 = 0x88
    NSMapTable *mMapRepsToSnapOffsets;	// 152 = 0x98
    _Bool mShouldConstrain;	// 160 = 0xa0
    double mSnapLevel;	// 168 = 0xa8
    double mConstraintAngle;	// 176 = 0xb0
    struct CGPoint mConstrainingPoint;	// 184 = 0xb8
    _Bool mConstraintGuidesShowing;	// 200 = 0xc8
    CRLCanvasShapeRenderable *mGuideRenderable;	// 208 = 0xd0
    _Bool mShouldShowGuides;	// 216 = 0xd8
    _Bool mShouldSnapToGuides;	// 217 = 0xd9
    _Bool mPreventOpeningCommandGroupWhenCommittingChangesForReps;	// 218 = 0xda
    NSMutableSet *mConnectedLineLayouts;	// 224 = 0xe0
    NSMutableSet *mParentLayoutsForInvalidatingForAncestorCollabCursors;	// 232 = 0xe8
    _Bool mShowDragHUD;	// 240 = 0xf0
    _Bool mTrackerDidBeginDragging;	// 241 = 0xf1
    UIImpactFeedbackGenerator *mImpactFeedbackGenerator;	// 248 = 0xf8
    _Bool mIsEnqueueingCommandsInRealTime;	// 256 = 0x100
    _Bool mShouldSuppressConstrainingHUD;	// 257 = 0x101
}

- (void).cxx_destruct;	// IMP=0x002000000059d3e4
@property(nonatomic) _Bool isArrowkeyDrivenTracking; // @synthesize isArrowkeyDrivenTracking=mIsArrowkeyDrivenTracking;
@property(retain, nonatomic) CRLCanvasRep *rep; // @synthesize rep=mRep;
@property(nonatomic) _Bool isInspectorDrivenTracking; // @synthesize isInspectorDrivenTracking=mIsInspectorDrivenTracking;
@property(nonatomic) _Bool shouldSnapToGuides; // @synthesize shouldSnapToGuides=mShouldSnapToGuides;
@property(nonatomic) _Bool shouldShowGuides; // @synthesize shouldShowGuides=mShouldShowGuides;
@property(nonatomic) _Bool showDragHUD; // @synthesize showDragHUD=mShowDragHUD;
@property(nonatomic) _Bool isDragInsertDrivenTracking; // @synthesize isDragInsertDrivenTracking=mIsDragInsertDrivenTracking;
@property(readonly, nonatomic) _Bool didBeginDrag; // @synthesize didBeginDrag=mDidBeginDrag;
@property(nonatomic) _Bool shouldSuppressConstrainingHUD; // @synthesize shouldSuppressConstrainingHUD=mShouldSuppressConstrainingHUD;
@property(readonly, nonatomic) _Bool isEnqueueingCommandsInRealTime; // @synthesize isEnqueueingCommandsInRealTime=mIsEnqueueingCommandsInRealTime;
- (id)p_repsForInfos:(id)arg1 fromReps:(id)arg2;	// IMP=0x001000000059d0fe
- (id)p_infosFromReps:(id)arg1;	// IMP=0x001000000059cf30
- (_Bool)p_delegateIsHandlingDrag;	// IMP=0x001000000059cf28
- (void)p_hideGuideRenderable;	// IMP=0x001000000059cefa
- (void)p_showGuideRenderable;	// IMP=0x001000000059cef4
- (struct CGRect)p_selectedInfosRect;	// IMP=0x001000000059cc7b
- (void)p_updateGuides;	// IMP=0x001000000059cbce
- (void)p_hideHUD;	// IMP=0x001000000059cb48
- (void)p_updateHUDAtPoint:(struct CGPoint)arg1;	// IMP=0x001000000059c4e4
- (void)p_updateHUDFromTimer;	// IMP=0x001000000059c4c8
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;	// IMP=0x001000000059c4af
- (_Bool)allowsDelegateToDisplayUIForDragOperation;	// IMP=0x001000000059c4a7
@property(readonly, nonatomic) NSArray *decoratorOverlayRenderables;
- (_Bool)traceIfDesiredForEndOperation;	// IMP=0x001000000059c281
- (_Bool)traceIfDesiredForBeginOperation;	// IMP=0x001000000059c1e3
- (_Bool)allowPopoverToRemainOpenDuringDynamicOperation;	// IMP=0x001000000059c1d1
- (void)didChangeCurrentlyTransformingReps;	// IMP=0x001000000059b819
- (_Bool)operationShouldBeDynamic;	// IMP=0x001000000059b811
- (_Bool)supportsAlignmentGuides;	// IMP=0x001000000059b7da
- (id)repsForGuidesWhenManipulatingReps:(id)arg1;	// IMP=0x001000000059b7bd
- (void)didEndDynamicOperationForReps:(id)arg1;	// IMP=0x001000000059b7ab
- (void)commitChangesForReps:(id)arg1;	// IMP=0x001000000059b45a
- (_Bool)shouldOpenCommandGroupToCommitChangesForReps:(id)arg1;	// IMP=0x001000000059b431
- (void)changeDynamicLayoutsForReps:(id)arg1;	// IMP=0x0010000000599298
- (void)willBeginDynamicOperationForReps:(id)arg1;	// IMP=0x00100000005991a6
@property(readonly, nonatomic) _Bool objectsWillBeCopiedAtDropTimeIfAppropriate;
- (void)p_didBeginDrag;	// IMP=0x0010000000599149
- (void);	// IMP=0x001000000059913c
- (void)setConstrainingPoint:(struct CGPoint)arg1;	// IMP=0x0010000000599126
- (void)setSnapLevel:(double)arg1;	// IMP=0x0010000000598f20
- (void)setShouldConstrain:(_Bool)arg1;	// IMP=0x0010000000598eda
- (void)setLogicalDragPoint:(struct CGPoint)arg1;	// IMP=0x0010000000598eca
- (void)setActualDragPoint:(struct CGPoint)arg1;	// IMP=0x0010000000598e4e
- (void)addUnscaledDragDelta:(struct CGPoint)arg1 roundDeltaToViewScale:(_Bool)arg2;	// IMP=0x0010000000598e1c
- (_Bool)insertInfosAndUpdateDragForDuplicatingDragIfAppropriate;	// IMP=0x00100000005982c1
- (void)endPossibleRepDragGesture;	// IMP=0x0010000000598209
- (void)willEndPossibleRepDragGesture;	// IMP=0x0010000000598203
- (void)beginShowingDragUIForInitialDragPoint:(struct CGPoint)arg1;	// IMP=0x0010000000597edf
- (void)activateUIFeedback;	// IMP=0x0010000000597ec6
- (void)dealloc;	// IMP=0x0010000000597e47
- (id)initWithRep:(id)arg1;	// IMP=0x0010000000597b78

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool disallowAllActionsWhileTracking;
@property(readonly, nonatomic) _Bool disallowCanvasGrowingWhileTracking;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

