//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CRLConnectionLinePathSourceAccessibility
{
}

+ (Class)crlaxBaseSafeCategoryClass;	// IMP=0x002000000034931e
+ (id)crlaxTargetClassName;	// IMP=0x0010000000349311
+ (id)crlaxCastFrom:(id)arg1;	// IMP=0x0010000000349338
- (id)_crlaxInferredLabel;	// IMP=0x0010000000349389
- (id)crlaxTarget;	// IMP=0x001000000034932f

@end

