//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CRLCanvasRep, CRLCanvasShapeRenderable, CRLInteractiveCanvasController, MISSING_TYPE, NSArray, NSMapTable, NSSet, NSString;

@interface CRLCanvasRepFreeTransformTracker : NSObject
{
    CRLInteractiveCanvasController *mICC;	// 8 = 0x8
    NSSet *mReps;	// 16 = 0x10
    struct CGPoint mPivotPoint;	// 24 = 0x18
    NSMapTable *mLayoutToSelectedRepMap;	// 40 = 0x28
    _Bool mStartedFreeTransform;	// 48 = 0x30
    _Bool mIgnoreDetents;	// 49 = 0x31
    _Bool mStartedDragging;	// 50 = 0x32
    struct CGPoint mUnscaledDrag;	// 56 = 0x38
    struct CGPoint mUnscaledDragDelta;	// 72 = 0x48
    struct CGPoint mUnscaledDragDetent;	// 88 = 0x58
    _Bool mShouldRenderInX;	// 104 = 0x68
    _Bool mShouldRenderInY;	// 105 = 0x69
    struct CGPoint mPreviousDragSnapDiff;	// 112 = 0x70
    struct CGRect mAlignmentRect;	// 128 = 0x80
    _Bool mStartedRotation;	// 160 = 0xa0
    double mOriginalAngleInDegrees;	// 168 = 0xa8
    double mRotateDeltaInRadians;	// 176 = 0xb0
    double mCurrentAngleInDegrees;	// 184 = 0xb8
    _Bool mRotationSnapped;	// 192 = 0xc0
    double mRotationDetent;	// 200 = 0xc8
    double mRotationInitialDetentThreshold;	// 208 = 0xd0
    double mRotationDetentThreshold;	// 216 = 0xd8
    CRLCanvasShapeRenderable *mGuideRenderable;	// 224 = 0xe0
    _Bool mStartedMagnification;	// 232 = 0xe8
    double mMagnificationStartOffset;	// 240 = 0xf0
    double mMagnifyBy;	// 248 = 0xf8
    struct CGRect mBaseBounds;	// 256 = 0x100
    struct CGSize mMinimumSize;	// 288 = 0x120
    _Bool mIsEnqueueingCommandsInRealTime;	// 304 = 0x130
    CRLCanvasRep *_rep;	// 312 = 0x138
}

- (void).cxx_destruct;	// IMP=0x00200000001cb73e
@property(readonly, nonatomic) CRLCanvasRep *rep; // @synthesize rep=_rep;
@property(readonly, nonatomic) _Bool isEnqueueingCommandsInRealTime; // @synthesize isEnqueueingCommandsInRealTime=mIsEnqueueingCommandsInRealTime;
@property(nonatomic) double rotationDetentThreshold; // @synthesize rotationDetentThreshold=mRotationDetentThreshold;
@property(nonatomic) double rotationInitialDetentThreshold; // @synthesize rotationInitialDetentThreshold=mRotationInitialDetentThreshold;
- (void)p_updateDragSnap;	// IMP=0x00100000001cb364
- (void)p_hideGuideRenderable;	// IMP=0x00100000001cb225
- (void)p_updateGuideRenderableWithAngle:(double)arg1 didSnap:(_Bool)arg2;	// IMP=0x00100000001cadd3
- (struct CGAffineTransform)p_translationTransform;	// IMP=0x00100000001cada7
- (struct CGPoint)p_scaledCenterForRotation;	// IMP=0x00100000001cad84
- (void)p_updateCenterForRotationIfNecessary;	// IMP=0x00100000001caba8
- (struct CGPoint)p_centerForRotationForRep:(id)arg1 inUnscaledBoundingRect:(struct CGRect)arg2;	// IMP=0x00100000001caa86
- (struct CGRect)p_unscaledBoundingRectForReps:(id)arg1;	// IMP=0x00100000001ca7eb
- (void)p_begin;	// IMP=0x00100000001ca60f
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;	// IMP=0x00100000001ca5b6
- (MISSING_TYPE *)actionForLayer:forKey: /* Error: Ran out of types for this method. */;	// IMP=0x00100000001ca59d
@property(readonly, nonatomic) NSArray *decoratorOverlayRenderables;
- (_Bool)traceIfDesiredForEndOperation;	// IMP=0x00100000001ca43c
- (_Bool)traceIfDesiredForBeginOperation;	// IMP=0x00100000001ca399
- (_Bool)operationShouldBeDynamic;	// IMP=0x00100000001ca391
- (_Bool)supportsAlignmentGuides;	// IMP=0x00100000001ca389
- (void)commitChangesForReps:(id)arg1;	// IMP=0x00100000001c9f92
- (_Bool)shouldOpenCommandGroupToCommitChangesForReps:(id)arg1;	// IMP=0x00100000001c9f8a
- (void)applyNewBoundsToRep:(id)arg1;	// IMP=0x00100000001c9b59
- (struct CGAffineTransform)freeTransformForLayout:(id)arg1;	// IMP=0x00100000001c99e0
- (struct CGAffineTransform)resizeTransformForLayout:(id)arg1;	// IMP=0x00100000001c9585
- (struct CGAffineTransform)rotateTransform;	// IMP=0x00100000001c9464
- (void)changeDynamicLayoutsForReps:(id)arg1;	// IMP=0x00100000001c8d71
- (void)willBeginDynamicOperationForReps:(id)arg1;	// IMP=0x00100000001c8c06
- (id)currentGeometryForLayout:(id)arg1;	// IMP=0x00100000001c85f8
- (id)selectedRepForLayout:(id)arg1;	// IMP=0x00100000001c8167
- (struct CGSize)currentSizeForLayout:(id)arg1;	// IMP=0x00100000001c8105
- (void)setMagnification:(double)arg1;	// IMP=0x00100000001c8053
- (void)addRotateDelta:(double)arg1;	// IMP=0x00100000001c8039
- (void)addUnscaledDragDelta:(struct CGPoint)arg1;	// IMP=0x00100000001c7f5a
- (void)dealloc;	// IMP=0x00100000001c7f13
- (id)initWithReps:(id)arg1;	// IMP=0x00100000001c7781

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool disallowAllActionsWhileTracking;
@property(readonly, nonatomic) _Bool disallowCanvasGrowingWhileTracking;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

