//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CRLCanvasPlaceholderInvisibleKnob
{
}

- (id)renderable;	// IMP=0x004000000007bd91
- (_Bool)isHitByUnscaledPoint:(struct CGPoint)arg1 inputType:(long long)arg2 returningDistance:(double *)arg3;	// IMP=0x001000000007bd89

@end

