//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CRLDropShadow
{
}

- (struct CGImage *)newShadowImageForRep:(id)arg1 withSize:(struct CGSize)arg2 drawSelector:(SEL)arg3 unflipped:(_Bool)arg4;	// IMP=0x00400000002e010d
- (struct CGRect)boundsForRep:(id)arg1;	// IMP=0x00100000002e00b2
- (struct CGRect)boundsInNaturalSpaceForRep:(id)arg1;	// IMP=0x00100000002e0057
- (id)newShadowClampedForSwatches;	// IMP=0x00100000002dff2e
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000002dfe56
- (id);	// IMP=0x00100000002dfe4b
- (unsigned long long)hash;	// IMP=0x00100000002dfe1c
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000002dfd87
- (unsigned long long)shadowType;	// IMP=0x00100000002dfd7c
- (id)initWithAngle:(double)arg1 offset:(double)arg2 radius:(double)arg3 opacity:(double)arg4 color:(id)arg5 enabled:(_Bool)arg6;	// IMP=0x00100000002dfd3e

@end

