//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol CRLDisplayLinkPlatformAdapter;

@interface CRLDisplayLinkManager : NSObject
{
    NSMutableSet *_registeredLinks;	// 8 = 0x8
    NSMutableSet *_activeLinks;	// 16 = 0x10
    Class _adapterClass;	// 24 = 0x18
    id <CRLDisplayLinkPlatformAdapter> _adapter;	// 32 = 0x20
}

+ (id)sharedManager;	// IMP=0x00400000002bc233
- (void).cxx_destruct;	// IMP=0x00200000002bcab0
- (void)p_linkTriggeredAt:(double)arg1 forTargetTime:(double)arg2;	// IMP=0x00100000002bc963
- (void)p_destroyPlatformAdapter;	// IMP=0x00100000002bc764
- (void)p_createPlatformAdapter;	// IMP=0x00100000002bc553
- (void)p_updateState;	// IMP=0x00100000002bc48e
- (void)updatePausedForLink:(id)arg1;	// IMP=0x00100000002bc41c
- (void)removeLink:(id)arg1;	// IMP=0x00100000002bc3ad
- (void)addLink:(id)arg1;	// IMP=0x00100000002bc336
- (id)init;	// IMP=0x00100000002bc308
- (id)p_initWithPlatformAdapterClass:(Class)arg1;	// IMP=0x00100000002bc288

@end

