//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, _TtC8Freeform21CRLEditingCoordinator;

@interface CRLFindReplaceAllHelper : NSObject
{
    _TtC8Freeform21CRLEditingCoordinator *_editingCoordinator;	// 8 = 0x8
    NSString *_findString;	// 16 = 0x10
    NSString *_replaceString;	// 24 = 0x18
    unsigned long long _options;	// 32 = 0x20
    unsigned long long _countOfItemsReplaced;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000055bf67
@property(readonly, nonatomic) unsigned long long countOfItemsReplaced; // @synthesize countOfItemsReplaced=_countOfItemsReplaced;
@property(readonly, nonatomic) unsigned long long options; // @synthesize options=_options;
@property(readonly, nonatomic) NSString *replaceString; // @synthesize replaceString=_replaceString;
@property(readonly, nonatomic) NSString *findString; // @synthesize findString=_findString;
@property(readonly, nonatomic) __weak _TtC8Freeform21CRLEditingCoordinator *editingCoordinator; // @synthesize editingCoordinator=_editingCoordinator;
- (void)appendReplacementCount:(unsigned long long)arg1;	// IMP=0x001000000055bf1f
- (void)enqueueReplaceAllWithSelectionBehavior:(id)arg1 modelEnumerator:(id)arg2;	// IMP=0x001000000055bc4e
- (void)replaceAllWithSelectionBehavior:(id)arg1 modelEnumerator:(id)arg2;	// IMP=0x001000000055bc3c
- (id)initWithEditingCoordinator:(id)arg1 findString:(id)arg2 replaceString:(id)arg3 options:(unsigned long long)arg4;	// IMP=0x001000000055bb53

@end

