//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSError, NSString, _TtC8Freeform8CRLAsset;

@interface CRLImageCompatibilityChecker : NSObject
{
    _TtC8Freeform8CRLAsset *_imageData;	// 8 = 0x8
    long long _compatibilityLevel;	// 16 = 0x10
    NSError *_error;	// 24 = 0x18
    _Atomic _Bool _cancelled;	// 32 = 0x20
}

+ (void)initialize;	// IMP=0x002000000007f949
- (void).cxx_destruct;	// IMP=0x0020000000080225
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) long long compatibilityLevel; // @synthesize compatibilityLevel=_compatibilityLevel;
@property(readonly, nonatomic, getter=isCancelled) _Bool cancelled;
- (void)cancel;	// IMP=0x00100000000801fb
- (void)checkCompatibilityUpToLevel:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000007fbdc
- (id)initWithImageData:(id)arg1;	// IMP=0x001000000007f9a5

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

