//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, NSMutableArray, NSPointerArray, NSTimer;

@interface CRLiOSKeyboardMonitor : NSObject
{
    _Bool _keyboardIsVisibleAndDocked;	// 8 = 0x8
    _Bool _undockedKeyboardWillShow;	// 9 = 0x9
    _Bool _undockedKeyboardWillHide;	// 10 = 0xa
    _Bool _weAreFakingAHideEvent;	// 11 = 0xb
    _Bool _lastHideWasFake;	// 12 = 0xc
    _Bool _suppressDidHide;	// 13 = 0xd
    _Bool _isLocalKeyboard;	// 14 = 0xe
    _Bool _keyboardIsAnimatingInOrDocking;	// 15 = 0xf
    _Bool _keyboardIsAnimatingOutOrUndocking;	// 16 = 0x10
    double _onScreenHeight;	// 24 = 0x18
    double _keyboardAnimationDuration;	// 32 = 0x20
    NSPointerArray *_keyboardObservers;	// 40 = 0x28
    NSMutableArray *_completionBlocks;	// 48 = 0x30
    NSTimer *_keyboardIsAnimatingInTimer;	// 56 = 0x38
    NSHashTable *_modalKeyboardObservers;	// 64 = 0x40
    struct CGRect _keyboardFrame;	// 72 = 0x48
}

+ (struct CGRect)p_localKeyboardFrameFromReportedFrame:(struct CGRect)arg1 screenBounds:(struct CGRect)arg2 inputView:(id)arg3;	// IMP=0x004000000035e386
+ (_Bool)isNullInputView:(id)arg1;	// IMP=0x001000000035e140
+ (_Bool)isLocalKeyboardForNotification:(id)arg1;	// IMP=0x001000000035defe
+ (void)afterKeyboardAnimationPerformBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000035de8c
+ (_Bool)keyboardIsAnimatingOutOrUndocking;	// IMP=0x001000000035de48
+ (_Bool)keyboardIsAnimatingInOrDocking;	// IMP=0x001000000035de04
+ (_Bool)keyboardIsAnimating;	// IMP=0x001000000035ddc0
+ (_Bool)undockedKeyboardWillHide;	// IMP=0x001000000035dd7c
+ (_Bool)undockedKeyboardWillShow;	// IMP=0x001000000035dd38
+ (_Bool)keyboardIsVisibleAndUndocked;	// IMP=0x001000000035dcf4
+ (_Bool)keyboardIsVisibleAndDocked;	// IMP=0x001000000035dcb0
+ (_Bool)isKeyboardFrameChanging:(id)arg1;	// IMP=0x001000000035d77c
+ (void)removeModalKeyboardObserver:(id)arg1;	// IMP=0x001000000035d70a
+ (void)addModalKeyboardObserver:(id)arg1;	// IMP=0x001000000035d698
+ (void)removeKeyboardObserver:(id)arg1;	// IMP=0x001000000035d626
+ (void)addKeyboardObserver:(id)arg1;	// IMP=0x001000000035d5b4
+ (id)sharedKeyboardMonitor;	// IMP=0x001000000035d55f
- (void).cxx_destruct;	// IMP=0x002000000035f835
@property(readonly, nonatomic) NSHashTable *modalKeyboardObservers; // @synthesize modalKeyboardObservers=_modalKeyboardObservers;
@property(retain, nonatomic) NSTimer *keyboardIsAnimatingInTimer; // @synthesize keyboardIsAnimatingInTimer=_keyboardIsAnimatingInTimer;
@property(readonly, nonatomic) NSMutableArray *completionBlocks; // @synthesize completionBlocks=_completionBlocks;
@property(readonly, nonatomic) NSPointerArray *keyboardObservers; // @synthesize keyboardObservers=_keyboardObservers;
@property(readonly) double keyboardAnimationDuration; // @synthesize keyboardAnimationDuration=_keyboardAnimationDuration;
@property(readonly) struct CGRect keyboardFrame; // @synthesize keyboardFrame=_keyboardFrame;
@property(readonly) double onScreenHeight; // @synthesize onScreenHeight=_onScreenHeight;
@property(readonly) _Bool isLocalKeyboard; // @synthesize isLocalKeyboard=_isLocalKeyboard;
@property(readonly) _Bool undockedKeyboardWillHide; // @synthesize undockedKeyboardWillHide=_undockedKeyboardWillHide;
@property(readonly) _Bool undockedKeyboardWillShow; // @synthesize undockedKeyboardWillShow=_undockedKeyboardWillShow;
@property(readonly) _Bool keyboardIsAnimatingOutOrUndocking; // @synthesize keyboardIsAnimatingOutOrUndocking=_keyboardIsAnimatingOutOrUndocking;
@property(nonatomic) _Bool keyboardIsAnimatingInOrDocking; // @synthesize keyboardIsAnimatingInOrDocking=_keyboardIsAnimatingInOrDocking;
- (void)p_keyboardDidChangeFrame:(id)arg1;	// IMP=0x001000000035f644
- (void)p_keyboardWillChangeFrame:(id)arg1;	// IMP=0x001000000035f519
- (_Bool)p_isNotificationCorrespondingToUndockedKeyboardWillHide:(id)arg1;	// IMP=0x001000000035f316
- (_Bool)p_isNotificationCorrespondingToUndockedKeyboardWillShow:(id)arg1;	// IMP=0x001000000035f0eb
- (double)p_verticalSpacingFromWindow:(id)arg1 toWindow:(id)arg2;	// IMP=0x001000000035ef83
- (double)onScreenHeightInWindow:(id)arg1;	// IMP=0x001000000035edb9
- (_Bool)p_isFrameCorrespondingToRotatedKeyboard:(struct CGRect)arg1;	// IMP=0x001000000035ed11
- (_Bool)p_isFrameCorrespondingToUndockedKeyboard:(struct CGRect)arg1;	// IMP=0x001000000035ea7e
- (void)p_performAnimationCompletionBlocksWithVisible:(_Bool)arg1;	// IMP=0x001000000035e8b8
- (void)p_updateKeyboardInfoFromNotification:(id)arg1;	// IMP=0x001000000035e5e5
- (void)p_installKeyboardNotifications;	// IMP=0x001000000035e4dc
- (void)afterKeyboardAnimationPerformBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000035d501
- (void)removeModalKeyboardObserver:(id)arg1;	// IMP=0x001000000035d48f
- (void)addModalKeyboardObserver:(id)arg1;	// IMP=0x001000000035d234
- (void)removeKeyboardObserver:(id)arg1;	// IMP=0x001000000035d14d
- (void)addKeyboardObserver:(id)arg1;	// IMP=0x001000000035d09e
- (void)p_scheduleKeyboardIsAnimatingInTimer;	// IMP=0x001000000035cd7f
- (void)p_clearKeyboardIsAnimatingInTimer;	// IMP=0x001000000035cd25
- (void)p_keyboardDidHideOrUndock:(id)arg1;	// IMP=0x001000000035cc0c
- (void)p_keyboardWillHideOrUndock:(id)arg1;	// IMP=0x001000000035ca94
- (void)p_keyboardDidShowOrDock:(id)arg1;	// IMP=0x001000000035c948
- (void)p_keyboardWillShowOrDock:(id)arg1;	// IMP=0x001000000035c740
- (id)p_observersToNotify;	// IMP=0x001000000035c343
- (void)p_enumerateObserversUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000035c27c
@property(readonly) _Bool keyboardIsAnimating;
@property(readonly) _Bool keyboardIsVisibleAndUndocked;
@property(readonly) _Bool keyboardIsVisibleAndDocked;
- (id)init;	// IMP=0x001000000035c144

@end

