//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CRLSearch, NSEnumerator, NSMutableArray, NSMutableDictionary, _TtC8Freeform21CRLEditingCoordinator, _TtC8Freeform8CRLBoard;
@protocol CRLFindReplaceDelegate, CRLSearchReference, CRLSearchable;

@interface CRLModelSearchController : NSObject
{
    _Bool _modelSearchesRunSynchronously;	// 8 = 0x8
    id <CRLFindReplaceDelegate> _findReplaceDelegate;	// 16 = 0x10
    _TtC8Freeform21CRLEditingCoordinator *_editingCoordinator;	// 24 = 0x18
    id <CRLSearchReference> _startingPointSearchReference;	// 32 = 0x20
    NSObject<CRLSearchReference> *_primaryFindResultSearchReference;	// 40 = 0x28
    NSEnumerator *_currentModelEnumerator;	// 48 = 0x30
    id <CRLSearchable> _currentSearchable;	// 56 = 0x38
    CRLSearch *_currentSearch;	// 64 = 0x40
    double _currentSearchStartTime;	// 72 = 0x48
    unsigned long long _currentSearchResultsCount;	// 80 = 0x50
    NSMutableArray *_layoutSearchResults;	// 88 = 0x58
    NSMutableDictionary *_layoutSearchCountForRootIndexMap;	// 96 = 0x60
    CDUnknownBlockType _progressBlock;	// 104 = 0x68
    struct _NSRange _currentRootSearchTargetRange;	// 112 = 0x70
}

+ (long long)compareSearchReference:(id)arg1 toSearchReference:(id)arg2;	// IMP=0x0040000000374f0a
+ (_Bool)searchReference:(id)arg1 isAfterSearchReference:(id)arg2 inDirection:(unsigned long long)arg3;	// IMP=0x0010000000374ef5
+ (_Bool)searchReference:(id)arg1 isBeforeSearchReference:(id)arg2 inDirection:(unsigned long long)arg3;	// IMP=0x0010000000374edd
+ (_Bool)p_searchReference:(id)arg1 comparedWithSearchReference:(id)arg2 inDirection:(unsigned long long)arg3 before:(_Bool)arg4;	// IMP=0x0010000000374e89
+ (void)assertSearchTargetImplementsProperMethods:(id)arg1;	// IMP=0x001000000037184c
- (void).cxx_destruct;	// IMP=0x002000000037506d
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(retain, nonatomic) NSMutableDictionary *layoutSearchCountForRootIndexMap; // @synthesize layoutSearchCountForRootIndexMap=_layoutSearchCountForRootIndexMap;
@property(retain, nonatomic) NSMutableArray *layoutSearchResults; // @synthesize layoutSearchResults=_layoutSearchResults;
@property(nonatomic) struct _NSRange currentRootSearchTargetRange; // @synthesize currentRootSearchTargetRange=_currentRootSearchTargetRange;
@property(nonatomic) unsigned long long currentSearchResultsCount; // @synthesize currentSearchResultsCount=_currentSearchResultsCount;
@property(nonatomic) double currentSearchStartTime; // @synthesize currentSearchStartTime=_currentSearchStartTime;
@property(retain, nonatomic) CRLSearch *currentSearch; // @synthesize currentSearch=_currentSearch;
@property(nonatomic) id <CRLSearchable> currentSearchable; // @synthesize currentSearchable=_currentSearchable;
@property(retain, nonatomic) NSEnumerator *currentModelEnumerator; // @synthesize currentModelEnumerator=_currentModelEnumerator;
@property(retain, nonatomic) NSObject<CRLSearchReference> *primaryFindResultSearchReference; // @synthesize primaryFindResultSearchReference=_primaryFindResultSearchReference;
@property(retain, nonatomic) id <CRLSearchReference> startingPointSearchReference; // @synthesize startingPointSearchReference=_startingPointSearchReference;
@property(nonatomic) __weak _TtC8Freeform21CRLEditingCoordinator *editingCoordinator; // @synthesize editingCoordinator=_editingCoordinator;
@property(nonatomic) _Bool modelSearchesRunSynchronously; // @synthesize modelSearchesRunSynchronously=_modelSearchesRunSynchronously;
@property(readonly, nonatomic) __weak id <CRLFindReplaceDelegate> findReplaceDelegate; // @synthesize findReplaceDelegate=_findReplaceDelegate;
- (id)searchReferenceAfterReference:(id)arg1 inDirection:(unsigned long long)arg2;	// IMP=0x00100000003748d0
- (unsigned long long)layoutSearchResultsIndexOfSearchReference:(id)arg1;	// IMP=0x0010000000374859
- (unsigned long long)_resultCountInRootObjectRange:(struct _NSRange)arg1;	// IMP=0x001000000037433a
- (unsigned long long)indexOfVisibleSearchReference:(id)arg1;	// IMP=0x00100000003740d2
- (id)firstVisibleResultInRect:(struct CGRect)arg1;	// IMP=0x0010000000373ec7
- (void)buildVisibleSearchResultsIfNecessary;	// IMP=0x0010000000373dce
- (void)buildSearchResultsIfNecessary;	// IMP=0x0010000000373d02
- (id)_lastResultInDirection:(unsigned long long)arg1;	// IMP=0x0010000000373c3b
- (id)_firstResultInDirection:(unsigned long long)arg1;	// IMP=0x0010000000373b74
- (_Bool)_nextSearchTargetWithMatchInDirection:(unsigned long long)arg1;	// IMP=0x00100000003734d2
- (unsigned long long)_layoutSearchResultsIndexNearestToSearchReference:(id)arg1 inDirection:(unsigned long long)arg2 isOrdredSame:(_Bool *)arg3;	// IMP=0x0010000000373255
- (unsigned long long)nextRootSearchTargetIndexFromIndex:(unsigned long long)arg1 forString:(id)arg2 options:(unsigned long long)arg3 inDirection:(unsigned long long)arg4;	// IMP=0x0010000000373135
- (unsigned long long)nextRootSearchTargetFromIndex:(unsigned long long)arg1 inDirection:(unsigned long long)arg2;	// IMP=0x0010000000372de5
- (void)_buildLayoutSearchResultsForRootSearchTargetsInRange:(struct _NSRange)arg1 resultsArray:(id)arg2;	// IMP=0x001000000037268a
- (unsigned long long)_layoutSearchResultsIndexAtOrAfterSearchReference:(id)arg1 inDirection:(unsigned long long)arg2 isOrdredSame:(_Bool *)arg3;	// IMP=0x00100000003724fc
- (unsigned long long)_layoutSearchResultsIndexAtOrBeforeSearchReference:(id)arg1 inDirection:(unsigned long long)arg2 isOrdredSame:(_Bool *)arg3;	// IMP=0x001000000037236e
- (void)sortLayoutSearchResultsArray:(id)arg1;	// IMP=0x0010000000372342
- (void)performSearchWithSearchTarget:(id)arg1 resultsArray:(id)arg2;	// IMP=0x0010000000371f9b
@property(readonly, nonatomic) unsigned long long findResultIndex;
- (void)invalidateSearchResultsCountPerRootIndexForRange:(struct _NSRange)arg1;	// IMP=0x0010000000371d33
- (void)invalidateSearchResults;	// IMP=0x0010000000371a9b
- (void)startCountingHits;	// IMP=0x0010000000371530
- (id)modelEnumeratorForUserSearch;	// IMP=0x00100000003714d9
- (void)stopCountingHits;	// IMP=0x00100000003712c0
- (void)continueCountingHits;	// IMP=0x0010000000370cf4
- (void)continueSearch;	// IMP=0x0010000000370963
- (id)getNextSearchFromCurrentSearchable;	// IMP=0x00100000003705d2
- (_Bool)respondsToSearch;	// IMP=0x0010000000370241
- (_Bool)searchCriteriaIsValid;	// IMP=0x0010000000370239
@property(readonly, nonatomic) _TtC8Freeform8CRLBoard *board;
@property(readonly, nonatomic) unsigned long long searchResultsCount;
- (void)setSearchProgressBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000003700df
- (id)initWithEditingCoordinator:(id)arg1 delegate:(id)arg2 modelSearchesRunSynchronously:(_Bool)arg3;	// IMP=0x001000000036ffe7
- (id)init;	// IMP=0x001000000036fcff

@end

