//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CRLSelectionModelTranslator : NSObject
{
}

- (_Bool)isSelectionPathUserSelectable:(id)arg1 isInCollaborationMode:(_Bool)arg2;	// IMP=0x00400000003c7eaf
- (id)containerToInsertIntoForSelectionPath:(id)arg1;	// IMP=0x00100000003c7969
- (id)unlockedBoardItemsForSelectionPath:(id)arg1;	// IMP=0x00100000003c78fa
- (id)boardItemsForSelectionPath:(id)arg1;	// IMP=0x00100000003c7827
- (id)selectionPathForNothingSelectedInsideGroup:(id)arg1;	// IMP=0x00100000003c7523
- (id)selectionPathForSelection:(id)arg1 onStorage:(id)arg2;	// IMP=0x00100000003c723d
- (id)selectionPathForRange:(struct _NSRange)arg1 onStorage:(id)arg2 headCursorAffinity:(unsigned long long)arg3 tailCursorAffinity:(unsigned long long)arg4;	// IMP=0x00100000003c6f02
- (id)visualSelectionPathForRange:(struct _NSRange)arg1 onStorage:(id)arg2;	// IMP=0x00100000003c6bdc
- (id)selectionPathForRange:(struct _NSRange)arg1 onStorage:(id)arg2;	// IMP=0x00100000003c68b9
- (id)selectionPathForInfos:(id)arg1;	// IMP=0x00100000003c5804
- (id)infosForSelectionPath:(id)arg1;	// IMP=0x00100000003c5677
- (id)infoForSelectionPath:(id)arg1;	// IMP=0x00100000003c560c

@end

