//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;

@interface CRLWPSpellingResults
{
}

- (struct _NSRange)rangeOfMisspelledWordAtCharIndex:(unsigned long long)arg1;	// IMP=0x00200000003fed6d
- (void)addResult:(id)arg1 forRange:(struct _NSRange)arg2;	// IMP=0x00100000003fed3e

// Remaining properties
@property(readonly, nonatomic) NSArray *results; // @dynamic results;

@end

