//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CRLWPTextMagnifierVerticalRanged
{
}

- (void)drawMagnifierClippedCanvasLayer:(id)arg1 inContext:(struct CGContext *)arg2;	// IMP=0x0040000000093f33
- (_Bool)shouldHideCanvasLayer;	// IMP=0x0010000000093e14
- (id)maskImageName;	// IMP=0x0010000000093e07
- (id)overlayImageName;	// IMP=0x0010000000093dfa
- (id)underlayImageName;	// IMP=0x0010000000093ded
- (void)stopMagnifying:(_Bool)arg1;	// IMP=0x0010000000093d6e
- (void)beginMagnifyingTarget:(id)arg1 magnificationPoint:(struct CGPoint)arg2 offset:(struct CGPoint)arg3 animated:(_Bool)arg4;	// IMP=0x0010000000093c77
- (void)updateFrame;	// IMP=0x0010000000093a67
- (double)currentOffset;	// IMP=0x0010000000093a2a
- (void)zoomRightAnimation;	// IMP=0x0010000000093815
- (void)zoomLeftAnimation;	// IMP=0x0010000000093663
- (id)init;	// IMP=0x0010000000093611

@end

