//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ManagedConfiguration/MCDependencyReader.h>

@class NSMutableDictionary;

@interface MCDependencyManager : MCDependencyReader
{
    NSMutableDictionary *_memberQueueSystemOrphansDict;	// 8 = 0x8
    NSMutableDictionary *_memberQueueUserOrphansDict;	// 16 = 0x10
}

+ (id)sharedManager;	// IMP=0x004000000005cc22
- (void).cxx_destruct;	// IMP=0x002000000005ee75
@property(retain, nonatomic) NSMutableDictionary *memberQueueUserOrphansDict; // @synthesize memberQueueUserOrphansDict=_memberQueueUserOrphansDict;
@property(retain, nonatomic) NSMutableDictionary *memberQueueSystemOrphansDict; // @synthesize memberQueueSystemOrphansDict=_memberQueueSystemOrphansDict;
- (void)removeDependent:(id)arg1 fromParent:(id)arg2 inDomain:(id)arg3 reciprocalDomain:(id)arg4 fromSystem:(_Bool)arg5 user:(_Bool)arg6;	// IMP=0x001000000005ec6a
- (void)removeDependent:(id)arg1 fromParent:(id)arg2 inDomain:(id)arg3 reciprocalDomain:(id)arg4;	// IMP=0x001000000005ec4f
- (void)addDependent:(id)arg1 ofParent:(id)arg2 inDomain:(id)arg3 reciprocalDomain:(id)arg4 toSystem:(_Bool)arg5 user:(_Bool)arg6;	// IMP=0x001000000005ea54
- (void)addDependent:(id)arg1 ofParent:(id)arg2 inDomain:(id)arg3 reciprocalDomain:(id)arg4;	// IMP=0x001000000005ea39
- (void)memberQueueRemoveDependent:(id)arg1 fromParent:(id)arg2 inDomain:(id)arg3 fromSystem:(_Bool)arg4 user:(_Bool)arg5;	// IMP=0x001000000005e632
- (void)memberQueueRemoveDependent:(id)arg1 fromParent:(id)arg2 inDomain:(id)arg3;	// IMP=0x001000000005e60a
- (void)removeDependent:(id)arg1 fromParent:(id)arg2 inDomain:(id)arg3 fromSystem:(_Bool)arg4 user:(_Bool)arg5;	// IMP=0x001000000005e2a0
- (void)removeDependent:(id)arg1 fromParent:(id)arg2 inDomain:(id)arg3;	// IMP=0x001000000005e278
- (void)memberQueueAddDependent:(id)arg1 toParent:(id)arg2 inDomain:(id)arg3 toSystem:(_Bool)arg4 user:(_Bool)arg5;	// IMP=0x001000000005dec8
- (void)memberQueueAddDependent:(id)arg1 toParent:(id)arg2 inDomain:(id)arg3;	// IMP=0x001000000005dea0
- (void)addDependent:(id)arg1 ofParent:(id)arg2 inDomain:(id)arg3 toSystem:(_Bool)arg4 user:(_Bool)arg5;	// IMP=0x001000000005dc8c
- (void)addDependent:(id)arg1 ofParent:(id)arg2 inDomain:(id)arg3;	// IMP=0x001000000005dc64
- (id)memberQueueOrphanedParentsInUserDomain:(id)arg1;	// IMP=0x001000000005dbe1
- (id)memberQueueOrphanedParentsInSystemDomain:(id)arg1;	// IMP=0x001000000005db5e
- (id)orphanedParentsForUserDomain:(id)arg1;	// IMP=0x001000000005d9b8
- (id)orphanedParentsForSystemDomain:(id)arg1;	// IMP=0x001000000005d812
- (id)orphanedParentsForDomain:(id)arg1;	// IMP=0x001000000005d4fb
- (void)memberQueueRemoveOrphanParent:(id)arg1 inDomain:(id)arg2 fromSystem:(_Bool)arg3 user:(_Bool)arg4;	// IMP=0x001000000005d26c
- (void)memberQueueAddOrphanParent:(id)arg1 inDomain:(id)arg2 toSystem:(_Bool)arg3 user:(_Bool)arg4;	// IMP=0x001000000005cfbc
- (void)commitChangesCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000005cd5f
- (void)commitChanges;	// IMP=0x001000000005ccb7
- (id)_init;	// IMP=0x001000000005cc34

@end

