//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CPLPrequeliteSynthesizedVariable
{
}

+ (void)initialize;	// IMP=0x004000000005182d
- (void)setValue:(id)arg1;	// IMP=0x00400000000518f3
- (id)valueWithConstructor:(CDUnknownBlockType)arg1;	// IMP=0x0010000000051852

@end

