//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <EmailDaemon/EDMessagePersistence.h>

@interface EDMessagePersistence (MFDeliveryQueue)
- (void)setMailDropDeliveryState:(long long)arg1 forMessage:(id)arg2;	// IMP=0x001000000003d0b1
- (long long)mailDropDeliveryStateForMessage:(id)arg1;	// IMP=0x001000000003cfd9
- (void)setDeliveryInfo:(id)arg1 forMessage:(id)arg2;	// IMP=0x001000000003cee7
- (id)deliveryInfoForMessage:(id)arg1;	// IMP=0x001000000003cdfe
@end

