//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MCSMailboxOperation;

@interface MailMailboxChangeSet
{
    MCSMailboxOperation *_mailboxOperation;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000003d62d
- (_Bool)allowOtherChange:(id)arg1;	// IMP=0x001000000003d5a3
- (id)URLStrings;	// IMP=0x001000000003d59b
- (id)stores;	// IMP=0x001000000003d593
- (id)accounts;	// IMP=0x001000000003d4ee
- (id)mailboxParentForMove;	// IMP=0x001000000003d4d1
- (id)mailboxToMoveOrRename;	// IMP=0x001000000003d4b4
- (id)mailboxToRemove;	// IMP=0x001000000003d497
- (id)modifiedMailboxName;	// IMP=0x001000000003d47a
- (unsigned long long)adjustUnreadCount:(unsigned long long)arg1 withCriterion:(id)arg2;	// IMP=0x001000000003d471
- (id)copyChangeSetForFullPath:(id)arg1;	// IMP=0x001000000003d469
- (id)description;	// IMP=0x001000000003d3c8
- (long long)localizedChangeDescriptionPriority;	// IMP=0x001000000003d3c0
- (id)localizedChangeDescription;	// IMP=0x001000000003d3b3
- (id)localizedErrorTitle;	// IMP=0x001000000003d396
- (id)localizedErrorDescription;	// IMP=0x001000000003d379
- (_Bool)revert;	// IMP=0x001000000003d333
- (_Bool)commit;	// IMP=0x001000000003d22b
- (id)applyPendingChangeToObjects:(id)arg1;	// IMP=0x001000000003d223
- (id)initWithOperation:(id)arg1;	// IMP=0x001000000003d193

@end

