//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ArcadeMetricsHandler
{
}

- (id)_getLaunchAppEventsWithContext:(id)arg1 rawLaunchEvents:(id)arg2;	// IMP=0x00400000000bcafc
- (_Bool)shouldCollectMetrics;	// IMP=0x00100000000bcaf4
- (void)recordLaunches:(id)arg1;	// IMP=0x00100000000bc6a6
- (_Bool)isCandidateAppProxy:(id)arg1 isMetadataLookup:(_Bool)arg2;	// IMP=0x00100000000bc654
- (_Bool)isCandidateAppMetadata:(id)arg1;	// IMP=0x00100000000bc63e

@end

