//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface ContextObject : NSObject
{
    NSMutableDictionary *_dictionary;	// 8 = 0x8
    struct os_unfair_lock_s _lock;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000125ad2
- (id)description;	// IMP=0x001000000012599f
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000012591a
- (id)init;	// IMP=0x00100000001258bd

@end

