//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface NanoNewsSettingsManager : NSObject
{
}

+ (void)resetSaved;	// IMP=0x00400000000059c8
+ (void)resetSeen;	// IMP=0x0010000000005984
+ (void)setSavedIdentifiers:(id)arg1;	// IMP=0x001000000000556b
+ (void)setPreferredRefreshDates:(id)arg1;	// IMP=0x0010000000005489
+ (id)preferredRefreshDates;	// IMP=0x0010000000005112
+ (_Bool)_validDateArray:(id)arg1;	// IMP=0x0010000000004fd0
+ (void)removeSeenIdentifier:(id)arg1;	// IMP=0x0010000000004f5a
+ (void)removeSavedIdentifier:(id)arg1;	// IMP=0x0010000000004ed7
+ (void)addSavedIdentifier:(id)arg1;	// IMP=0x0010000000004e54
+ (void)addSeenIdentifier:(id)arg1;	// IMP=0x0010000000004dde
+ (id)gizmoSavedHeadlineIdentifiers;	// IMP=0x0010000000004d87
+ (id)articleIdentifiersOnGizmo;	// IMP=0x0010000000004ceb
+ (id)savedHeadlineIdentifiers;	// IMP=0x0010000000004c94
+ (id)seenHeadlineIdentifiers;	// IMP=0x0010000000004c3d
+ (void)synchronizeSeenHeadlineIdentifiers;	// IMP=0x0010000000004bf9

@end

