//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableSet;

@interface VCPSceneLibraryProcessingTask : NSObject
{
    struct atomic<bool> _cancel;	// 8 = 0x8
    struct atomic<bool> _started;	// 9 = 0x9
    NSArray *_photoLibraries;	// 16 = 0x10
    NSMutableSet *_assetBatch;	// 24 = 0x18
    CDUnknownBlockType _progressHandler;	// 32 = 0x20
    CDUnknownBlockType _completionHandler;	// 40 = 0x28
    CDUnknownBlockType _cancelBlock;	// 48 = 0x30
}

+ (id)taskWithPhotoLibraries:(id)arg1 andOptions:(id)arg2 andProgressHandler:(CDUnknownBlockType)arg3 andCompletionHandler:(CDUnknownBlockType)arg4 andCancelBlock:(CDUnknownBlockType)arg5;	// IMP=0x00200000000ca839
+ (id)taskWithPhotoLibraries:(id)arg1 andProgressHandler:(CDUnknownBlockType)arg2 andCompletionHandler:(CDUnknownBlockType)arg3 andCancelBlock:(CDUnknownBlockType)arg4;	// IMP=0x00100000000ca75e
- (void).cxx_destruct;	// IMP=0x00200000000d01e0
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
- (_Bool)autoCancellable;	// IMP=0x00100000000d01bf
- (int)run;	// IMP=0x00100000000cf806
- (int)processingLibraryWithTask:(id)arg1;	// IMP=0x00100000000cf1f8
- (int)_maintainProcessingStatusWithTask:(id)arg1;	// IMP=0x00100000000cebcb
- (int)_analyzeAssetsWithChangeToken:(id)arg1 withTask:(id)arg2;	// IMP=0x00100000000cd8fb
- (int)_queryChangeTokenCountSince:(id)arg1 count:(unsigned long long *)arg2 withTask:(id)arg3;	// IMP=0x00100000000cd637
- (int)_processLocalIdentifiers:(id)arg1 change:(id)arg2 insert:(_Bool)arg3 withTask:(id)arg4;	// IMP=0x00100000000ccf45
- (int)_analyzeAllAssetsWithTask:(id)arg1;	// IMP=0x00100000000cc702
- (int)_retryAssetsWithTask:(id)arg1 andStatus:(unsigned long long)arg2 andProgressReporter:(id)arg3;	// IMP=0x00100000000cb4e5
- (int)_retryFailedAssetsWithTask:(id)arg1;	// IMP=0x00100000000cb1be
- (int)_addBatchWithAsset:(id)arg1 isRetry:(_Bool)arg2 withTask:(id)arg3;	// IMP=0x00100000000ca9f8
- (_Bool)isCancelled;	// IMP=0x00100000000ca9d4
- (void)cancel;	// IMP=0x00100000000ca9c9
- (float)resourceRequirement;	// IMP=0x00100000000ca9bb
- (void)dealloc;	// IMP=0x00100000000ca92c
- (id)initWithPhotoLibraries:(id)arg1 andOptions:(id)arg2 andProgressHandler:(CDUnknownBlockType)arg3 andCompletionHandler:(CDUnknownBlockType)arg4 andCancelBlock:(CDUnknownBlockType)arg5;	// IMP=0x00100000000ca5de
- (id)init;	// IMP=0x00100000000ca5d0

@end

