//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, _bmFMDatabase;
@protocol OS_dispatch_queue;

@interface _bmFMDatabaseQueue : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    _bmFMDatabase *_db;	// 16 = 0x10
    int _openFlags;	// 24 = 0x18
    NSString *_path;	// 32 = 0x20
    NSString *_vfsName;	// 40 = 0x28
}

+ (Class)databaseClass;	// IMP=0x004000000004af89
+ (id)databaseQueueWithURL:(id)arg1 flags:(int)arg2;	// IMP=0x001000000004af22
+ (id)databaseQueueWithPath:(id)arg1 flags:(int)arg2;	// IMP=0x001000000004aeca
+ (id)databaseQueueWithURL:(id)arg1;	// IMP=0x001000000004ae68
+ (id)databaseQueueWithPath:(id)arg1;	// IMP=0x001000000004ae1f
- (void).cxx_destruct;	// IMP=0x002000000004bd28
@property(copy) NSString *vfsName; // @synthesize vfsName=_vfsName;
@property(readonly) int openFlags; // @synthesize openFlags=_openFlags;
@property(retain) NSString *path; // @synthesize path=_path;
- (_Bool)checkpoint:(int)arg1 name:(id)arg2 logFrameCount:(int *)arg3 checkpointCount:(int *)arg4 error:(id *)arg5;	// IMP=0x001000000004bb68
- (_Bool)checkpoint:(int)arg1 name:(id)arg2 error:(id *)arg3;	// IMP=0x001000000004bb43
- (_Bool)checkpoint:(int)arg1 error:(id *)arg2;	// IMP=0x001000000004bb1c
- (id)inSavePoint:(CDUnknownBlockType)arg1;	// IMP=0x001000000004b81a
- (void)inImmediateTransaction:(CDUnknownBlockType)arg1;	// IMP=0x001000000004b800
- (void)inExclusiveTransaction:(CDUnknownBlockType)arg1;	// IMP=0x001000000004b7e9
- (void)inDeferredTransaction:(CDUnknownBlockType)arg1;	// IMP=0x001000000004b7cf
- (void)inTransaction:(CDUnknownBlockType)arg1;	// IMP=0x001000000004b7b8
- (void)beginTransaction:(long long)arg1 withBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000004b5c8
- (void)inDatabase:(CDUnknownBlockType)arg1;	// IMP=0x001000000004b497
- (id)database;	// IMP=0x001000000004b3ce
- (void)interrupt;	// IMP=0x001000000004b391
- (void)close;	// IMP=0x001000000004b30c
- (void)dealloc;	// IMP=0x001000000004b2c4
- (id)init;	// IMP=0x001000000004b2b0
- (id)initWithPath:(id)arg1;	// IMP=0x001000000004b296
- (id)initWithURL:(id)arg1;	// IMP=0x001000000004b240
- (id)initWithURL:(id)arg1 flags:(int)arg2;	// IMP=0x001000000004b1e2
- (id)initWithPath:(id)arg1 flags:(int)arg2;	// IMP=0x001000000004b1cd
- (id)initWithPath:(id)arg1 flags:(int)arg2 vfs:(id)arg3;	// IMP=0x001000000004b01c
- (id)initWithURL:(id)arg1 flags:(int)arg2 vfs:(id)arg3;	// IMP=0x001000000004af9a

@end

