//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CARSettingsCellSpecifier, NSArray, SampleTextCollectionDataSource, UIButton, UICollectionView, UILabel, UIView;

@interface CARDebugDynamicTextPanel
{
    CARSettingsCellSpecifier *_cellSpecifier;	// 8 = 0x8
    UIView *_phoneView;	// 16 = 0x10
    UIButton *_systemButton;	// 24 = 0x18
    UIButton *_xtraLargeButton;	// 32 = 0x20
    UIButton *_largeButton;	// 40 = 0x28
    UIButton *_mediumButton;	// 48 = 0x30
    UILabel *_currentSizeTitle;	// 56 = 0x38
    UICollectionView *_sampleTextCollectionView;	// 64 = 0x40
    SampleTextCollectionDataSource *_sampleTextDataSource;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0020000000024205
@property(retain, nonatomic) SampleTextCollectionDataSource *sampleTextDataSource; // @synthesize sampleTextDataSource=_sampleTextDataSource;
@property(retain, nonatomic) UICollectionView *sampleTextCollectionView; // @synthesize sampleTextCollectionView=_sampleTextCollectionView;
@property(retain, nonatomic) UILabel *currentSizeTitle; // @synthesize currentSizeTitle=_currentSizeTitle;
@property(retain, nonatomic) UIButton *mediumButton; // @synthesize mediumButton=_mediumButton;
@property(retain, nonatomic) UIButton *largeButton; // @synthesize largeButton=_largeButton;
@property(retain, nonatomic) UIButton *xtraLargeButton; // @synthesize xtraLargeButton=_xtraLargeButton;
@property(retain, nonatomic) UIButton *systemButton; // @synthesize systemButton=_systemButton;
- (void)_printFonts;	// IMP=0x0010000000023de6
@property(readonly) NSArray *fontTextStyles;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0010000000023bc3
- (void)_sizeUpdated;	// IMP=0x0010000000023a9e
- (void)_handleSizeButton:(id)arg1;	// IMP=0x00100000000239dd
- (id)_buttonWithTitle:(id)arg1;	// IMP=0x0010000000023827
- (void)viewDidLoad;	// IMP=0x0010000000022cff
- (id)phoneView;	// IMP=0x0010000000021e6e
- (id)cellSpecifier;	// IMP=0x0010000000021d17
- (id)initWithPanelController:(id)arg1;	// IMP=0x0010000000021ccb

@end

