//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class MISSING_TYPE, NSString, NSXPCConnection, NSXPCListener;

@interface CLSimulationControllerAdapter : CLIntersiloService
{
    NSXPCListener *_listener;	// 8 = 0x8
    NSXPCConnection *_connection;	// 16 = 0x10
    void *_controller;	// 24 = 0x18
}

+ (id)getSilo;	// IMP=0x00200000005c7ead
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000005c7e94
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000005c7e37
@property(nonatomic) void *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
- (MISSING_TYPE *)listener:shouldAcceptNewConnection: /* Error: Ran out of types for this method. */;	// IMP=0x00100000005c94b2
- (void)simulateBeaconWithProximityUUID:(id)arg1 major:(long long)arg2 minor:(long long)arg3 eventType:(unsigned char)arg4;	// IMP=0x00100000005c9357
- (void)simulateFenceWithBundleID:(id)arg1 andFenceID:(id)arg2 eventType:(unsigned char)arg3 atLocation:(id)arg4;	// IMP=0x00100000005c91e5
- (void)getFencesForBundleID:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00100000005c9082
- (void)simulateSignificantLocationChange:(id)arg1;	// IMP=0x00100000005c8f4e
- (void)simulateVisit:(id)arg1;	// IMP=0x00100000005c8e49
- (void)setLocationTravellingSpeed:(double)arg1;	// IMP=0x00100000005c8d49
- (void)setLocationInterval:(double)arg1;	// IMP=0x00100000005c8c4f
- (void)setIntermediateLocationDistance:(double)arg1;	// IMP=0x00100000005c8b55
- (void)setLocationRepeatBehavior:(unsigned char)arg1;	// IMP=0x00100000005c8a70
- (void)setLocationDeliveryBehavior:(unsigned char)arg1;	// IMP=0x00100000005c897b
- (void)clearSimulatedLocations;	// IMP=0x00100000005c8951
- (void)appendSimulatedLocations:(id)arg1;	// IMP=0x00100000005c8695
- (void)setSimulationScenario:(id)arg1;	// IMP=0x00100000005c8630
- (void)startLocationSimulation;	// IMP=0x00100000005c8471
- (void)stopLocationSimulation;	// IMP=0x00100000005c82c7
- (void)isInEmegencyState:(_Bool)arg1;	// IMP=0x00100000005c81b6
- (void)shutdown;	// IMP=0x00100000005c81aa
- (void)endService;	// IMP=0x00100000005c816c
- (void)beginService;	// IMP=0x00100000005c7f46
- (id)init;	// IMP=0x00100000005c7f09

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

