//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLStreamingAwareLocationProviderAdapter
{
}

+ (id)getSilo;	// IMP=0x00200000007375d6
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000007375bd
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000737560
- (void)remoteDeviceMotionUpdate:(int)arg1 atTime:(double)arg2;	// IMP=0x0020000000737b05
- (void)releaseAccuracyEnablementAssertionForClient:(byref id)arg1;	// IMP=0x0010000000737990
- (void)takeAccuracyEnablementAssertionForClient:(byref id)arg1 withDesiredAccuracy:(double)arg2;	// IMP=0x00100000007377ea
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00100000007377c2
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000737795
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x001000000073776d
- (void *)adaptee;	// IMP=0x001000000073773a
- (void)endService;	// IMP=0x001000000073771f
- (void)beginService;	// IMP=0x001000000073766f
- (id)init;	// IMP=0x0010000000737632

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

