//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CLLocation, NSString;

@interface CLTrackingAvoidanceZoneMonitor : NSObject
{
    void *wrappedAvengerZoneMonitor;	// 8 = 0x8
    _Bool _isInZone;	// 16 = 0x10
    CLLocation *_location;	// 24 = 0x18
    NSString *_timeZone;	// 32 = 0x20
}

@property(readonly) _Bool isInZone; // @synthesize isInZone=_isInZone;
@property(readonly) NSString *timeZone; // @synthesize timeZone=_timeZone;
@property(readonly) CLLocation *location; // @synthesize location=_location;
- (void)dealloc;	// IMP=0x0010000000af48a2
- (_Bool)locationIsInZoneWithLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(double)arg3;	// IMP=0x0010000000af486b
- (_Bool)onLocationUpdate:(id)arg1;	// IMP=0x0010000000af46c1
- (_Bool)_updateLocation:(id)arg1;	// IMP=0x0010000000af4638
- (id)initWithTimeZone:(id)arg1 zoneBoundary:(struct CLZoneBoundary_)arg2;	// IMP=0x0010000000af4537
- (id)init;	// IMP=0x0010000000af450c

@end

