//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray, NSString;

@interface TRANSITPbLocationFingerprintV1 : PBCodable
{
    double _latitude;	// 8 = 0x8
    double _longitude;	// 16 = 0x10
    NSString *_locationId;	// 24 = 0x18
    NSMutableArray *_macModes;	// 32 = 0x20
    struct {
        unsigned int latitude:1;
        unsigned int longitude:1;
    } _has;	// 40 = 0x28
}

@property(retain, nonatomic) NSMutableArray *macModes; // @synthesize macModes=_macModes;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *locationId; // @synthesize locationId=_locationId;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000007d6b13
- (unsigned long long)hash;	// IMP=0x00100000007d68d4
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000007d67e4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000007d65d2
- (void)copyTo:(id)arg1;	// IMP=0x00100000007d64d6
- (void)writeTo:(id)arg1;	// IMP=0x00100000007d6365
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000007d6358
- (id)dictionaryRepresentation;	// IMP=0x00100000007d5db1
- (id)description;	// IMP=0x00100000007d5d3a
- (id)macModesAtIndex:(unsigned long long)arg1;	// IMP=0x00100000007d5d1d
- (unsigned long long)macModesCount;	// IMP=0x00100000007d5d00
- (void)addMacModes:(id)arg1;	// IMP=0x00100000007d5cb3
- (void)clearMacModes;	// IMP=0x00100000007d5c96
@property(nonatomic) _Bool hasLongitude;
@property(nonatomic) _Bool hasLatitude;
@property(readonly, nonatomic) _Bool hasLocationId;
- (void)dealloc;	// IMP=0x00100000007d5b98

@end

