//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC16EventViewService15LocationManager : NSObject
{
    MISSING_TYPE *manager;	// 8 = 0x8
    MISSING_TYPE *checkedThrowingContinuation;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x004000000000f410
- (id)init;	// IMP=0x001000000000f320
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x001000000000f310
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;	// IMP=0x001000000000f280

@end

