//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <HealthUI/HKViewController.h>

@class BKSApplicationStateMonitor, HKAuthorizationPresentationRequest, HKAuthorizationRequestRecord, HKHealthRecordsStore, HKHealthStore, HKNavigationController, HKSource, NSArray, NSString, NSUUID;
@protocol HKHealthPrivacyHostRemoteViewController;

@interface HKHealthPrivacyServiceAuthorizationViewController : HKViewController
{
    _Bool _showAtViewLoad;	// 8 = 0x8
    _Bool _showAtNextSourceFetch;	// 9 = 0x9
    HKHealthRecordsStore *_healthRecordsStore;	// 16 = 0x10
    HKHealthStore *_healthStore;	// 24 = 0x18
    HKNavigationController *_navigationController;	// 32 = 0x20
    HKAuthorizationRequestRecord *_requestRecord;	// 40 = 0x28
    NSArray *_presentationRequests;	// 48 = 0x30
    NSUUID *_currentTransactionSessionIdentifier;	// 56 = 0x38
    HKSource *_currentTransactionSource;	// 64 = 0x40
    HKAuthorizationPresentationRequest *_presentedRequest;	// 72 = 0x48
    BKSApplicationStateMonitor *_applicationStateMonitor;	// 80 = 0x50
}

+ (id)_exportedInterface;	// IMP=0x002000000000686b
+ (id)_remoteViewControllerInterface;	// IMP=0x0010000000006861
- (void).cxx_destruct;	// IMP=0x0020000000006980
@property(retain, nonatomic) BKSApplicationStateMonitor *applicationStateMonitor; // @synthesize applicationStateMonitor=_applicationStateMonitor;
@property(retain, nonatomic) HKAuthorizationPresentationRequest *presentedRequest; // @synthesize presentedRequest=_presentedRequest;
@property(copy, nonatomic) HKSource *currentTransactionSource; // @synthesize currentTransactionSource=_currentTransactionSource;
@property(copy, nonatomic) NSUUID *currentTransactionSessionIdentifier; // @synthesize currentTransactionSessionIdentifier=_currentTransactionSessionIdentifier;
@property(copy, nonatomic) NSArray *presentationRequests; // @synthesize presentationRequests=_presentationRequests;
@property(retain, nonatomic) HKAuthorizationRequestRecord *requestRecord; // @synthesize requestRecord=_requestRecord;
@property(retain, nonatomic) HKNavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(readonly, nonatomic) HKHealthStore *healthStore; // @synthesize healthStore=_healthStore;
@property(readonly, nonatomic) id <HKHealthPrivacyHostRemoteViewController> _healthPrivacyHostViewController;
@property(readonly, nonatomic) HKHealthRecordsStore *healthRecordsStore; // @synthesize healthRecordsStore=_healthRecordsStore;
- (void)_finishWithError:(id)arg1;	// IMP=0x00100000000066ad
- (void)promptControllerDidFinish:(id)arg1 error:(id)arg2;	// IMP=0x00100000000065b3
- (void)_beginAuthorizationSessionWithIdentifier:(id)arg1;	// IMP=0x0010000000005fb2
- (void)_hostDidTerminate;	// IMP=0x0010000000005f10
- (void)_configureApplicationStateMonitor;	// IMP=0x0010000000005cff
- (void)_hostApplicationStateDidChange:(unsigned int)arg1;	// IMP=0x0010000000005c47
- (unsigned int)_appStateTerminationUpperBound;	// IMP=0x0010000000005bfb
- (id)_promptControllerForHealthDataPresentationRequest:(id)arg1 source:(id)arg2;	// IMP=0x00100000000059ba
- (id)_promptControllerForClinicalHealthRecordsPresentationRequest:(id)arg1 source:(id)arg2;	// IMP=0x0010000000005544
- (id)_promptControllerForPresentationRequest:(id)arg1 source:(id)arg2;	// IMP=0x00100000000054ac
- (void)_didFinishPresentingRequestWithError:(id)arg1;	// IMP=0x001000000000541e
- (void);	// IMP=0x0010000000005200
- (_Bool)_isPresentingLastRequest;	// IMP=0x0010000000005155
- (void)_presentRequestIfNeeded:(id)arg1;	// IMP=0x0010000000004ebc
- (void)show;	// IMP=0x0010000000004cb2
- (void)setRequestRecord:(id)arg1 presentationRequests:(id)arg2;	// IMP=0x0010000000004b01
- (void)viewDidLoad;	// IMP=0x0010000000004ab3
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000004a56

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

