//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIActivity.h>

@class NSString, UIImage;

@interface SSSBetaFeedbackActivity : UIActivity
{
    NSString *_title;	// 8 = 0x8
    UIImage *_image;	// 16 = 0x10
    CDUnknownBlockType _block;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000320aa
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void)performActivity;	// IMP=0x001000000003200b
- (_Bool)canPerformWithActivityItems:(id)arg1;	// IMP=0x0010000000032003
- (id)activityType;	// IMP=0x0010000000031ff6
- (id)activityImage;	// IMP=0x0010000000031fe4
- (id)activityTitle;	// IMP=0x0010000000031fd2
- (id)initWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000031e63

@end

