//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSString, SSSDittoRootViewController, SSSViewControllerManager;

@interface SSSDittoRemoteViewController : UIViewController
{
    SSSViewControllerManager *_viewControllerManager;	// 8 = 0x8
    SSSDittoRootViewController *_rootViewController;	// 16 = 0x10
    _Bool _willSoonUnparentChildDittoRootViewController;	// 24 = 0x18
}

+ (_Bool)_isSecureForRemoteViewService;	// IMP=0x002000000005885d
+ (id)_exportedInterface;	// IMP=0x001000000005883d
+ (id)_remoteViewControllerInterface;	// IMP=0x001000000005881d
- (void).cxx_destruct;	// IMP=0x00200000000588a6
@property(nonatomic) _Bool willSoonUnparentChildDittoRootViewController; // @synthesize willSoonUnparentChildDittoRootViewController=_willSoonUnparentChildDittoRootViewController;
@property(nonatomic) __weak SSSViewControllerManager *viewControllerManager; // @synthesize viewControllerManager=_viewControllerManager;
- (_Bool)_canShowWhileLocked;	// IMP=0x0010000000058865
- (void)tearDownScreenshotExperience;	// IMP=0x001000000005876d
- (void)informHostThatScreenshotsHaveDismissed;	// IMP=0x0010000000058692
- (_Bool)shouldAutorotate;	// IMP=0x001000000005868a
- (id)childViewControllerForStatusBarHidden;	// IMP=0x001000000005866d
- (id)childViewControllerForStatusBarStyle;	// IMP=0x0010000000058650
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x0010000000058645
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x001000000005854c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00100000000584bc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x001000000005844d
- (void)viewDidLoad;	// IMP=0x00100000000583b3
- (void)loadView;	// IMP=0x001000000005837a
- (id)loadedView;	// IMP=0x0010000000058368
- (void)_statusBarHeightChanged;	// IMP=0x0010000000058177
- (void)dealloc;	// IMP=0x0010000000058102
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000058073
@property(readonly, nonatomic) SSSDittoRootViewController *rootViewController;
- (void)cleanupRootViewController;	// IMP=0x0010000000058024
- (void)stopBeingParentOfDittoRootViewController:(id)arg1;	// IMP=0x0010000000057fa5
- (void)becomeParentOfDittoRootViewController:(id)arg1;	// IMP=0x0010000000057f5d
- (void)dittoRootViewController:(id)arg1 wantsBackground:(_Bool)arg2 duration:(double)arg3;	// IMP=0x0010000000057f57
- (void)dittoRootViewControllerFinishedShowingSharingUI:(id)arg1 inStateTransition:(_Bool)arg2;	// IMP=0x0010000000057f51
- (void)dittoRootViewController:(id)arg1 willShowTestFlightUIWithBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000057edf
- (void)dittoRootViewController:(id)arg1 willShowShowSharingUIWithBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000057e6d
- (void)dittoRootViewController:(id)arg1 didTransitionToState:(unsigned long long)arg2;	// IMP=0x0010000000057e67
- (void)dittoRootViewController:(id)arg1 willTransitionToState:(unsigned long long)arg2 changeBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000057dc9
- (void)_performDismiss;	// IMP=0x0010000000057d8c
- (void)_addRootViewController;	// IMP=0x0010000000057c43

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

