//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface SSSScreenshotItemProviderImage
{
}

- (id)activityViewControllerSuggestionFaceRecognitionData:(id)arg1;	// IMP=0x0020000000001d94
- (id)imageData;	// IMP=0x0010000000001cf9
- (id)activityViewController:(id)arg1 thumbnailImageDataForActivityType:(id)arg2 suggestedSize:(struct CGSize)arg3;	// IMP=0x0010000000001ce7
- (id)activityViewController:(id)arg1 attachmentNameForActivityType:(id)arg2;	// IMP=0x0010000000001c90
- (id)activityViewController:(id)arg1 subjectForActivityType:(id)arg2;	// IMP=0x0010000000001c7e
- (id)activityViewControllerLinkMetadata:(id)arg1;	// IMP=0x0010000000001962
- (id)item;	// IMP=0x0010000000001742
- (id)placeholderItemForScreenshot:(id)arg1;	// IMP=0x00100000000016ef

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

