//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableDictionary;

@interface BKTouchDestinationStatistic
{
    NSMutableDictionary *_statsPerDestination;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000090113
@property(retain, nonatomic) NSMutableDictionary *statsPerDestination; // @synthesize statsPerDestination=_statsPerDestination;
- (void)reset;	// IMP=0x00100000000900a4
- (void)appendDescriptionToFormatter:(id)arg1;	// IMP=0x001000000008ffcb
- (void)addDestination:(id)arg1 touchIdentifier:(unsigned int)arg2;	// IMP=0x001000000008fe0c

@end

