//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSError.h>

@interface GTError_replayer : NSError
{
}

- (id)dy_errorSignature;	// IMP=0x004000000002475e
- (id)localizedDescription;	// IMP=0x00100000000246ab

@end

