//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface ABSContainerSyncObject
{
    NSString *_containerIdentifier;	// 8 = 0x8
}

+ (void)applyChange:(id)arg1;	// IMP=0x004000000003487b
+ (id)_getContainer;	// IMP=0x00100000000340af
+ (long long)currentGuardianRestriction;	// IMP=0x0010000000034058
- (void).cxx_destruct;	// IMP=0x0020000000034993
@property(retain, nonatomic) NSString *containerIdentifier; // @synthesize containerIdentifier=_containerIdentifier;
- (id)createProtobufWithOptions:(id)arg1;	// IMP=0x0010000000034690
- (long long)changeType;	// IMP=0x0010000000034685
- (void)setChangeType:(long long)arg1;	// IMP=0x001000000003467f
- (id)sequencer;	// IMP=0x0010000000034677
- (id)objectIdentifier;	// IMP=0x001000000003466a

@end

