//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface WFSidebarViewController : UIViewController
{
    MISSING_TYPE *style;	// 0 = 0x0
    MISSING_TYPE *database;	// 11360 = 0x2c60
    MISSING_TYPE *sections;	// 0 = 0x0
    MISSING_TYPE *isCompact;	// 2147484672 = 0x80000400
    MISSING_TYPE *shortcutMoveService;	// 0 = 0x0
    MISSING_TYPE *rootView;	// 1953718111 = 0x74735f5f
    MISSING_TYPE *animateDataReload;	// 0 = 0x0
    MISSING_TYPE *$__lazy_storage_$_toolbarViewController;	// 0 = 0x0
    MISSING_TYPE *$__lazy_storage_$_dataSource;	// 0 = 0x0
    MISSING_TYPE *$__lazy_storage_$_collectionView;	// 0 = 0x0
    MISSING_TYPE *$__lazy_storage_$_layout;	// 0 = 0x0
    MISSING_TYPE *$__lazy_storage_$_barButtons;	// 0 = 0x0
    MISSING_TYPE *$__lazy_storage_$_sidebarDataSource;	// 0 = 0x0
    MISSING_TYPE *selectedIndexPathBeforeEditing;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x004000000005f660
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000062070
- (void)presentFolderEditorWithSender:(id)arg1;	// IMP=0x0010000000061ff0
- (void)addFolder;	// IMP=0x0010000000061f90
- (void)endEditing;	// IMP=0x0010000000061cf0
- (void)startEditing;	// IMP=0x0010000000061b50
- (void)keyboardWillChange:(id)arg1;	// IMP=0x0010000000060520
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0010000000060360
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00100000000601e0
- (void)didMoveToParentViewController:(id)arg1;	// IMP=0x001000000005ff80
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x001000000005ff10
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x001000000005fd60
- (void)dealloc;	// IMP=0x001000000005f5c0
- (void)viewDidLoad;	// IMP=0x001000000005f510
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000005aec0

@end

