//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PassKitCore/PDXPCService.h>

@class NSString;
@protocol NPDCompanionAgentClientDataSource, NPDCompanionAgentClientDelegate;

@interface NPDCompanionAgentClient : PDXPCService
{
    id <NPDCompanionAgentClientDataSource> _dataSource;	// 8 = 0x8
    id <NPDCompanionAgentClientDelegate> _delegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000328f3
@property(nonatomic) __weak id <NPDCompanionAgentClientDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <NPDCompanionAgentClientDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)_removePendingAppleCardNotification;	// IMP=0x0010000000032745
- (void)_updateLocalCommutePlanReminderForCommutePlan:(id)arg1 pass:(id)arg2;	// IMP=0x001000000003248f
- (void)_updateLocalBalanceReminderForBalance:(id)arg1 pass:(id)arg2;	// IMP=0x00100000000321ae
- (id)_commutePlanReminderIdentifierWithCommutePlan:(id)arg1 pass:(id)arg2;	// IMP=0x001000000003209c
- (void)_applyIngestionDateToPass:(id)arg1;	// IMP=0x0010000000031f9d
- (void)_selectNewDefaultCardForUserAfterDeletionOfDefaultCardWithUniqueID:(id)arg1;	// IMP=0x00100000000318af
- (void)handlePeerPaymentTermsAndConditionsRequestFromGizmo;	// IMP=0x00100000000316b2
- (void)trustedDeviceEnrollmentSignatureWithAccountDSID:(id)arg1 sessionData:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000031399
- (void)isIssuerAppProvisioningSupported:(CDUnknownBlockType)arg1;	// IMP=0x0010000000031203
- (void)expressModeEnabledForPassIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000031004
- (void)hasActiveExternallySharedPassesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000030ea1
- (void)presentStandaloneTransaction:(long long)arg1 forPassUniqueIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000030c36
- (void)markPendingTransactionAsProcessedForPassWithUniqueID:(id)arg1;	// IMP=0x0000000000030bc4
- (void)fetchPendingTransactionForPassWithUniqueID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000030b3e
- (void)noteForegroundVerificationObserverActive:(_Bool)arg1;	// IMP=0x0010000000030a15
- (void)startBackgroundVerificationObserverForPass:(id)arg1 verificationMethod:(id)arg2;	// IMP=0x00100000000308a7
- (void)setCommutePlanReminder:(id)arg1 forCommutePlan:(id)arg2 pass:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000003047a
- (void)commutePlanReminderForCommutePlan:(id)arg1 pass:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000030348
- (void)setBalanceReminder:(id)arg1 forBalance:(id)arg2 pass:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000002fe6e
- (void)balanceReminderForBalance:(id)arg1 pass:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002fd1a
- (void)balancesForPaymentPassWithUniqueIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002fbbf
- (void)transitStateWithPassUniqueIdentifier:(id)arg1 paymentApplication:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002fa41
- (void)deletePaymentTransactionWithIdentifier:(id)arg1 fromDeviceWithPairingID:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002f5e4
- (void)transactionsForTransactionSourceIdentifiers:(id)arg1 withTransactionSource:(unsigned long long)arg2 withBackingData:(unsigned long long)arg3 startDate:(id)arg4 endDate:(id)arg5 orderedByDate:(long long)arg6 limit:(long long)arg7 completion:(CDUnknownBlockType)arg8;	// IMP=0x001000000002f01a
- (void)markAllAppletsForDeletionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002ef8a
- (void)initiateLostModeExitAuthWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002ebd9
- (void)deviceIDSIdentifierWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002ea30
- (void)passesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002e615
- (void)countOfPassesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002e48e
- (void)updateSettings:(unsigned long long)arg1 forPassWithUniqueID:(id)arg2;	// IMP=0x001000000002e3bd
- (void)peerPaymentAccountForPairingID:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002e166
- (void)setPeerPaymentAccount:(id)arg1 forPairingID:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002e0b8
- (void)sharedPeerPaymentWebServiceContextForPairingID:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002de8d
- (void)setSharedPeerPaymentWebServiceContext:(id)arg1 forPairingID:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002ddea
- (void)sharedPaymentWebServiceContextForPairingID:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002ddd4
- (void)setSharedPaymentWebServiceContext:(id)arg1 forPairingID:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002ddc1
- (void)handlePendingiCloudSignoutWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002ddbb
- (void)handlePendingUnpairingWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002ddb5
- (void)redownloadAllPaymentPassesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002ddaf
- (void)initiateConsistencyCheckWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002dda9
- (void)setDefaultPaymentApplication:(id)arg1 forPassWithUniqueID:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002d643
- (void)defaultPaymentApplicationForPassWithUniqueID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002d47a
- (_Bool)_isPassQualifiedToBeDefaultWithUniqueID:(id)arg1;	// IMP=0x001000000002d20a
- (void)willPassWithUniqueIdentifierAutomaticallyBecomeDefault:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002d15c
- (id)_defaultCard;	// IMP=0x001000000002d078
- (void)defaultCard:(CDUnknownBlockType)arg1;	// IMP=0x001000000002d013
- (void)setDefaultCard:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002cb53
- (_Bool)_isGizmoConnected;	// IMP=0x001000000002ca9b
- (void)removePaymentPassWithUniqueID:(id)arg1 forPairingID:(id)arg2 waitForConfirmation:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000002bb06
- (void)savePaymentPassData:(id)arg1 withUniqueID:(id)arg2 forPairingID:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000002b25d
- (void)credentialedPassUniqueIDsWithReply:(CDUnknownBlockType)arg1;	// IMP=0x001000000002ad49
- (void)paymentPassWithPairedTerminalIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002a7c1
- (void)paymentPassWithDeviceAccountIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002a2f0
- (void)paymentPassesWithPrimaryAccountIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000029dbd
- (id)paymentPassWithUniqueID:(id)arg1;	// IMP=0x0010000000029955
- (void)paymentPassWithUniqueID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000298e4
- (void)paymentPassUniqueIDsExcludingDeactivated:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000029538
- (void)registerDeviceWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000293d5
- (void)noteProvisioningPreflightCompleteWithSuccess:(_Bool)arg1 error:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000291b4
- (void)beginProvisioningFromWatchOfferForPaymentPasses:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000028d23
- (void)handleProvisioningErrorForAccountIdentifier:(id)arg1 error:(id)arg2;	// IMP=0x0010000000028786
- (void)handleDeviceUnlockedForPendingProvisioningRequestFromGizmo;	// IMP=0x0010000000027ff5
- (void)provisionPassForRemoteCredentialWithType:(long long)arg1 andIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000027ec9
- (void)provisionPassForAccountIdentifier:(id)arg1 makeDefault:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002742e
- (void)noteWatchOfferDisplayedForPaymentPassWithUniqueID:(id)arg1;	// IMP=0x0010000000027301
- (void)connect;	// IMP=0x00100000000272fb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

