//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, PLPhotoLibraryBundle;
@protocol OS_xpc_object;

@interface PLLibraryRepairSupport : NSObject
{
    NSObject<OS_xpc_object> *_xpcActivity;	// 8 = 0x8
    MISSING_TYPE *_transaction;	// 16 = 0x10
    NSString *_description;	// 24 = 0x18
    PLPhotoLibraryBundle *_bundle;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000007c19
@property(retain) PLPhotoLibraryBundle *bundle; // @synthesize bundle=_bundle;
- (void)runPeriodicMaintenanceActivityOnAllLibrariesWithExecutionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000074d9
- (void)_maintainLibrary:(id)arg1 executionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000006f05
- (_Bool)_updateDeferredCriticalMaintenanceTaskMarker:(id)arg1;	// IMP=0x0010000000006e7d
- (_Bool)_updateDeferredMaintenanceTaskMarker:(id)arg1 value:(id)arg2;	// IMP=0x0010000000006e61
- (_Bool)_updateMaintenanceTaskMarker:(id)arg1 key:(id)arg2 value:(id)arg3;	// IMP=0x0010000000006d41
- (_Bool)_isValidProcessingURL:(id)arg1 interruptedPaths:(id)arg2;	// IMP=0x0010000000006ca6
- (id)_interruptedProcessingURLs;	// IMP=0x0010000000006bee
- (void)_saveInterruptedProcessingURLs:(id)arg1;	// IMP=0x0010000000006b44
- (id)_buildIncompleteMaintenanceTaskPathsKey;	// IMP=0x0010000000006a77
- (void)runPeriodicMaintenance;	// IMP=0x001000000000650d
- (void)runCuratedLibraryPeriodicMaintenanceTasks;	// IMP=0x0010000000006423
- (_Bool)_runCriticalPeriodicMaintenanceTasksDeferActivityIfRequired:(id)arg1;	// IMP=0x00100000000062ae
- (_Bool)_deferActivityIfRequiredForClassName:(id)arg1;	// IMP=0x00100000000060f0
- (unsigned long long)_indexOfRegisteredMaintenanceTaskForMarker:(id)arg1;	// IMP=0x0010000000006005
- (id)_registeredMaintenanceTaskClasses;	// IMP=0x0010000000005e75
- (id)_registeredCriticalMaintenaceTaskClasses;	// IMP=0x0010000000005de4
- (id)initWithActivity:(id)arg1 description:(id)arg2;	// IMP=0x0010000000005d09

@end

