//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BLJaliscoDAAPClient, NSString;
@protocol BLJaliscoDAAPClientDelegate;

@interface BDSJaliscoDAAPServiceImpl : NSObject
{
    _Bool _storeAuthenticationRequired;	// 8 = 0x8
    BLJaliscoDAAPClient *_jaliscoClient;	// 16 = 0x10
}

+ (id)sharedClient;	// IMP=0x00200000000345aa
- (void).cxx_destruct;	// IMP=0x0020000000034ce0
@property(retain, nonatomic) BLJaliscoDAAPClient *jaliscoClient; // @synthesize jaliscoClient=_jaliscoClient;
@property(readonly, nonatomic) _Bool storeAuthenticationRequired; // @synthesize storeAuthenticationRequired=_storeAuthenticationRequired;
- (void)updatePolitely:(_Bool)arg1 uiManager:(id)arg2 reason:(long long)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000034c3f
- (void)resetStaleJaliscoDatabaseWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000034bcd
- (void)deleteItemsWithStoreIDs:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000034b47
- (void)hideItemsWithStoreIDs:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000034ac1
- (void)resetPurchasedTokenForStoreIDs:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000034a3b
- (void)setItemHidden:(_Bool)arg1 forStoreID:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000349ad
- (void)updateFamilyPolitely:(_Bool)arg1 reason:(long long)arg2 completionWithError:(CDUnknownBlockType)arg3;	// IMP=0x0010000000034930
- (void)updateFamilyPolitely:(_Bool)arg1 reason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000348b3
- (void)updatePolitelyAfterSignIn:(_Bool)arg1 reason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000034836
- (void)updatePolitelyAfterSignOut:(_Bool)arg1 reason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000347b9
- (void)updatePolitely:(_Bool)arg1 reason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000003473c
- (void)updatePolitely:(_Bool)arg1 reason:(long long)arg2 completionWithError:(CDUnknownBlockType)arg3;	// IMP=0x00100000000346bf
@property(nonatomic) __weak id <BLJaliscoDAAPClientDelegate> daapClientDelegate;
- (id)init;	// IMP=0x00100000000344d1

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

