//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface NSObject (ICLoggable)
+ (id)ic_loggingDescriptionFromLoggable:(id)arg1 isPretty:(_Bool)arg2;	// IMP=0x0020000000073eb1
- (id)ic_loggingIdentifier;	// IMP=0x0020000000073e8c
- (id)ic_prettyLoggingDescription;	// IMP=0x0010000000073e10
- (id)ic_loggingDescription;	// IMP=0x0010000000073d97
- (id)undateify;	// IMP=0x001000000042f830
@end

