//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData, NSDate, REMCDReminder;

@interface REMCDRecurrenceRule
{
}

+ (id)cdEntityName;	// IMP=0x001000000007161b
+ (_Bool)isAbstract;	// IMP=0x0010000000071613
+ (id)keyPathsForValuesAffectingEffectiveMinimumSupportedVersion;	// IMP=0x0010000000052aaf
+ (id)fetchRequest;	// IMP=0x0010000000052e82
+ (_Bool)shouldAttemptLocalObjectMerge;	// IMP=0x0010000000408fd0
+ (id)newCloudObjectForRecord:(id)arg1 account:(id)arg2 context:(id)arg3;	// IMP=0x0010000000407b90
+ (id)existingCloudObjectForRecordID:(id)arg1 accountID:(id)arg2 context:(id)arg3;	// IMP=0x0010000000407750
+ (id)recordTypes;	// IMP=0x0010000000407630
- (void)debug_lowLevelRemoveFromParent;	// IMP=0x0000000000052b52
- (long long)parentEffectiveMinimumSupportedVersion;	// IMP=0x0010000000052acf
- (_Bool)isConnectedToAccountObject:(id)arg1;	// IMP=0x0010000000052a38
- (void)fixBrokenReferences;	// IMP=0x0010000000409940
- (void)cleanUpAfterLocalObjectMerge;	// IMP=0x00100000004092b0
- (_Bool)mergeWithLocalObject:(id)arg1;	// IMP=0x0010000000409060
- (id)existingLocalObjectToMergeWithPredicate:(id)arg1;	// IMP=0x0010000000408ff0
- (id)parentCloudObject;	// IMP=0x0010000000408f80
- (id)newlyCreatedRecord;	// IMP=0x0010000000408f20
- (void)mergeDataFromRecord:(id)arg1 accountID:(id)arg2;	// IMP=0x0010000000408580
- (_Bool)shouldMarkAsDeletedInsteadOfDeletingImmediately;	// IMP=0x0010000000407d00
- (_Bool)supportsDeletionByTTL;	// IMP=0x0010000000407ce0
- (id)recordType;	// IMP=0x0010000000407ca0
- (id)recordZoneName;	// IMP=0x0010000000407c40

// Remaining properties
@property(retain, nonatomic) NSData *daysOfTheMonth; // @dynamic daysOfTheMonth;
@property(retain, nonatomic) NSData *daysOfTheWeek; // @dynamic daysOfTheWeek;
@property(retain, nonatomic) NSData *daysOfTheYear; // @dynamic daysOfTheYear;
@property(copy, nonatomic) NSDate *endDate; // @dynamic endDate;
@property(nonatomic) short firstDayOfTheWeek; // @dynamic firstDayOfTheWeek;
@property(nonatomic) short frequency; // @dynamic frequency;
@property(nonatomic) short interval; // @dynamic interval;
@property(retain, nonatomic) NSData *monthsOfTheYear; // @dynamic monthsOfTheYear;
@property(nonatomic) long long occurrenceCount; // @dynamic occurrenceCount;
@property(retain, nonatomic) REMCDReminder *reminder; // @dynamic reminder;
@property(retain, nonatomic) NSData *setPositions; // @dynamic setPositions;
@property(retain, nonatomic) NSData *weeksOfTheYear; // @dynamic weeksOfTheYear;

@end

