//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface REMCDAuxiliaryReminderChangeDeleteInfo
{
}

+ (id)cdEntityName;	// IMP=0x0010000000068fa6
+ (_Bool)isAbstract;	// IMP=0x0010000000068f9e
+ (id)fetchRequest;	// IMP=0x001000000007073b

// Remaining properties
@property(copy, nonatomic) NSString *oldExternalIdentifier; // @dynamic oldExternalIdentifier;
@property(copy, nonatomic) NSString *oldListIdentifier; // @dynamic oldListIdentifier;

@end

