//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ASDJobManager, ASDUpdatesService, FBSDisplayLayoutMonitor, NSArray, NSMutableDictionary, NSString;

@interface DMDiphoneOSAppController
{
    NSString *_singleAppModeBundleIndentifier;	// 8 = 0x8
    NSMutableDictionary *_bundleIDsToAssertions;	// 16 = 0x10
    FBSDisplayLayoutMonitor *_layoutMonitor;	// 24 = 0x18
    NSArray *__foregroundBundleIdentifiers;	// 32 = 0x20
}

+ (id)metadataPath;	// IMP=0x002000000001e618
+ (id)changeTypeAsString:(long long)arg1;	// IMP=0x001000000001e344
+ (id)_appleAccountForPersona:(id)arg1;	// IMP=0x001000000001e0bb
+ (id)_appStoreAccountIdentifierForPersona:(id)arg1;	// IMP=0x001000000001df49
+ (id)enumeratorForOrdinaryApps;	// IMP=0x001000000001c1c5
+ (id)enumeratorForSystemAppPlaceholders;	// IMP=0x001000000001c1ac
+ (id)enumeratorForUserAppPlaceholders;	// IMP=0x001000000001c18e
- (void).cxx_destruct;	// IMP=0x001000000001ffe5
@property(retain, nonatomic) NSArray *_foregroundBundleIdentifiers; // @synthesize _foregroundBundleIdentifiers=__foregroundBundleIdentifiers;
@property(retain, nonatomic) FBSDisplayLayoutMonitor *layoutMonitor; // @synthesize layoutMonitor=_layoutMonitor;
@property(retain, nonatomic) NSMutableDictionary *bundleIDsToAssertions; // @synthesize bundleIDsToAssertions=_bundleIDsToAssertions;
@property(copy, nonatomic) NSString *singleAppModeBundleIndentifier; // @synthesize singleAppModeBundleIndentifier=_singleAppModeBundleIndentifier;
- (void)_updateForegroundBundleIdentifiers;	// IMP=0x001000000001fc4f
- (void)_getMetadataForBundleIdentifier:(id)arg1 storeItemIdentifier:(id)arg2 personaIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000001f692
- (void)_applyStoreDictionary:(id)arg1 toAppMetadata:(id)arg2;	// IMP=0x001000000001f4ca
- (id)_managedDefaultsForBundleIdentifier:(id)arg1;	// IMP=0x001000000001f478
- (_Bool)setFeedback:(id)arg1 forBundleIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x001000000001f1a9
- (id)feedbackForBundleIdentifier:(id)arg1;	// IMP=0x001000000001ef17
- (void)_withSandboxExtensionForApp:(id)arg1 do:(CDUnknownBlockType)arg2;	// IMP=0x001000000001eca5
- (_Bool)setConfiguration:(id)arg1 forBundleIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x001000000001eaf8
- (id)configurationForBundleIdentifier:(id)arg1;	// IMP=0x001000000001eaa1
- (void)getMetadataForNonEnterpriseAppRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001e73e
- (void)getBundleIdentifierForStoreItemIdentifier:(id)arg1 personaIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000001e631
- (_Bool)writeManagementInformationToDiskWithError:(id *)arg1;	// IMP=0x001000000001e599
- (void)installSystemAppWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001e363
- (void)sendAppRequestWithBundleIdentifier:(id)arg1 storeItemIdentifier:(id)arg2 personaIdentifier:(id)arg3 type:(long long)arg4 skipDownloads:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x001000000001db2f
- (void)promptUserToSignInWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000001d963
@property(readonly, nonatomic) _Bool userIsSignedIn;
- (void)removeTerminationAssertionForBundleIdentifier:(id)arg1;	// IMP=0x001000000001d7c2
- (void)addTerminationAssertion:(id)arg1 forBundleIdentifier:(id)arg2;	// IMP=0x001000000001d66e
@property(readonly, copy, nonatomic) ASDUpdatesService *updatesService;
@property(readonly, copy, nonatomic) ASDJobManager *jobManager;
- (id)foregroundBundleIdentifiers;	// IMP=0x001000000001d56b
- (id)initPrivate;	// IMP=0x001000000001d3db
- (id)_allPropertyKeys;	// IMP=0x001000000001c25a
- (unsigned long long)appTypeFromProxy:(id)arg1;	// IMP=0x001000000001c1e0
- (void)handleFetchRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001aeb1
- (void)_downloadAppForRequest:(id)arg1 type:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000001d1b8
- (void)_installUserAppForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001cf83
- (void)_installDeviceLicensedAppForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001cea2
- (void)resumeAppInstallationWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001c934
- (void)startInstallingNonEnterpriseAppForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001c6fc
- (void)startInstallingEnterpriseAppWithManifestURL:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001c4c4
- (void)startRedeemingAppWithCode:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000020038
- (void)_uninstallAppWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000020ba1
- (void)startUninstallingAppWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000020912
- (void)cancelAppInstallationWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000020422
- (void)_updateEndedForLifeCycle:(id)arg1;	// IMP=0x0010000000021519
- (void)_startUpdatingAppForRequest:(id)arg1 metadata:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000021193
- (void)didFinishUpdatingForLifeCycle:(id)arg1;	// IMP=0x0010000000021125
- (void)didFailUpdatingForLifeCycle:(id)arg1;	// IMP=0x00100000000210b7
- (void)didCancelUpdatingForLifeCycle:(id)arg1;	// IMP=0x0010000000021049
- (void)resumeAppUpdateWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000021037
- (void)cancelAppUpdateWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000021025
- (void)startUpdatingAppForRequest:(id)arg1 metadata:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000020dc4

@end

