//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSSecureUnarchiveFromDataTransformer.h>

@interface DMDSecureUnarchiveFromEventSubscriptionRegistrationDataTransformer : NSSecureUnarchiveFromDataTransformer
{
}

+ (id)allowedTopLevelClasses;	// IMP=0x00400000000529b8
+ (void)initialize;	// IMP=0x0010000000052954

@end

