//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDSetAppRemovabilityOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x004000000007bbef
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000007bbbd
- (void)runWithRequest:(id)arg1 bundleIdentifier:(id)arg2;	// IMP=0x004000000007bbfc

@end

