//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CATTaskServer, NSString;

@interface DMDTaskServerListenerDelegate : NSObject
{
    CATTaskServer *_taskServer;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000838eb
@property(readonly, nonatomic) CATTaskServer *taskServer; // @synthesize taskServer=_taskServer;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00100000000837e7
- (id)initWithTaskServer:(id)arg1;	// IMP=0x001000000008377c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

