//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@interface _TtC13MediaRemoteUI34CoverSheetBackgroundViewController : UIViewController
{
}

- (id)initWithCoder:(id)arg1;	// IMP=0x00400000000052c0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000005210
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00100000000051c0
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0010000000004f30
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000004f10
- (void)viewDidLoad;	// IMP=0x0010000000004ee0
- (void)loadView;	// IMP=0x0010000000004d50
- (_Bool)_canShowWhileLocked;	// IMP=0x0010000000004d40

@end

