//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface GKBadgeController : NSObject
{
    NSMutableDictionary *_badgeDictionaries[4];	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_syncQueue;	// 40 = 0x28
    _Bool _dirty;	// 48 = 0x30
}

+ (id)sharedController;	// IMP=0x004000000013ccf9
- (void).cxx_destruct;	// IMP=0x002000000013f84f
- (void)registerBadgePermissionForBundleID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000013f4a2
- (void)unbadgeAllApplications;	// IMP=0x001000000013f1fc
- (void)badgeAllApplications;	// IMP=0x001000000013ef05
- (void)setBadgeCount:(unsigned long long)arg1 forBundleID:(id)arg2 badgeType:(unsigned long long)arg3;	// IMP=0x001000000013e94f
- (unsigned long long)_totalBadgeCountForBundleID:(id)arg1;	// IMP=0x001000000013e72b
- (unsigned long long)badgeCountForBundleID:(id)arg1 badgeType:(unsigned long long)arg2;	// IMP=0x001000000013e48d
- (unsigned long long)_badgeCountForBundleID:(id)arg1 badgeType:(unsigned long long)arg2;	// IMP=0x001000000013e276
- (id)_dictionaryForBadgeType:(unsigned long long)arg1;	// IMP=0x001000000013e0c7
- (void)badgeBundleID:(id)arg1 badgeCount:(unsigned long long)arg2;	// IMP=0x001000000013dc5f
- (void)badgeApplicationWithBundleID:(id)arg1 badgeCount:(unsigned long long)arg2;	// IMP=0x001000000013d6b8
- (_Bool)isBadgingEnabledForBundleID:(id)arg1;	// IMP=0x001000000013d60a
- (void)synchronize;	// IMP=0x001000000013ce8f
- (id)_plistKeyForBadgeType:(unsigned long long)arg1;	// IMP=0x001000000013ce6a
- (id)init;	// IMP=0x001000000013ce02
- (id)_badgeCountURL;	// IMP=0x001000000013cd4e

@end

