//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface GKCompatibilityListCacheObject
{
}

+ (Class)entryClass;	// IMP=0x004000000015c570
+ (id)entityName;	// IMP=0x001000000015c563
- (void)updateWithServerRepresentation:(id)arg1 expirationDate:(id)arg2;	// IMP=0x002000000015c581

// Remaining properties
@property(retain, nonatomic) NSString *bundleID; // @dynamic bundleID;
@property(retain, nonatomic) NSString *shortVersion; // @dynamic shortVersion;
@property(retain, nonatomic) NSString *version; // @dynamic version;

@end

