//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSString;

@interface GKRealTimeMultiplayerActionBulletin
{
    NSString *_debugLine;	// 112 = 0x70
    MISSING_TYPE *_notificationName;	// 120 = 0x78
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x0040000000216222
- (void).cxx_destruct;	// IMP=0x0020000000219679
@property(readonly) NSString *notificationName; // @synthesize notificationName=_notificationName;
@property(readonly) NSString *debugLine; // @synthesize debugLine=_debugLine;
- (_Bool)isAccept;	// IMP=0x001000000021961e
- (id)getNotificationName;	// IMP=0x00100000002195ef
- (id)getDebugLine;	// IMP=0x00100000002195c0
@property(readonly) NSString *aggregateDictionaryKey;
- (void)assembleBulletin;	// IMP=0x001000000021932b
- (void)setInvitedPlayerRespondedWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000002175c6
- (void)loadDataWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000216c23

@end

