//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKRealTimeMultiplayerCancelBulletin
{
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x004000000021af52
- (id)removeAndReturnAssociatedInvite;	// IMP=0x004000000021bfe9
- (void)assembleBulletin;	// IMP=0x001000000021bc7b
- (void)copyDataFromAssociatedBulletin:(id)arg1;	// IMP=0x001000000021ba1c

@end

