//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GKLeaderboardInternal, GKScoreInternal;

@interface GKScoreChallengeInternal
{
    GKScoreInternal *_score;	// 88 = 0x58
    GKLeaderboardInternal *_leaderboard;	// 96 = 0x60
}

+ (id)secureCodedPropertyKeys;	// IMP=0x004000000000484c
+ (id)internalRepresentation;	// IMP=0x001000000000483a
- (void).cxx_destruct;	// IMP=0x0020000000004e6c
@property(retain, nonatomic) GKLeaderboardInternal *leaderboard; // @synthesize leaderboard=_leaderboard;
@property(copy, nonatomic) GKScoreInternal *score; // @synthesize score=_score;
- (id)titleText;	// IMP=0x0010000000004cac
- (unsigned long long)type;	// IMP=0x0010000000004ca1
- (id)serverRepresentationForReceivingPlayer:(id)arg1;	// IMP=0x0010000000004972

@end

