//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSMethodSignature.h>

@interface NSMethodSignature (GKAdditions)
- (_Bool)_gkHasReplyBlock;	// IMP=0x0010000000178288
- (_Bool)_gkTakesBlockAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000178234
@end

