//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FRVersionHelpers, MISSING_TYPE, NSDate, NSString, UIViewController;

@interface FRApplicationUpdateNotifier : NSObject
{
    _Bool _isPresentingAlert;	// 8 = 0x8
    UIViewController *_viewController;	// 16 = 0x10
    NSDate *_nextAlertPresentationDate;	// 24 = 0x18
    long long _alertPresentationCount;	// 32 = 0x20
    FRVersionHelpers *_versionHelpers;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0020000000053f7c
@property(retain, nonatomic) FRVersionHelpers *versionHelpers; // @synthesize versionHelpers=_versionHelpers;
@property(nonatomic) _Bool isPresentingAlert; // @synthesize isPresentingAlert=_isPresentingAlert;
@property(nonatomic) long long alertPresentationCount; // @synthesize alertPresentationCount=_alertPresentationCount;
@property(copy, nonatomic) NSDate *nextAlertPresentationDate; // @synthesize nextAlertPresentationDate=_nextAlertPresentationDate;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
- (void)activityObservingApplicationWindowDidBecomeForeground;	// IMP=0x0010000000053e97
- (MISSING_TYPE *)shouldPresentLastAlertForCurrentUpdate;	// IMP=0x0010000000053e89
- (_Bool)isAlertPresentationIntervalPassed;	// IMP=0x0010000000053d52
- (void)launchSettings;	// IMP=0x0010000000053d12
- (void)updateAlertDidDismiss:(_Bool)arg1;	// IMP=0x0010000000053c86
- (void)showAppUpdateAlert;	// IMP=0x00100000000537b2
- (_Bool)shouldShowUpdateAlert;	// IMP=0x001000000005371f
- (void)persistStates;	// IMP=0x001000000005350c
- (void)restoreStates;	// IMP=0x001000000005342b
- (id)persistableProperties;	// IMP=0x001000000005341e
- (void)setup;	// IMP=0x001000000005340c
- (id)initWithVersionHelpers:(id)arg1 appActivityMonitor:(id)arg2;	// IMP=0x0010000000053323
- (id)init;	// IMP=0x00100000000531de

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

