//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FRCardConfigurationCache;

@interface FRCardConfiguration : NSObject
{
    double _cardCornerRadius;	// 8 = 0x8
    double _materialBlurRadius;	// 16 = 0x10
    double _materialColorAlpha;	// 24 = 0x18
    FRCardConfigurationCache *_cache;	// 32 = 0x20
}

+ (id)_gradientCGColors;	// IMP=0x00400000000b89da
+ (struct CGSize)textMargin;	// IMP=0x00100000000b845e
+ (double)bannerHeightForWidth:(double)arg1;	// IMP=0x00100000000b7186
+ (id)cardConfiguration;	// IMP=0x00100000000b70c2
- (void).cxx_destruct;	// IMP=0x00200000000b9163
@property(retain, nonatomic) FRCardConfigurationCache *cache; // @synthesize cache=_cache;
@property(readonly, nonatomic) double materialColorAlpha; // @synthesize materialColorAlpha=_materialColorAlpha;
@property(readonly, nonatomic) double materialBlurRadius; // @synthesize materialBlurRadius=_materialBlurRadius;
@property(readonly, nonatomic) double cardCornerRadius; // @synthesize cardCornerRadius=_cardCornerRadius;
- (void)prewarmConfigurationForCardSize:(struct CGSize)arg1 sizeCategory:(id)arg2;	// IMP=0x00100000000b902c
- (id)placeholderChannelImageForCardOfSize:(struct CGSize)arg1;	// IMP=0x00100000000b8efc
- (id)placeholderTopicImageForCardOfSize:(struct CGSize)arg1;	// IMP=0x00100000000b8dcf
- (id)_placeholderOfSize:(struct CGSize)arg1 withChin:(_Bool)arg2;	// IMP=0x00100000000b8cf6
- (id)gradientLayerWithChin:(_Bool)arg1;	// IMP=0x00100000000b8b3a
- (struct CGSize)topicTitleTextSize:(id)arg1 cardSize:(struct CGSize)arg2;	// IMP=0x00100000000b889b
- (struct CGSize)topicTextSize:(id)arg1 cardSize:(struct CGSize)arg2;	// IMP=0x00100000000b875c
- (struct CGRect)topicTextRect:(id)arg1 cardSize:(struct CGSize)arg2 textPadPath:(id *)arg3;	// IMP=0x00100000000b8516
- (struct CGRect)topicFrameForSize:(struct CGSize)arg1;	// IMP=0x00100000000b8474
- (id)topicTextAttributesForCardSize:(struct CGSize)arg1 textColor:(id)arg2 sizeCategory:(id)arg3;	// IMP=0x00100000000b8205
- (id)topicTitleAttributesForCardSize:(struct CGSize)arg1 textColor:(id)arg2 sizeCategory:(id)arg3;	// IMP=0x00100000000b803f
- (double)spaceBetweenHorizontalDividerAndTopicNameForCardSize:(struct CGSize)arg1;	// IMP=0x00100000000b8020
- (double)spaceBetweenTopicTitleAndHorizontalDividerForCardSize:(struct CGSize)arg1;	// IMP=0x00100000000b8001
- (double)horizontalDividerWidthForCardSize:(struct CGSize)arg1;	// IMP=0x00100000000b7fe2
- (double)topicTitleTopMarginForCardSize:(struct CGSize)arg1;	// IMP=0x00100000000b7fc3
- (struct UIEdgeInsets)insetsForCollectionViewBounds:(struct CGRect)arg1;	// IMP=0x00100000000b7f74
- (struct CGSize)itemSizeForCollectionViewBounds:(struct CGRect)arg1 isCompact:(_Bool)arg2 orientation:(long long)arg3;	// IMP=0x00100000000b7e4f
- (unsigned long long)numberOfColumnsForCollectionViewBounds:(struct CGRect)arg1 isCompact:(_Bool)arg2 orientation:(long long)arg3;	// IMP=0x00100000000b7dd3
- (struct UIEdgeInsets)gridInsetsForWidth:(double)arg1;	// IMP=0x00100000000b7d54
- (double)gridSpacingForWidth:(double)arg1;	// IMP=0x00100000000b7cf9
- (struct UIEdgeInsets)logoInsetsForBannerSize:(struct CGSize)arg1 logoAspectRatio:(double)arg2;	// IMP=0x00100000000b7b92
- (struct CGRect)bannerFrameForSize:(struct CGSize)arg1;	// IMP=0x00100000000b7b24
- (id)attributedStringForTag:(id)arg1 boundsSize:(struct CGSize)arg2 sizeCategory:(id)arg3;	// IMP=0x00100000000b7833
- (id)textColorForTag:(id)arg1;	// IMP=0x00100000000b7745
- (double)_kerningFeedsWhenInCardsOfSize:(struct CGSize)arg1 isChannel:(_Bool)arg2 sizeCategory:(id)arg3;	// IMP=0x00100000000b76fe
- (double)kerningForTopicFeedsWhenInCardsOfSize:(struct CGSize)arg1 sizeCategory:(id)arg2;	// IMP=0x00100000000b76e7
- (double)kerningForChannelFeedsWhenInCardsOfSize:(struct CGSize)arg1 sizeCategory:(id)arg2;	// IMP=0x00100000000b76cd
- (id)fontForChannelFeedsWhenInCardsOfSize:(struct CGSize)arg1 sizeCategory:(id)arg2;	// IMP=0x00100000000b74c2
- (id)fontForTopicFeedsWhenInCardsOfSize:(struct CGSize)arg1 sizeCategory:(id)arg2;	// IMP=0x00100000000b73b8
- (double)_fontSizeForTopicFeedsWhenInCardsOfSize:(struct CGSize)arg1 sizeCategory:(id)arg2;	// IMP=0x00100000000b735a
- (double)_fontSizeForTopicTitleWhenInCardsOfSize:(struct CGSize)arg1 sizeCategory:(id)arg2;	// IMP=0x00100000000b72fc
- (double)lineHeightForSize:(struct CGSize)arg1;	// IMP=0x00100000000b72dd
- (double)insetForFeed:(id)arg1 sizeCategory:(id)arg2;	// IMP=0x00100000000b71ac
- (id)init;	// IMP=0x00100000000b7117

@end

