//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionView.h>

@class NSObject;

@interface FRCollectionView : UICollectionView
{
    unsigned long long _mode;	// 8 = 0x8
    NSObject *__accessibilityFocusedIdentifierForRestoringAfterReload;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000a56bb
@property(retain, nonatomic) NSObject *_accessibilityFocusedIdentifierForRestoringAfterReload; // @synthesize _accessibilityFocusedIdentifierForRestoringAfterReload=__accessibilityFocusedIdentifierForRestoringAfterReload;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
- (long long)accessibilityContainerType;	// IMP=0x00100000000a5656
- (void)_accessibilityRestoreFocusedElementIfApplicable;	// IMP=0x00100000000a54d2
- (void)_accessibilitySaveFocusedElementIfApplicable;	// IMP=0x00100000000a53e0
- (void)reloadData;	// IMP=0x00100000000a5340

@end

