//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSString, UIImageView, UILabel;

@interface FRFeatureView : UIView
{
    _Bool _imageOnTop;	// 8 = 0x8
    UIImageView *_featureImageView;	// 16 = 0x10
    UILabel *_featureTitleLabel;	// 24 = 0x18
    UILabel *_featureBodyLabel;	// 32 = 0x20
    NSString *_title;	// 40 = 0x28
    NSString *_body;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x002000000003fb35
@property(copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) __weak UILabel *featureBodyLabel; // @synthesize featureBodyLabel=_featureBodyLabel;
@property(readonly, nonatomic) __weak UILabel *featureTitleLabel; // @synthesize featureTitleLabel=_featureTitleLabel;
@property(readonly, nonatomic) __weak UIImageView *featureImageView; // @synthesize featureImageView=_featureImageView;
@property(nonatomic) _Bool imageOnTop; // @synthesize imageOnTop=_imageOnTop;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x001000000003f9d8
- (void)layoutSubviews;	// IMP=0x001000000003ef1b
- (double)lineHeight;	// IMP=0x001000000003eed3
- (id)bodyFont;	// IMP=0x001000000003ee4a
- (id)titleFont;	// IMP=0x001000000003edc1
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x001000000003ec04
- (double)titleToBodySpacing;	// IMP=0x001000000003ebfb
@property(readonly, nonatomic) double imageOnTopPadding;
- (double)iconPadding;	// IMP=0x001000000003eb1a
- (double)textPadding;	// IMP=0x001000000003eabc
- (double)minTextWidth;	// IMP=0x001000000003e956
@property(readonly, nonatomic) struct CGSize iconSize;
- (_Bool)useCompactLayout;	// IMP=0x001000000003e89a
- (id)featureBody;	// IMP=0x001000000003e84a
- (id)featureTitle;	// IMP=0x001000000003e7fa
- (id)featureImage;	// IMP=0x001000000003e7aa
- (id)initWithImage:(id)arg1 title:(id)arg2 body:(id)arg3;	// IMP=0x001000000003e527
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000003e50e
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000003e4f5

@end

