//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC7parsecdP33_A71F4EB6BEA682B89431D07BAC0060AE19PARBagConfigFactory : NSObject
{
}

- (id)init;	// IMP=0x00400000000e8a60
- (id)loadWithData:(id)arg1 userAgent:(id)arg2 userDefaults:(id)arg3;	// IMP=0x00100000000e8980
- (id)loadWithUrl:(id)arg1 userAgent:(id)arg2 userDefaults:(id)arg3;	// IMP=0x00100000000e88a0

@end

