//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, NSString;

@interface XCSynthesizedEventRecord : NSObject
{
    NSMutableArray *_eventPaths;	// 8 = 0x8
    _Bool _beginsPersistentState;	// 16 = 0x10
    _Bool _endsPersistentState;	// 17 = 0x11
    NSString *_name;	// 24 = 0x18
    long long _interfaceOrientation;	// 32 = 0x20
    long long _targetProcessID;	// 40 = 0x28
    unsigned long long _displayID;	// 48 = 0x30
    NSDictionary *_systemAutomationProperties;	// 56 = 0x38
    struct CGVector _originalOffset;	// 64 = 0x40
    struct CGSize _parentWindowSize;	// 80 = 0x50
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000003154
- (void).cxx_destruct;	// IMP=0x0020000000004209
@property struct CGSize parentWindowSize; // @synthesize parentWindowSize=_parentWindowSize;
@property(copy) NSDictionary *systemAutomationProperties; // @synthesize systemAutomationProperties=_systemAutomationProperties;
@property(nonatomic) struct CGVector originalOffset; // @synthesize originalOffset=_originalOffset;
@property _Bool endsPersistentState; // @synthesize endsPersistentState=_endsPersistentState;
@property _Bool beginsPersistentState; // @synthesize beginsPersistentState=_beginsPersistentState;
@property(readonly) unsigned long long displayID; // @synthesize displayID=_displayID;
@property long long targetProcessID; // @synthesize targetProcessID=_targetProcessID;
@property(readonly) long long interfaceOrientation; // @synthesize interfaceOrientation=_interfaceOrientation;
@property(readonly, copy) NSString *name; // @synthesize name=_name;
- (id)description;	// IMP=0x0010000000003e74
@property(readonly) double maximumOffset;
- (void)addPointerEventPath:(id)arg1;	// IMP=0x0010000000003ba2
@property(readonly) NSArray *eventPaths;
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000394f
- (unsigned long long)hash;	// IMP=0x0010000000003910
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000000036ed
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000000325f
- (id)initWithName:(id)arg1 interfaceOrientation:(long long)arg2;	// IMP=0x0010000000003248
- (id)initWithName:(id)arg1 displayID:(unsigned long long)arg2;	// IMP=0x0010000000003233
- (id)initWithName:(id)arg1;	// IMP=0x001000000000321c
- (void)unsetInterfaceOrientation;	// IMP=0x0010000000003207
- (id)initWithName:(id)arg1 displayID:(unsigned long long)arg2 interfaceOrientation:(long long)arg3;	// IMP=0x001000000000315c

@end

