//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface AXManagedAssetTaskRestorationState : NSObject
{
    NSString *_taskID;	// 8 = 0x8
    NSString *_assetType;	// 16 = 0x10
    NSString *_phase;	// 24 = 0x18
    NSString *_lastExitStatus;	// 32 = 0x20
    NSDate *_date;	// 40 = 0x28
}

+ (id)restoreOrCreateStateFromStore:(id)arg1 taskID:(id)arg2 assetType:(id)arg3;	// IMP=0x004000000000a5e0
+ (id)idleStateWithTaskID:(id)arg1 assetType:(id)arg2;	// IMP=0x001000000000a4f0
- (void).cxx_destruct;	// IMP=0x002000000000b230
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSString *lastExitStatus; // @synthesize lastExitStatus=_lastExitStatus;
@property(retain, nonatomic) NSString *phase; // @synthesize phase=_phase;
@property(retain, nonatomic) NSString *assetType; // @synthesize assetType=_assetType;
@property(retain, nonatomic) NSString *taskID; // @synthesize taskID=_taskID;
- (_Bool)previousTaskWasDeferred;	// IMP=0x001000000000b040
- (_Bool)previousTaskDidFail;	// IMP=0x001000000000afe0
- (_Bool)previousTaskWasSuccessful;	// IMP=0x001000000000af80
- (void)updatePhase:(id)arg1 exitStatus:(id)arg2 saveToStore:(id)arg3;	// IMP=0x001000000000ada0
- (void)updatePhase:(id)arg1 saveToStore:(id)arg2;	// IMP=0x001000000000ad10
- (_Bool)isIdle;	// IMP=0x001000000000acb0
- (id)_restorationDictionary;	// IMP=0x001000000000ab50
- (id)_restorationKey;	// IMP=0x001000000000aac0
- (id)description;	// IMP=0x001000000000a9d0
- (id)_initWithPhase:(id)arg1 lastExitStatus:(id)arg2 date:(id)arg3 taskID:(id)arg4 assetType:(id)arg5;	// IMP=0x001000000000a810

@end

