//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSProxy.h>

@class OTManager;
@protocol OctagonEntitlementBearerProtocol;

@interface OctagonXPCEntitlementChecker : NSProxy
{
    OTManager *_manager;	// 8 = 0x8
    id <OctagonEntitlementBearerProtocol> _entitlementBearer;	// 16 = 0x10
}

+ (id)createWithManager:(id)arg1 entitlementBearer:(id)arg2;	// IMP=0x004000000013d80f
+ (_Bool)conformsToProtocol:(id)arg1;	// IMP=0x001000000013d7c6
- (void).cxx_destruct;	// IMP=0x002000000013d795
@property(retain) id <OctagonEntitlementBearerProtocol> entitlementBearer; // @synthesize entitlementBearer=_entitlementBearer;
@property(retain) OTManager *manager; // @synthesize manager=_manager;
- (void)failPersistAccountSettings:(id)arg1 setting:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x001000000013d67a
- (void)failFetchAccountWideSettingsWithForceFetch:(_Bool)arg1 arguments:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x001000000013d5a9
- (void)failFetchAccountSettings:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x001000000013d4d8
- (void)failSetAccountSetting:(id)arg1 setting:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x001000000013d40b
- (void)failFetchTrustedSecureElementIdentities:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x001000000013d33a
- (void)failRemoveLocalSecureElementIdentityPeerID:(id)arg1 secureElementIdentityPeerID:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x001000000013d26d
- (void)failSetLocalSecureElementIdentity:(id)arg1 secureElementIdentity:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x001000000013d1a0
- (void)failFetchEscrowContents:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x001000000013d0cb
- (void)forwardInvocation:(id)arg1;	// IMP=0x001000000013c7e3
- (id)methodSignatureForSelector:(SEL)arg1;	// IMP=0x001000000013c784
- (id)initWithManager:(id)arg1 entitlementBearer:(id)arg2;	// IMP=0x001000000013c708

@end

