//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SOSCKCircleStorage
{
}

- (struct __CFArray *)handleCircleMessagesAndReturnHandledCopy:(struct __CFDictionary *)arg1 err:(struct __CFError **)arg2;	// IMP=0x004000000020955a
- (struct __CFDictionary *)handleRetirementMessages:(struct __CFDictionary *)arg1 err:(struct __CFError **)arg2;	// IMP=0x0010000000209552
- (_Bool)postRetirement:(struct __CFString *)arg1 peer:(struct __OpaqueSOSPeerInfo *)arg2 err:(struct __CFError **)arg3;	// IMP=0x001000000020954a
- (_Bool)postCircle:(struct __CFString *)arg1 circleData:(struct __CFData *)arg2 err:(struct __CFError **)arg3;	// IMP=0x0010000000209542
- (_Bool)flushChanges:(struct __CFError **)arg1;	// IMP=0x001000000020953a
- (_Bool)expireRetirementRecords:(struct __CFDictionary *)arg1 err:(struct __CFError **)arg2;	// IMP=0x0010000000209532
- (id)getAccount;	// IMP=0x0010000000209520
- (long long)getTransportType;	// IMP=0x0010000000209515
- (id)initWithAccount:(id)arg1;	// IMP=0x00100000002094ad
- (id)init;	// IMP=0x0010000000209469

@end

