//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class SHAudioTapProvider;

@interface SHMatcherFactory : NSObject
{
    SHAudioTapProvider *_audioTapProvider;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000022e2e
@property(readonly, nonatomic) SHAudioTapProvider *audioTapProvider; // @synthesize audioTapProvider=_audioTapProvider;
- (id)buildConcurrentMatcherWithTapsCallback:(CDUnknownBlockType)arg1;	// IMP=0x0010000000022b44
- (id)matcherForRequest:(id)arg1 attribution:(id)arg2 clientType:(long long)arg3;	// IMP=0x00100000000227f5
- (id)initWithAudioTapProvider:(id)arg1;	// IMP=0x001000000002278a

@end

