//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;
@protocol OS_dispatch_queue;

@interface MCPOIBusynessLocationOfInterestManager : NSObject
{
    NSArray *_suppressedLocationsOfInterest;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
}

+ (id)sharedLocationOfInterestManagerInstance;	// IMP=0x002000000000565e
- (void).cxx_destruct;	// IMP=0x0020000000006689
- (_Bool)isUserAtSuppressedLocationsOfInterest:(id)arg1;	// IMP=0x001000000000612a
- (id)suppressedLocationsOfInterestUUIDs;	// IMP=0x0010000000005f71
- (void)fetchSuppressedLocationsOfInterestWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000059e7
- (void)_fetchLocationsOfInterest:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000005735
- (id)init;	// IMP=0x00100000000056b3

@end

