//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface FASettingPresetsCache : NSObject
{
}

+ (id)cacheQueue;	// IMP=0x00200000000184c4
- (id)invalidate;	// IMP=0x0020000000019350
- (id)updateWithPresets:(id)arg1 requestURL:(id)arg2;	// IMP=0x0010000000018e0b
- (id)_createCacheFile;	// IMP=0x0010000000018c23
- (id)_cacheURL;	// IMP=0x0010000000018b31
- (id)load:(id *)arg1;	// IMP=0x0010000000018953
- (id)loadForURL:(id)arg1;	// IMP=0x0010000000018721
- (id)_fetchData:(id *)arg1;	// IMP=0x0010000000018545
- (id)_cacheURLWithError:(id *)arg1;	// IMP=0x001000000001846d
- (id)_cacheDirectoryURLWithError:(id *)arg1;	// IMP=0x001000000001831d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

