//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewController.h>

@class NSDateFormatter, PKJob;

@interface PKPrintStatusTableViewController : UITableViewController
{
    PKJob *_printJob;	// 8 = 0x8
    NSDateFormatter *_sentFormatter;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000000411a
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00100000000040de
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00100000000040b4
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000003434
- (id)localizedOptionsForSettings:(id)arg1;	// IMP=0x0010000000002e91
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0010000000002d02
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0010000000002cf7
- (void)updateJobInfo;	// IMP=0x0010000000002c35
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0010000000002b69
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000002a82
- (void)cancelPrinting;	// IMP=0x00100000000029b8
- (void)popToJobsView;	// IMP=0x0010000000002903
- (void)updateCancelButton;	// IMP=0x00100000000028c6
- (void)loadView;	// IMP=0x001000000000281c
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;	// IMP=0x0010000000002771
- (void)dealloc;	// IMP=0x00100000000026fc
- (id)initWithJob:(id)arg1;	// IMP=0x0010000000002624

@end

