//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE;

@interface _TtC5Files17DOCColumnViewCell : UICollectionViewCell
{
    MISSING_TYPE *browserContainerController;	// 8 = 0x8
    MISSING_TYPE *navigationFocusGuide;	// 16 = 0x10
    MISSING_TYPE *separatorView;	// 24 = 0x18
    MISSING_TYPE *separatorThicknessConstraint;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00400000002772d0
- (void)prepareForReuse;	// IMP=0x00100000002771e0
- (void)layoutSubviews;	// IMP=0x0010000000276b30
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000276a30
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000276a00

@end

