//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC5Files40DOCProgressCollectionIndicatorButtonItem
{
    MISSING_TYPE *progressSource;	// 8 = 0x8
    MISSING_TYPE *configuration;	// 24 = 0x18
    MISSING_TYPE *viewControllerForPresentationFallback;	// 32 = 0x20
    MISSING_TYPE *containerView;	// 40 = 0x28
    MISSING_TYPE *indicatorView;	// 48 = 0x30
    MISSING_TYPE *widthConstraint;	// 56 = 0x38
    MISSING_TYPE *metrics;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x004000000036c4a0
- (id)init;	// IMP=0x001000000036c3e0

@end

