//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/_UIContentUnavailableView.h>

@interface _TtC5FilesP33_EBE2DA6178484455F79AECAF4845EF6C20DOCGoToNoResultsView : _UIContentUnavailableView
{
}

- (id)initWithCoder:(id)arg1;	// IMP=0x00400000001c32f0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000001c3290
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 style:(unsigned long long)arg3 includeBackdrop:(_Bool)arg4;	// IMP=0x00100000001c31d0
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 style:(unsigned long long)arg3;	// IMP=0x00100000001c3110
- (double)_labelAlpha;	// IMP=0x00100000001c30d0

@end

