//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE, UIScrollView;
@protocol _TtP5Files30DOCItemInfoContentTagsDelegate_, _TtP5Files34DOCBrowserContainedActionReporting_;

@interface _TtC5Files32DOCItemInfoContentViewController : UIViewController
{
    MISSING_TYPE *source;	// 8 = 0x8
    MISSING_TYPE *configuration;	// 16 = 0x10
    MISSING_TYPE *actionManager;	// 24 = 0x18
    MISSING_TYPE *documentManager;	// 32 = 0x20
    MISSING_TYPE *layoutMargins;	// 40 = 0x28
    MISSING_TYPE *actionDelegate;	// 72 = 0x48
    MISSING_TYPE *eventReporting;	// 80 = 0x50
    MISSING_TYPE *actionReporting;	// 96 = 0x60
    MISSING_TYPE *tagsWorkflowDelegate;	// 104 = 0x68
    MISSING_TYPE *showsShareButton;	// 112 = 0x70
    MISSING_TYPE *$__lazy_storage_$_thumbnailView;	// 120 = 0x78
    MISSING_TYPE *$__lazy_storage_$_filenameTitleLabel;	// 128 = 0x80
    MISSING_TYPE *$__lazy_storage_$_shareStatusLabel;	// 136 = 0x88
    MISSING_TYPE *$__lazy_storage_$_kindAndSizeView;	// 144 = 0x90
    MISSING_TYPE *$__lazy_storage_$_syncingErrorLabel;	// 152 = 0x98
    MISSING_TYPE *$__lazy_storage_$_downloadButton;	// 160 = 0xa0
    MISSING_TYPE *$__lazy_storage_$_metadataSectionLabel;	// 168 = 0xa8
    MISSING_TYPE *$__lazy_storage_$_metadataTitleRowSeparator;	// 176 = 0xb0
    MISSING_TYPE *$__lazy_storage_$_metadataTitleRow;	// 184 = 0xb8
    MISSING_TYPE *$__lazy_storage_$_showMoreMetadataButton;	// 192 = 0xc0
    MISSING_TYPE *$__lazy_storage_$_metadataView;	// 200 = 0xc8
    MISSING_TYPE *$__lazy_storage_$_tagsTitleRowSeparator;	// 208 = 0xd0
    MISSING_TYPE *$__lazy_storage_$_tagsTitleRow;	// 216 = 0xd8
    MISSING_TYPE *$__lazy_storage_$_tagsSectionTitleLabel;	// 224 = 0xe0
    MISSING_TYPE *$__lazy_storage_$_addTagsButton;	// 232 = 0xe8
    MISSING_TYPE *$__lazy_storage_$_tagView;	// 240 = 0xf0
    MISSING_TYPE *$__lazy_storage_$_actionsView;	// 248 = 0xf8
    MISSING_TYPE *$__lazy_storage_$_shareButton;	// 256 = 0x100
    MISSING_TYPE *$__lazy_storage_$_shareView;	// 264 = 0x108
    MISSING_TYPE *$__lazy_storage_$_actionsRow;	// 272 = 0x110
    MISSING_TYPE *$__lazy_storage_$_stackView;	// 280 = 0x118
    MISSING_TYPE *$__lazy_storage_$_scrollView;	// 288 = 0x120
    MISSING_TYPE *attributionView;	// 296 = 0x128
    MISSING_TYPE *tagViewController;	// 304 = 0x130
    MISSING_TYPE *actionsForCurrentActivityViewController;	// 312 = 0x138
    MISSING_TYPE *thumbnail;	// 320 = 0x140
    MISSING_TYPE *nodeObserver;	// 328 = 0x148
    MISSING_TYPE *hasMetadataViewFinishedInitialLoad;	// 336 = 0x150
    MISSING_TYPE *lastThumbnailSize;	// 344 = 0x158
}

- (void).cxx_destruct;	// IMP=0x0040000000190f10
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000190ea0
- (void)openSelectedItem:(id)arg1;	// IMP=0x001000000018f4c0
- (void)documentPreviewTappedWithSender:(id)arg1;	// IMP=0x001000000018eae0
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x001000000018eaa0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x001000000018e9a0
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x001000000018e520
- (void)viewDidMoveToWindow:(id)arg1 shouldAppearOrDisappear:(_Bool)arg2;	// IMP=0x001000000018e3d0
- (double)layoutHeightForWidth:(double)arg1;	// IMP=0x001000000018e020
- (void)viewDidLayoutSubviews;	// IMP=0x001000000018dff0
- (void)viewWillLayoutSubviews;	// IMP=0x001000000018db30
- (void)viewDidLoad;	// IMP=0x001000000018d650
- (void)loadView;	// IMP=0x001000000018c7b0
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000018c790
- (id)initWithConfiguration:(id)arg1 node:(id)arg2 source:(id)arg3 documentManager:(id)arg4 actionManager:(id)arg5 actionDelegate:(id)arg6;	// IMP=0x001000000018c440
@property(nonatomic, retain) UIScrollView *scrollView;
@property(nonatomic) _Bool showsItemLocation;
@property(nonatomic) _Bool showsShareButton; // @synthesize showsShareButton;
@property(nonatomic) __weak id <_TtP5Files30DOCItemInfoContentTagsDelegate_> tagsWorkflowDelegate; // @synthesize tagsWorkflowDelegate;
@property(nonatomic) __weak id <_TtP5Files34DOCBrowserContainedActionReporting_> actionReporting; // @synthesize actionReporting;
@property(nonatomic) struct UIEdgeInsets layoutMargins; // @synthesize layoutMargins;

@end

