//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class STKYesNoSessionAction;

@interface STKYesNoInputAlertViewController
{
}

- (void)noPressed:(id)arg1;	// IMP=0x0020000000005a38
- (void)yesPressed:(id)arg1;	// IMP=0x00100000000059db
- (id)newBottomBar;	// IMP=0x0010000000005581
- (_Bool)validateAction:(id)arg1;	// IMP=0x0010000000005536

// Remaining properties
@property(readonly, nonatomic) STKYesNoSessionAction *sessionAction; // @dynamic sessionAction;

@end

