//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class SSSQLiteDatabase;

@interface AccountCacheDBClient : NSObject
{
    SSSQLiteDatabase *_database;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000002cb0e
- (id)_databasePath;	// IMP=0x001000000002ca4b
- (id)dSIDForAppleID:(id)arg1;	// IMP=0x001000000002c8b6
- (id)init;	// IMP=0x001000000002c810

@end

