//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSSet, NSString;

@interface DownloadManagerClient
{
    NSSet *_downloadKinds;	// 48 = 0x30
    _Bool _isDownloadsEntitled;	// 56 = 0x38
    NSString *_persistenceIdentifier;	// 64 = 0x40
    NSArray *_prefetchedDownloadExternalProperties;	// 72 = 0x48
    NSArray *_prefetchedDownloadProperties;	// 80 = 0x50
    _Bool _shouldFilterExternalDownloads;	// 88 = 0x58
}

- (_Bool)_supportsDownloadKind:(id)arg1;	// IMP=0x00200000000b631f
- (void);	// IMP=0x00100000000b6119
- (_Bool)_isBackgroundApp;	// IMP=0x00100000000b60ec
- (id)_copyFilteredKindsForKinds:(id)arg1;	// IMP=0x00100000000b5dd7
- (id)_copyPrivateDownloadKinds;	// IMP=0x00100000000b5d19
- (id)_copyDownloadKindsFromEntitlement;	// IMP=0x00100000000b5c99
- (id)_copyAllowedThirdPartyKinds;	// IMP=0x00100000000b5c1a
- (_Bool)hasEntitlements;	// IMP=0x00100000000b5bdc
- (_Bool)supportsDownloadKind:(id)arg1;	// IMP=0x00100000000b5b10
@property _Bool shouldFilterExternalDownloads;
@property(copy) NSArray *prefetchedDownloadExternalProperties;
@property(copy) NSArray *prefetchedDownloadProperties;
@property(copy) NSString *persistenceIdentifier;
@property(copy) NSSet *downloadKinds;
- (void)setClientOptions:(id)arg1;	// IMP=0x00100000000b5614
- (void)sendDownloadsUpdatedWithIdentifiers:(id)arg1;	// IMP=0x00100000000b55fa
- (void)sendDownloadStatesChangedWithIdentifiers:(id)arg1;	// IMP=0x00100000000b55e0
- (void)sendDownloadStateChangedWithID:(long long)arg1 externalValues:(id)arg2 propertyValues:(id)arg3;	// IMP=0x00100000000b54cf
- (void)sendDownloadsRemovedWithIdentifiers:(id)arg1;	// IMP=0x00100000000b54b5
- (void)sendDownloadKindsUsingNetwork:(id)arg1;	// IMP=0x00100000000b5404
- (void)sendChangeset:(id)arg1;	// IMP=0x00100000000b50fb
- (_Bool)reloadPersistenceStateInDatabase:(id)arg1;	// IMP=0x00100000000b49e8
- (id)persistentDownloadManagerInDatabase:(id)arg1;	// IMP=0x00100000000b46f6
- (id)newDownloadWithClientXPCDownload:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000b3cfe
- (id)downloadsQueryForMessage:(id)arg1 database:(id)arg2;	// IMP=0x00100000000b3824
- (_Bool)canAccessDownload:(id)arg1;	// IMP=0x00100000000b3612
- (_Bool)canAccessAsset:(id)arg1;	// IMP=0x00100000000b3561
- (void)addClientEntityToDatabase:(id)arg1;	// IMP=0x00100000000b3444
- (void)dealloc;	// IMP=0x00100000000b33d0
- (id)initWithInputConnection:(id)arg1;	// IMP=0x00100000000b3343

@end

