//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <StoreServices/SSSQLiteQuery.h>

@interface SSSQLiteQuery (DirectUploadEntity)
- (void)enumerateSSVDirectUploadsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000117ebc
@end

