//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ICQLinkAppDelegate_iOS
{
}

- (void)launchURL:(id)arg1;	// IMP=0x0040000000001e37
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000001e22
- (void)launchFlowWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000001bab
- (void)launchSettingsDeeplink;	// IMP=0x0010000000001af6
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;	// IMP=0x0010000000001a6b
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0010000000001a63

@end

