//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface HSPCEnterCodeViewController
{
    unsigned long long _numberOfDigits;	// 8 = 0x8
}

@property(nonatomic) unsigned long long numberOfDigits; // @synthesize numberOfDigits=_numberOfDigits;
- (id)_stringByApplyingMatter21DigitFormatToString:(id)arg1;	// IMP=0x001000000002527e
- (id)_stringByApplyingMatter11DigitFormatToString:(id)arg1;	// IMP=0x00100000000251c4
- (id)_stringByApplyingHomeKit8DigitFormatToString:(id)arg1;	// IMP=0x001000000002513f
- (id)_stringByApplyingCodeFormatToString:(id)arg1;	// IMP=0x001000000002509e
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;	// IMP=0x0010000000024c0f
- (void)configureNextViewController:(id)arg1;	// IMP=0x0010000000024b8d
- (id)onCameraButton;	// IMP=0x0010000000024b6d
- (id)commitConfiguration;	// IMP=0x0010000000024769
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00100000000246ff
- (void)viewDidLoad;	// IMP=0x001000000002453c
- (id)initWithCoordinator:(id)arg1 config:(id)arg2;	// IMP=0x0010000000024427

@end

