//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class HMRoom, NSArray;

@interface HSPCHomeKitRoomProvider
{
    NSArray *_existingRooms;	// 8 = 0x8
    HMRoom *_suggestedRoom;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000545e0
@property(readonly) HMRoom *suggestedRoom; // @synthesize suggestedRoom=_suggestedRoom;
@property(readonly, copy) NSArray *existingRooms; // @synthesize existingRooms=_existingRooms;
- (id)_generateRoomSuggestionsWithLimit:(long long)arg1 existingRooms:(id)arg2;	// IMP=0x001000000005436e
- (unsigned long long)initialRowIndex;	// IMP=0x0010000000054244
- (id)userFacingStringForItem:(id)arg1;	// IMP=0x0010000000054041
- (id)loadData;	// IMP=0x0010000000053df4
- (id)initWithCoordinator:(id)arg1 configuration:(id)arg2;	// IMP=0x0010000000053b74

@end

