//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface HSPCNameZonesViewController
{
}

+ (id)applicableServicesForAccessory:(id)arg1;	// IMP=0x0040000000045e68
- (_Bool)shouldServiceStartEnabled:(id)arg1;	// IMP=0x00400000000461cf
- (id)initWithCoordinator:(id)arg1 config:(id)arg2;	// IMP=0x0010000000046145

@end

