//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UINavigationController.h>

@class HMHome, HMHomeManager, NSString, NSUUID;

@interface HSUserManagementViewController : UINavigationController
{
    _Bool _didNotifyFinishLoading;	// 8 = 0x8
    HMHomeManager *_homeManager;	// 16 = 0x10
    HMHome *_home;	// 24 = 0x18
    NSUUID *_homeUUID;	// 32 = 0x20
}

+ (id)_exportedInterface;	// IMP=0x002000000004641d
+ (id)_remoteViewControllerInterface;	// IMP=0x0010000000046404
- (void).cxx_destruct;	// IMP=0x0020000000046b94
@property(nonatomic) _Bool didNotifyFinishLoading; // @synthesize didNotifyFinishLoading=_didNotifyFinishLoading;
@property(retain, nonatomic) NSUUID *homeUUID; // @synthesize homeUUID=_homeUUID;
@property(retain, nonatomic) HMHome *home; // @synthesize home=_home;
@property(retain, nonatomic) HMHomeManager *homeManager; // @synthesize homeManager=_homeManager;
- (void)_notifyHostAndDismissWithError:(id)arg1;	// IMP=0x0010000000046aa7
- (void)controllerDidSendInvitations:(id)arg1;	// IMP=0x0010000000046a32
- (void)controllerDidDismissWithError:(id)arg1;	// IMP=0x0010000000046a20
- (void)addPeopleViewController:(id)arg1 didSendInvitations:(id)arg2;	// IMP=0x00100000000469ab
- (void)addPeopleViewControllerDidCancel:(id)arg1;	// IMP=0x0010000000046997
- (void)_updateViewControllers;	// IMP=0x00100000000467c0
- (void)_notifyRemoteReadyToDisplayIfNeeded;	// IMP=0x0010000000046717
- (void)_updateHome;	// IMP=0x0010000000046490
- (void)homeManagerDidUpdateHomes:(id)arg1;	// IMP=0x001000000004647e
- (id)initWithRootViewController:(id)arg1;	// IMP=0x001000000004633b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

